/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface _ABAddressBookCopyLocalizedLabel (SBTimeUtilities)
- (BOOL)date:(id)fp8 isSameYearAsDate:(id)fp12;
- (BOOL)date:(id)fp8 isSameDayAsDate:(id)fp12;
- (id)_timeOnlyComponentsForDate:(id)fp8;
- (id)_dateOnlyComponentsForDate:(id)fp8;
@end

