/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface _ABAddressBookCopyLocalizedLabel (SBIconIndex)
+ (id)indexPathWithIconIndex:(unsigned int)fp8 listIndex:(unsigned int)fp12;
+ (id)emptyPath;
- (BOOL)isPrefixedByPath:(id)fp8;
- (id)indexPathWithPrefixPath:(id)fp8;
- (id)subpathFromPosition:(unsigned int)fp8;
- (id)_subpathWithRange:(struct _NSRange)fp8;
@end

