/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface _ABAddressBookCopyLocalizedLabel (SBStringDrawing)
- (void)drawWithMetrics:(id)fp8 inContext:(struct CGContext *)fp12;
- (id)stringMetricsForFirstLineWidth:(float)fp8;
@end

