/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface _ABAddressBookCopyLocalizedLabel (CTHelpers)
- (id)callingNamePresentationValue;
- (struct __CFString *)settingType;
- (id)mmiProcedure;
- (id)ssServiceType;
- (id)serviceCenterAddress;
- (id)enabledString;
- (id)connectedLinePresentationValue;
- (id)connectedLineIDRestrictionValue;
- (id)callingLinePresentationValue;
- (id)callingLineIDRestrictionValue;
- (id)callBarringFacility;
- (id)callForwardingReason;
- (id)callClass;
@end

