/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface _ABAddressBookCopyLocalizedLabel (PrefsNotifications)
- (id)prefsNotificationsAlertString;
- (id)_alertStringForPref:(id)fp8;
- (id)_callingNamePresentationString:(id)fp8;
- (id)_ssPasswordString:(id)fp8;
- (id)_serviceCenterAddressString:(id)fp8;
- (id)_simLockString:(id)fp8;
- (id)_callingLineIDRestrictionString:(id)fp8;
- (id)_connectedLineIDRestrictionString:(id)fp8;
- (id)_callingLinePresentationString:(id)fp8;
- (id)_connectedLinePresentationString:(id)fp8;
- (id)_fixedDialingString:(id)fp8;
- (id)_callBarringString:(id)fp8;
- (id)_callWaitingString:(id)fp8;
- (id)_callForwardingString:(id)fp8;
- (void)addPrefNotification:(id)fp8 withUserInfo:(id)fp12;
@end

