/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface _ABAddressBookCopyLocalizedLabel (SBGraphics)
+ (id)sbg_imageFromContextWithSize:(struct CGSize)fp8 scale:(float)fp16 type:(int)fp20 pool:(id)fp24 drawing:(id)fp(null) encapsulation:(void)fp28;
+ (id)sbg_imageFromContextWithSize:(struct CGSize)fp8 scale:(float)fp16 type:(int)fp20 pool:(id)fp24 drawing:(id)fp(null);
+ (unsigned long)sbg_bytesNeededForSize:(struct CGSize)fp8 scale:(float)fp16 withContextType:(int)fp20;
@end

