/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BBWeeAppControllerHost <NSObject>
- (BOOL)weeApp:(id)fp8 updatePresentationMode:(int)fp12 duration:(float)fp16 delay:(float)fp20;
- (int)weeAppPresentationMode:(id)fp8;
- (BOOL)weeAppWantsNotificationCenterDismissal:(id)fp8;
- (void)weeAppWantsSizeUpdate:(id)fp8;
@end

