/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BKSWorkspaceDelegate <NSObject>
- (void)workspace:(id)fp8 applicationDebugStateChanged:(id)fp12 newState:(BOOL)fp16;
- (void)workspace:(id)fp8 handleStatusBarReturnActionFromApplication:(id)fp12 statusBarStyle:(id)fp16;
- (void)workspace:(id)fp8 handleOpenURL:(id)fp12 fromApplication:(id)fp16;
- (void)workspace:(id)fp8 applicationSuspensionSettingsUpdated:(id)fp12 withSettings:(id)fp16;
- (void)workspace:(id)fp8 applicationExited:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationSuspended:(id)fp12 withSettings:(id)fp16;
- (void)workspace:(id)fp8 applicationActivated:(id)fp12;
- (void)workspace:(id)fp8 applicationDidFailToLaunch:(id)fp12;
- (void)workspace:(id)fp8 applicationDidFinishLaunching:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationDidStartLaunching:(id)fp12;
- (void)workspaceDidResume:(id)fp8;
- (void)workspaceWillResume:(id)fp8;
- (void)workspaceDidSuspend:(id)fp8;
- (void)workspaceWillSuspend:(id)fp8;
- (void)workspace:(id)fp8 applicationDidBecomeReceiver:(id)fp12 fromApplication:(id)fp16;
- (id)workspace:(id)fp8 applicationWillBecomeReceiver:(id)fp12 fromApplication:(id)fp16;
@end

