/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct BKSDisplayBrightnessTransaction;

struct CATransform3D {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
};

struct CGAffineTransform {
    float a;
    float b;
    float c;
    float d;
    float tx;
    float ty;
};

struct CGContext;

struct CGImage;

struct CGPath;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct UIEdgeInsets {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct _CARenderImage;

struct _MISProfile;

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSZone;

struct __CFBoolean;

struct __CFDictionary;

struct __CFMachPort;

struct __CFString;

struct __CTCall;

struct __CTServerConnection;

struct __GSEvent;

struct __SBGestureContext;

struct __SCDynamicStore;

struct __WiFiDeviceClient;

struct __WiFiManagerClient;

struct __WiFiNetwork;

struct __darwin_pthread_handler_rec;

struct _opaque_pthread_mutex_t {
    long __sig;
    char __opaque[40];
};

struct _opaque_pthread_t {
    long _field1;
    struct __darwin_pthread_handler_rec *_field2;
    char _field3[596];
};

struct tcp_connection_fallback_watch_s;

struct vImage_Buffer {
    void *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
};

typedef struct {
    char _field1[24];
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :2;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    CDAnonymousStruct1 _field2;
} CDAnonymousStruct2;

typedef struct {
    float x;
    float y;
    float scale;
    float rotate;
} CDAnonymousStruct9;

typedef struct {
    int startStyle;
    int startOrientation;
    int endStyle;
    int endOrientation;
    int transitionType;
    char zoomOther;
} CDAnonymousStruct3;

typedef struct {
    int _field1;
    int _field2;
} CDAnonymousStruct4;

typedef struct {
    unsigned int _field1[8];
} CDAnonymousStruct5;

typedef struct {
    int direction;
    struct CGRect rect;
} CDAnonymousStruct6;

typedef struct {
    int type;
    unsigned int pathIndex;
    struct CGPoint location;
    struct CGPoint previousLocation;
    float totalDistanceTraveled;
    int interfaceOrientation;
    int previousInterfaceOrientation;
} CDAnonymousStruct7;

typedef struct {
    unsigned long _field1;
    id *_field2;
    unsigned long *_field3;
    unsigned long _field4[5];
} CDAnonymousStruct8;

typedef struct {
    char itemIsEnabled[24];
    char timeString[64];
    int gsmSignalStrengthRaw;
    int gsmSignalStrengthBars;
    char serviceString[100];
    char serviceCrossfadeString[100];
    char serviceImages[2][100];
    char operatorDirectory[1024];
    unsigned int serviceContentType;
    int wifiSignalStrengthRaw;
    int wifiSignalStrengthBars;
    unsigned int dataNetworkType;
    int batteryCapacity;
    unsigned int batteryState;
    char batteryDetailString[150];
    int bluetoothBatteryCapacity;
    int thermalColor;
    unsigned int thermalSunlightMode:1;
    unsigned int slowActivity:1;
    unsigned int syncActivity:1;
    char activityDisplayId[256];
    unsigned int bluetoothConnected:1;
    unsigned int displayRawGSMSignal:1;
    unsigned int displayRawWifiSignal:1;
    unsigned int locationIconType:1;
} CDAnonymousStruct1;

