/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "NSCopying-Protocol.h"

@class NSHashTable, NSMapTable;

@interface SBActivationContext : _ABAddressBookCopyLocalizedLabel <NSCopying>
{
    NSMapTable *_activationValues;
    NSMapTable *_deactivationValues;
    NSHashTable *_activationFlags;
    NSHashTable *_deactivationFlags;
}

+ (id)newFlagTable;
+ (id)newValueTable;
+ (id)contextFromDisplay:(id)fp8;
- (void)setDeactivationFlags:(id)fp8;
- (id)deactivationFlags;
- (void)setActivationFlags:(id)fp8;
- (id)activationFlags;
- (void)setDeactivationValues:(id)fp8;
- (id)deactivationValues;
- (void)setActivationValues:(id)fp8;
- (id)activationValues;
- (id)_deactivationSettingsDescription;
- (id)_descriptionForDeactivationSetting:(unsigned int)fp8;
- (id)_activationSettingsDescription;
- (id)_descriptionForActivationSetting:(unsigned int)fp8;
- (id)_descriptionForDisplaySetting:(unsigned int)fp8;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (BOOL)deactivationFlag:(unsigned int)fp8;
- (id)deactivationValue:(unsigned int)fp8;
- (void)setDeactivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDeactivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDeactivationSettings;
- (BOOL)activationFlag:(unsigned int)fp8;
- (id)activationValue:(unsigned int)fp8;
- (void)setActivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setActivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearActivationSettings;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithDisplay:(id)fp8;

@end

