/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"

@class BBObserver, CPDistributedNotificationCenter, NSMutableArray, NSMutableSet, NSTimer;

@interface SBAlertItemsController : _ABAddressBookCopyLocalizedLabel <BBObserverDelegate>
{
    NSMutableArray *_lockedAlertItems;
    NSMutableArray *_unlockedAlertItems;
    NSMutableArray *_pendingAlertItems;
    NSMutableArray *_superModalAlertItems;
    NSTimer *_autoDismissTimer;
    CPDistributedNotificationCenter *_notificationCenter;
    unsigned int _notificationClientCount;
    BOOL _systemShuttingDown;
    NSMutableSet *_forceAlertsToPendReasons;
    BBObserver *_bbObserver;
}

+ (id)sharedInstance;
- (id)lockedAlertItems;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (void)_buddyDidExit;
- (void)_notificationClientEnded:(id)fp8;
- (void)_notificationClientStarted:(id)fp8;
- (void)moveActiveAlertsToPendingWithAnimation:(BOOL)fp8;
- (void)setForceAlertsToPend:(BOOL)fp8 forReason:(id)fp12;
- (void)noteSystemShuttingDown;
- (void)notifySystemOfAlertItemActivation:(id)fp8;
- (void)_postAlertPresentedNotificationForType:(int)fp8 sender:(id)fp12 date:(id)fp16;
- (void)noteVolumeOrLockPressedOverLockedAlerts;
- (void)deactivateAlertItemsForAlertActivationAndPendMiniAlerts:(BOOL)fp8;
- (BOOL)dontLockOverAlertItems;
- (BOOL)deactivateAlertForMenuClickOrSystemGestureWithAnimation:(BOOL)fp8;
- (BOOL)canDeactivateAlertForMenuClickOrSystemGesture;
- (id)visibleAlertItem;
- (BOOL)hasVisibleAlert;
- (BOOL)hasAlerts;
- (BOOL)hasAlertOfClass:(Class)fp8;
- (id)alertItemsOfClass:(Class)fp8;
- (id)alertItemOfClass:(Class)fp8;
- (void)autoDismissAlertItem:(id)fp8;
- (void)deactivateVisibleAlertItemOfClass:(Class)fp8 reason:(int)fp12;
- (void)deactivateAlertItemsOfClass:(Class)fp8 reason:(int)fp12 animated:(BOOL)fp16;
- (void)deactivateAlertItemsOfClass:(Class)fp8 reason:(int)fp12;
- (void)deactivateAlertItemsOfClass:(Class)fp8;
- (void)deactivateAlertItem:(id)fp8;
- (void)deactivateAlertItem:(id)fp8 reason:(int)fp12 animated:(BOOL)fp16;
- (void)activatePendedAlertsIfNecessary;
- (void)_activateSuperModalAlertsIfNecessary;
- (void)deactivateAlertItem:(id)fp8 reason:(int)fp12;
- (void)activateAlertItem:(id)fp8;
- (void)resetAutoDismissTimer;
- (void)convertUnlockedAlertsToLockedAlerts;
- (id)description;
- (BOOL)hasVisibleSuperModalAlert;
- (void)dealloc;
- (id)init;

@end

