/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, SBAlertWindow;

@interface SBAlertManager : _ABAddressBookCopyLocalizedLabel
{
    SBAlertWindow *_alertWindow;
    SBAlertWindow *_deferredAlertWindow;
    NSMutableArray *_alerts;
    BOOL _deactivatingAllAlerts;
    id <SBAlertManagerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)_deactivateAfterNextLaunch:(id)fp8;
- (void)_updateSEOStatus;
- (void)_tearDownAlertWindow:(id)fp8;
- (id)debugDescription;
- (id)description;
- (void)removeFromView:(id)fp8;
- (void)_updateStatusBarTimeItemEnabled;
- (struct CGRect)_alertWindowRect;
- (int)orientation;
- (void)noteOrientationChanged:(int)fp8;
- (void)workspaceDidAnimateSuspendingApp;
- (void)workspaceWillAnimateActivatingApp;
- (void)deactivateAlertsAfterLaunch;
- (void)setAlertsShouldDeactivateAfterLaunch;
- (void)deactivateAll;
- (BOOL)containsAlert:(id)fp8;
- (void)_deactivate:(id)fp8;
- (void)deactivate:(id)fp8;
- (void)_activate:(id)fp8;
- (void)activate:(id)fp8;
- (id)allAlerts;
- (BOOL)hasStackedAlerts;
- (id)activeAlert;
- (id)window;
- (void)dealloc;
- (id)init;

@end

