/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBDisplayProtocol-Protocol.h"

@class NSHashTable, NSMapTable, NSMutableDictionary, SBActivationContext, SBAlertView;

@interface SBAlert : _ABAddressBookCopyLocalizedLabel <SBDisplayProtocol>
{
    SBAlertView *_display;
    NSMutableDictionary *_dictionary;
    BOOL _SEO;
    SBActivationContext *_activationContext;
    NSMapTable *_displayValues;
    NSHashTable *_displayFlags;
    BOOL _orientationChangedEventsEnabled;
    float _accelerometerSampleInterval;
    BOOL _expectsFaceContact;
    BOOL _expectsFaceContactInLandscape;
}

+ (id)_adapterForController:(id)fp8;
+ (void)alertAdapterDisplayDidDisappear:(id)fp8;
+ (void)deactivateAlertForController:(id)fp8 animated:(BOOL)fp12 animateOldDisplayInWithStyle:(int)fp16 isSlidingDisplay:(BOOL)fp20;
+ (void)activateAlertForController:(id)fp8 animated:(BOOL)fp12 animateCurrentDisplayOut:(BOOL)fp16 withDelay:(BOOL)fp20 isSlidingDisplay:(BOOL)fp24;
+ (void)test;
+ (id)alertWindow;
+ (void)registerForAlerts;
- (void)setSEO:(BOOL)fp8;
- (BOOL)SEO;
- (void)setActivationContext:(id)fp8;
- (id)activationContext;
- (BOOL)suppressesNotifications;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)fp8;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)hasTranslucentBackground;
- (BOOL)shouldPendAlertItemsWhileActive;
- (BOOL)shouldDeactivateAlertItemsOnActivation;
- (BOOL)handleMenuButtonTap;
- (void)animateDeactivation;
- (BOOL)currentlyAnimatingDeactivation;
- (void)didFinishAnimatingOut;
- (void)didFinishAnimatingIn;
- (void)didAnimateLockKeypadOut;
- (void)didAnimateLockKeypadIn;
- (int)statusBarStyle;
- (double)autoLockTime;
- (double)autoDimTime;
- (BOOL)allowsEventOnlySuspension;
- (BOOL)expectsFaceContactInLandscape;
- (BOOL)expectsFaceContact;
- (void)setExpectsFaceContact:(BOOL)fp8 inLandscape:(BOOL)fp12;
- (void)setExpectsFaceContact:(BOOL)fp8;
- (int)effectiveStatusBarStyle;
- (double)accelerometerSampleInterval;
- (void)setAccelerometerSampleInterval:(double)fp8;
- (BOOL)orientationChangedEventsEnabled;
- (void)setOrientationChangedEventsEnabled:(BOOL)fp8;
- (id)description;
- (void)deactivate;
- (void)removeFromView;
- (int)interfaceOrientationForActivation;
- (void)activate;
- (int)statusBarStyleOverridesToCancel;
- (Class)alertWindowClass;
- (struct CGRect)alertWindowRect;
- (float)finalAlpha;
- (BOOL)showsSpringBoardStatusBar;
- (BOOL)undimsDisplay;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (void)removeObjectForKey:(id)fp8;
- (id)objectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (id)deactivationValue:(unsigned int)fp8;
- (BOOL)deactivationFlag:(unsigned int)fp8;
- (void)setDeactivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDeactivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDeactivationSettings;
- (id)activationValue:(unsigned int)fp8;
- (BOOL)activationFlag:(unsigned int)fp8;
- (void)setActivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setActivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearActivationSettings;
- (BOOL)displayFlag:(unsigned int)fp8;
- (id)displayValue:(unsigned int)fp8;
- (void)setDisplaySetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDisplaySetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDisplaySettings;
- (void)clearDisplay;
- (void)setDisplay:(id)fp8;
- (id)display;
- (void)dealloc;
- (id)init;

@end

