/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBAlertManagerDelegate <NSObject>
- (void)alertManager:(id)fp8 didDeactivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 willDeactivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 didActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 willActivateAlert:(id)fp12 overAlerts:(id)fp16;
@end

