/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class SBAlert, SBUIAnimationController;

@interface SBAlertToAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerDelegate>
{
    SBAlert *_alert;
    SBUIAnimationController *_animation;
    BOOL _animatedAppActivation;
    BOOL _animatingAlertSuspension;
    BOOL _deactivateAfterNextLaunch;
    BOOL _activatingFromAssistant;
    BOOL _fadeAssistant;
}

- (id)alert;
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 didCommitAnimation:(BOOL)fp12 withDuration:(double)fp16 afterDelay:(double)fp24;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (void)_handleFailure;
- (void)_deactivateAlertIfNecessary;
- (void)_alertAnimationComplete:(id)fp8;
- (void)_transactionComplete;
- (void)_endAnimation;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)selfAlertDidDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfAlertWillDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (BOOL)selfApplicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationActivated:(id)fp8;
- (void)_commit;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 alert:(id)fp16 toApplication:(id)fp20;

@end

