/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMapTable, NSMutableArray, SBAlertView, UIView;

@interface SBAlertWindow : _ABAddressBookCopyLocalizedLabel
{
    UIView *_contentLayer;
    unsigned int _isAnimating:1;
    unsigned int _isInvalid:1;
    unsigned int _handlerActive:1;
    float _finalAlpha;
    int _currentOrientation;
    SBAlertView *_currentDisplay;
    NSMutableArray *_stackedAlertDisplays;
    NSMapTable *_alertToDisplayMap;
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;
- (void)noteInterfaceOrientationChangingTo:(int)fp8 animated:(BOOL)fp12;
- (void)window:(id)fp8 willAnimateFromContentFrame:(struct CGRect)fp12 toContentFrame:(struct CGRect)fp28;
- (void)window:(id)fp8 didRotateFromInterfaceOrientation:(int)fp12;
- (void)window:(id)fp8 willAnimateRotationToInterfaceOrientation:(int)fp12 duration:(double)fp16;
- (void)window:(id)fp8 willRotateToInterfaceOrientation:(int)fp12 duration:(double)fp16;
- (id)rotatingContentViewForWindow:(id)fp8;
- (BOOL)window:(id)fp8 shouldAutorotateToInterfaceOrientation:(int)fp12;
- (BOOL)shouldWindowUseOnePartInterfaceRotationAnimation:(id)fp8;
- (BOOL)_isSupportedInterfaceOrientation:(int)fp8;
- (void)_setupContentLayerForCurrentOrientation;
- (BOOL)handlerAlreadyActive;
- (void)setHandlerAlreadyActive:(BOOL)fp8;
- (id)currentDisplay;
- (void)alertDisplayWillDismiss;
- (void)dismissWindow:(id)fp8;
- (int)displayCount;
- (BOOL)hasActiveAlertsOrDisplays;
- (BOOL)deactivateAlert:(id)fp8;
- (void)displayAlert:(id)fp8;
- (id)contentLayer;
- (id)stackedDisplayForAlert:(id)fp8;
- (BOOL)isOpaque;
- (void)dealloc;
- (id)initWithContentRect:(struct CGRect)fp8;

@end

