/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class CADisplayLink, NSArray, UIView;

@interface SBAnimationStepper : _ABAddressBookCopyLocalizedLabel
{
    id m_delegate;
    UIView *m_view;
    NSArray *m_animatingSubviews;
    double m_duration;
    float m_percentage;
    CADisplayLink *m_displayLink;
    double m_finishBackwardTimestamp;
    double m_finishBackwardDuration;
    float m_finishBackwardPercentage;
}

- (float)percentage;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setAnimatingSubviews:(id)fp8;
- (id)animatingSubviews;
- (void)setView:(id)fp8;
- (id)view;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)updateFinishBackwardToStart:(id)fp8;
- (void)finishBackwardToStart;
- (void)finishForwardToEnd;
- (void)setPercentage:(float)fp8;
- (void)stepAnimationsInView:(id)fp8 animatingSubviews:(id)fp12 duration:(double)fp16;
- (void)dealloc;
- (id)init;

@end

