/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAppSwitcherScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, SBAppSwitcherScrollView, SBLinenView, UIView;

@interface SBAppSwitcherBarView : _ABAddressBookCopyLocalizedLabel <SBAppSwitcherScrollViewDelegate>
{
    id <SBAppSwitcherBarViewDelegate> _delegate;
    NSMutableDictionary *_visibleIconViewMap;
    NSMutableArray *_iconDisplayIDs;
    UIView *_contentView;
    SBLinenView *_backgroundView;
    NSMutableArray *_auxViews;
    SBAppSwitcherScrollView *_scrollView;
    BOOL _animateContentReflow;
    BOOL _animatedScrolling;
    int _reflowIconCount;
    int _lastPageIndex;
    unsigned int _firstVisibleIconIndex;
    unsigned int _lastVisibleIconIndex;
    BOOL _isVisible;
    BOOL _isEditing;
    struct CGPoint _savedPositionForSuspendGesture;
    int _orientation;
    NSNumber *_rotatingFromOrientationForFirstLayoutUse;
    BOOL _showFirstPageOnLayout;
    BOOL _rotating;
}

+ (float)edgePadding:(int)fp8;
+ (float)edgePaddingForWidth:(float)fp8;
+ (struct CGSize)viewSize:(int)fp8;
+ (unsigned int)iconsPerPage:(int)fp8;
- (BOOL)isEditing;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)viewDidRotateFromInterfaceOrientation:(int)fp8;
- (void)viewWillAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)viewWillRotateToInterfaceOrientation:(int)fp8;
- (void)restoreScrollPositionAfterSuspendGesture;
- (void)saveScrollPositionBeforeSuspendGesture;
- (BOOL)scrollView:(id)fp8 shouldCancelInContentForView:(id)fp12;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)_scrollingDidFinish;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)_setAnimatedScrolling:(BOOL)fp8;
- (void)_commonScrollingWillBegin;
- (void)_reflowAnimationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_layoutIconsInRange:(BOOL)fp8 minIndex:(unsigned int)fp12 maxIndex:(unsigned int)fp16;
- (void)_layoutIconsInVisibleRange:(BOOL)fp8;
- (void)_toggleIconViewEditingState:(id)fp8 animated:(BOOL)fp12;
- (unsigned int)iconIndexColumnOnPageAtPoint:(struct CGPoint)fp8 orientation:(int)fp16;
- (void)_computeVisibleIconIndexRange:(BOOL)fp8 forOrientation:(int)fp12 contentOffset:(struct CGPoint)fp16 firstIndex:(unsigned int *)fp24 lastIndex:(unsigned int *)fp28;
- (void)_setVisibleIconIndexRange:(BOOL)fp8;
- (float)_horizontalBumpForIconIndexOnPage:(unsigned int)fp8 orientation:(int)fp12;
- (id)_iconViewForIcon:(id)fp8 creatingIfNecessary:(BOOL)fp12;
- (id)_iconForDisplayIdentifier:(id)fp8;
- (id)visibleIconViewForDisplayIdentifier:(id)fp8;
- (int)_pageForIndex:(unsigned int)fp8 orientation:(int)fp12;
- (int)_pageForOffset:(struct CGPoint)fp8 withSize:(struct CGSize)fp16;
- (struct CGPoint)_firstPageOffset:(struct CGSize)fp8;
- (unsigned int)_pageCount:(int)fp8;
- (struct CGRect)_iconFrameForIndex:(unsigned int)fp8 withSize:(struct CGSize)fp12 orientation:(int)fp20;
- (void)_positionAtFirstPage:(BOOL)fp8;
- (void)_adjustScrollContentSize;
- (struct CGPoint)_newScrollContentOffsetFromOldOffset:(struct CGPoint)fp8 oldSize:(struct CGSize)fp16 oldOrientation:(int)fp24 toNewSize:(struct CGSize)fp28 newOrientation:(int)fp36;
- (void)_adjustContentOffsetForReflow:(BOOL)fp8;
- (BOOL)_isIndexVisible:(unsigned int)fp8;
- (void)_clearIconViews;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (BOOL)airPlayControlsVisible;
- (BOOL)nowPlayingControlsVisible;
- (void)addAuxiliaryViews:(id)fp8;
- (void)reloadOrRemoveIconWithDisplayIdentifier:(id)fp8;
- (void)_iconRemoveDidStop:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)removeIconWithDisplayIdentifier:(id)fp8;
- (void)addIconWithDisplayIdentifier:(id)fp8;
- (void)setEditing:(BOOL)fp8;
- (BOOL)isVisible;
- (BOOL)isScrolling;
- (id)displayIdentifiers;
- (void)prepareForDisplay:(id)fp8 showFirstPage:(BOOL)fp12 orientation:(int)fp16;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

