/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBShowcaseViewController.h"

#import "SBAppSwitcherBarViewDelegate-Protocol.h"
#import "SBIconViewDelegate-Protocol.h"
#import "SBIconViewMapDelegate-Protocol.h"

@class NSString, SBAppSwitcherBarView, SBAppSwitcherModel, SBNowPlayingBar, SBPrintStatusController;

@interface SBAppSwitcherController : SBShowcaseViewController <SBIconViewDelegate, SBAppSwitcherBarViewDelegate, SBIconViewMapDelegate>
{
    SBAppSwitcherModel *_model;
    SBNowPlayingBar *_nowPlayingBar;
    SBAppSwitcherBarView *_bottomBar;
    BOOL _editing;
    int _orientation;
    NSString *_topAppDisplayID;
    SBPrintStatusController *_printStatusController;
}

+ (id)sharedInstanceIfAvailable;
+ (id)sharedInstance;
- (void)setTopAppDisplayID:(id)fp8;
- (id)topAppDisplayID;
- (id)model;
- (void)restoreScrollPositionAfterSuspendGesture;
- (void)saveScrollPositionBeforeSuspendGesture;
- (void)appSwitcherBar:(id)fp8 pageAtIndexDidDisappear:(int)fp12;
- (void)appSwitcherBar:(id)fp8 pageAtIndexDidAppear:(int)fp12;
- (BOOL)appSwitcherBar:(id)fp8 scrollShouldCancelInContentForView:(id)fp12;
- (void)appSwitcherBarRemovedFromSuperview:(id)fp8;
- (BOOL)iconViewDisplaysBadges:(id)fp8;
- (void)iconCloseBoxTapped:(id)fp8;
- (int)closeBoxTypeForIcon:(id)fp8;
- (void)iconTouchBegan:(id)fp8;
- (void)iconHandleLongPress:(id)fp8;
- (BOOL)iconShouldAllowTap:(id)fp8;
- (void)iconTapped:(id)fp8;
- (Class)viewMap:(id)fp8 iconViewClassForIcon:(id)fp12;
- (int)viewMap:(id)fp8 locationForIcon:(id)fp12;
- (unsigned int)viewMap:(id)fp8 maxRecycledIconViewsOfClass:(Class)fp12;
- (BOOL)printViewIsShowing;
- (id)printIconView;
- (void)dismissPrintView;
- (void)removePrintStatusIconBadge;
- (void)setNeedsPrintStatusIcon:(BOOL)fp8;
- (void)_appActivationStateDidChange:(id)fp8;
- (id)_currentDownloads;
- (void)_removeApplicationFromRecents:(id)fp8;
- (void)_stopEditing;
- (void)_beginEditing;
- (BOOL)_inEditMode;
- (id)_bundleIdentifiersForViewDisplay;
- (BOOL)airPlayControlsVisible;
- (BOOL)nowPlayingControlsVisible;
- (BOOL)isScrolling;
- (BOOL)handleMenuButtonTap;
- (void)_iconModelVisibilityChanged:(id)fp8;
- (void)_iconModelChangedSignificantly;
- (void)setupForApp:(id)fp8 orientation:(int)fp12;
- (void)_reloadIconViewsAndShowFirstPage:(BOOL)fp8;
- (void)downloadChanged:(id)fp8;
- (void)downloadRemoved:(id)fp8;
- (void)viewDidRotateFromInterfaceOrientation:(int)fp8;
- (void)viewWillAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)viewWillRotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (float)bottomBarHeight;
- (id)view;
- (void)_newsstandFolderWasOpened:(id)fp8;
- (void)_appsDidChange:(id)fp8;
- (void)dealloc;
- (id)init;

@end

