/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBAppContextHostManager;

@interface SBAppContextHostView : _ABAddressBookCopyLocalizedLabel
{
    SBAppContextHostManager *_manager;
}

- (void)setManager:(id)fp8;
- (id)manager;
- (id)window;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)description;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithDefaultSize;

@end

