/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSSet;

@interface SBApplicationDataLookupOperation : _ABAddressBookCopyLocalizedLabel
{
    NSSet *_registeredBundleIDs;
    NSSet *_unregisteredBundleIDs;
}

- (void)main;
- (void)dealloc;
- (id)initWithRegisteredBundleIDs:(id)fp8 unregisteredBundleIDs:(id)fp12;

@end

