/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BKSApplicationStateMonitor, NSDictionary, NSLock, NSMutableDictionary, NSMutableSet, NSOperationQueue, SBApplication, SBDataLookupResults;

@interface SBApplicationController : _ABAddressBookCopyLocalizedLabel
{
    SBDataLookupResults *_pendingDataLookupResults;
    NSLock *_pendingDataLookupResultsLock;
    NSMutableDictionary *_applications;
    NSMutableDictionary *_applicationsByBundleIdentifer;
    NSMutableSet *_applicationsPlayingMutedAudioSinceLastLock;
    SBApplication *_applicationCurrentlyRecordingAudio;
    int _locationStatusBarIconType;
    NSDictionary *_backgroundDisplayDict;
    unsigned int _ignoreUninstallationEventCount;
    NSOperationQueue *_backgroundOperationQueue;
    NSLock *_applicationsLock;
    NSMutableDictionary *_systemAppsVisibilityOverrides;
    BOOL _visibilityOverridesAreDirty;
    BKSApplicationStateMonitor *_appStateMonitor;
    BOOL _booting;
    NSMutableSet *_appsToAutoLaunchAfterBoot;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (BOOL)updateAppIconVisibilityOverridesShowing:(id *)fp8 hiding:(id *)fp12;
- (void)_setVisibilityOverridesAreDirty:(BOOL)fp8;
- (int)appVisibilityOverrideForBundleIdentifier:(id)fp8;
- (void)_reloadBackgroundIDsDict;
- (void)processPendingInstalls;
- (void)_handleDataLookupResultsIfReceived;
- (void)_applicationRegistrationChangedCallback:(id)fp8 info:(id)fp12;
- (void)_applicationsUnregistered:(id)fp8;
- (void)_applicationsRegistered:(id)fp8;
- (void)_applicationsRegistered:(id)fp8 unregistered:(id)fp12;
- (BOOL)_hasRequiredCapabilities:(id)fp8;
- (void)loadApplicationsWithBundle:(id)fp8 bundlePath:(id)fp12 isSystemApplication:(BOOL)fp16 defaultTags:(id)fp20 signerIdentity:(id)fp24 provisioningProfileValidated:(BOOL)fp28 seatbeltEnvironmentVariables:(id)fp32;
- (Class)applicationClassForInfoDictionary:(id)fp8;
- (void)loadWebclipAndIcon:(id)fp8;
- (void)loadApplicationsAndIcons:(id)fp8 reveal:(BOOL)fp12 popIn:(BOOL)fp16;
- (void)_loadApplicationsAndIcons:(id)fp8 removed:(id)fp12 applicationDictionaries:(id)fp16 reveal:(BOOL)fp20 popIn:(BOOL)fp24 reloadAllIcons:(BOOL)fp28;
- (void)_updateIconControllerAndModelForLoadedApplications:(id)fp8 reveal:(BOOL)fp12 popIn:(BOOL)fp16 reloadAllIcons:(BOOL)fp20;
- (void)waitForOperationsToComplete;
- (void)_decrementUninstallationEventCount;
- (void)uninstallApplication:(id)fp8;
- (void)removeApplicationsFromModelWithBundleIdentifier:(id)fp8;
- (BOOL)loadApplication:(id)fp8;
- (id)loadApplications;
- (id)_loadApplications:(BOOL)fp8 applicationDictionaries:(id)fp12;
- (id)_loadApplications:(id)fp8 removed:(id)fp12 applicationDictionaries:(id)fp16 updateRestrictions:(BOOL)fp20;
- (void)_calculateApplicationDiff:(id *)fp8 removed:(id *)fp12 applicationDictionaries:(id)fp16;
- (id)_modifiedApplications:(id)fp8 applicationDictionaries:(id)fp12;
- (BOOL)_applicationHasBeenModified:(id)fp8 applicationDictionary:(id)fp12;
- (void)_loadApplication:(id)fp8 dictionary:(id)fp12 allowDemoOnly:(BOOL)fp16;
- (void)_loadApplication:(id)fp8 dictionary:(id)fp12;
- (void)_postLoadApplications:(id)fp8 removed:(id)fp12 modified:(id)fp16 updateRestrictions:(BOOL)fp20;
- (void)_sendInstalledAppsDidChangeNotification:(id)fp8 removed:(id)fp12 modified:(id)fp16;
- (void)_preLoadApplications;
- (id)newsstandApps;
- (id)webApplications;
- (id)mobilePhone;
- (id)setupApplication;
- (id)dataActivation;
- (id)applicationCurrentlyRecordingAudio;
- (id)iPod;
- (id)applicationWithPid:(int)fp8;
- (id)applicationWithDisplayIdentifier:(id)fp8;
- (id)applicationsWithPid:(int)fp8;
- (id)applicationsWithBundleIdentifier:(id)fp8;
- (id)allApplications;
- (id)allDisplayIdentifiers;
- (void)autoLaunchAppsIfNecessaryAfterBoot;
- (int)locationStatusBarIconType;
- (void)buildLocationState;
- (void)_updateLocationState;
- (void)_memoryWarningReceived;
- (void)_lockStateChanged:(id)fp8;
- (void)_unusuallyMutedAudioPlaying:(id)fp8;
- (void)_recordingStateChanged:(id)fp8;
- (void)_mediaServerConnectionDied:(id)fp8;
- (void)_registerForAVSystemControllerNotifications;
- (void)_unregisterForAVSystemControllerNotifications;
- (void)queuePendingDataLookupResults:(id)fp8;
- (id)dequeuePendingDataLookupResults;
- (BOOL)hasPendingDataLookupResults;
- (void)dealloc;
- (id)init;

@end

