/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@class NSString;

@interface SBApplicationIcon : SBLeafIcon
{
    NSString *_displayIdentifier;
    unsigned int _appIsBeingCleaned:1;
}

- (id)applicationBundleID;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (void)setBadge:(id)fp8;
- (void)launchFromViewSwitcher;
- (void)launch;
- (void)_terminationAssertionDidChange;
- (void)_setAppIsBeingCleanedFlag;
- (BOOL)launchEnabled;
- (id)automationID;
- (id)tags;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (id)generateIconImage:(int)fp8;
- (BOOL)canGenerateImageInBackgroundForFormat:(int)fp8;
- (void)generateIconImageInBackground:(id)fp(null);
- (id)blockForGeneratingIconImageInBackgroundWithFormat:(SEL)fp4;
- (id)_blockForGeneratingIconImageInBackgroundWithFormat:(SEL)fp4 complete:(int)fp8;
- (id)__loadIconImage:(id)fp8 format:(int)fp12 scale:(float)fp16;
- (void)completeUninstall;
- (id)application;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithApplication:(id)fp8;

@end

