/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBAppSwitcherUILabel : _ABAddressBookCopyLocalizedLabel
{
}

- (void)_drawFullMarqueeTextInRect:(struct CGRect)fp8;
- (struct CGRect)textRectForBounds:(struct CGRect)fp8 limitedToNumberOfLines:(int)fp24;

@end

