/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBAppSwitcherBarViewDelegate <NSObject>
- (void)appSwitcherBar:(id)fp8 pageAtIndexDidDisappear:(int)fp12;
- (void)appSwitcherBar:(id)fp8 pageAtIndexDidAppear:(int)fp12;
- (BOOL)appSwitcherBar:(id)fp8 scrollShouldCancelInContentForView:(id)fp12;
- (void)appSwitcherBarRemovedFromSuperview:(id)fp8;
@end

