/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, NSMutableDictionary, NSString, SBAppContextHostView, SBOrderedRequesters;

@interface SBAppContextHostManager : _ABAddressBookCopyLocalizedLabel
{
    SBAppContextHostView *_contextHostView;
    NSString *_appBundleID;
    NSMutableArray *_contexts;
    BOOL _hostingEnabled;
    BOOL _suspended;
    SBOrderedRequesters *_hostRequesters;
    NSMutableDictionary *_hostRequesterInfo;
}

- (BOOL)isHostingEnabled;
- (void)setAppBundleID:(id)fp8;
- (id)appBundleID;
- (void)_adjustLayerFrameAndTransform:(id)fp8;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8 excludeContext:(unsigned int)fp24 outTransform:(struct CGAffineTransform *)fp28;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8 outTransform:(struct CGAffineTransform *)fp24;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8;
- (void)setOrderOutPending:(BOOL)fp8 forContextId:(unsigned int)fp12;
- (void)didOrderOutContextWithId:(unsigned int)fp8;
- (void)willOrderInContextWithId:(unsigned int)fp8 windowLevel:(float)fp12 windowOutput:(int)fp16 flush:(BOOL)fp20;
- (unsigned int)contextCount;
- (void)_setContext:(id)fp8 hidden:(BOOL)fp12;
- (void)_removeRequesterInfo:(id)fp8;
- (void)_applyRequesterInfo:(id)fp8;
- (id)_infoForRequester:(id)fp8;
- (void)_notePropertiesSetOnRealContextHostViewWhichIReallyNeedToChangeAndIKnowWhatImDoingISwear:(id)fp8 originalProperties:(id)fp12 forRequester:(id)fp16;
- (id)_realContextHostViewWhichIReallyNeedToAccessAndIKnowWhatImDoingISwear;
- (void)setContextId:(unsigned int)fp8 hidden:(BOOL)fp12 forRequester:(id)fp16;
- (void)orderRequesterFront:(id)fp8;
- (void)disableHostingForAllRequesters;
- (void)disableHostingForRequester:(id)fp8;
- (void)resumeContextHosting;
- (void)suspendContextHosting;
- (BOOL)_clearContextHosts;
- (BOOL)_startContextHosting;
- (void)enableHostingForRequester:(id)fp8 priority:(int)fp12;
- (id)hostViewForRequester:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)init;

@end

