/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIFullscreenAnimationView.h"

@class CALayer, CATransformLayer, SBApplication, UIView;

@interface SBAppToAppTransitionView : SBUIFullscreenAnimationView
{
    SBApplication *_toApplication;
    CATransformLayer *_transformLayer;
    CALayer *_startLayer;
    CALayer *_stopLayer;
    UIView *_fromView;
    UIView *_toView;
    int _orientation;
}

- (void)setOrientation:(int)fp8;
- (int)orientation;
- (void)setToApp:(id)fp8;
- (id)toApp;
- (float)_rotationRadians;
- (id)_rotationValueFunction;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)endTransition;
- (void)beginTransition;
- (void)setToView:(id)fp8;
- (void)setFromView:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

