/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIAlertViewDelegate-Protocol.h"

@class SBApplicationIcon;

@interface SBAppProfileExpiredAlertItem : _ABAddressBookCopyLocalizedLabel <UIAlertViewDelegate>
{
    SBApplicationIcon *_icon;
}

- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)dealloc;
- (id)initWithIcon:(id)fp8;

@end

