/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class BKSApplicationActivationAssertion, SBApplication, SBUIAnimationController;

@interface SBAppToAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerDelegate>
{
    SBApplication *_fromApp;
    SBUIAnimationController *_animationController;
    BKSApplicationActivationAssertion *_suspendingAppAssertion;
    BOOL _deactivateAlertsAfterLaunch;
    BOOL _shouldLaunchPNGLess;
    BOOL _animatedActivation;
    BOOL _animatedDeactivation;
    BOOL _deactivatingAppFromAppToAppGesture;
}

- (void)setFromApp:(id)fp8;
- (id)fromApp;
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 didCommitAnimation:(BOOL)fp12 withDuration:(double)fp16 afterDelay:(double)fp24;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (id)_setupAnimationFrom:(id)fp8 to:(id)fp12;
- (void)_transactionComplete;
- (void)_interruptWithReason:(int)fp8;
- (BOOL)_canBeInterrupted;
- (void)_endAnimation;
- (BOOL)selfAlertDidDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (BOOL)selfApplicationActivated:(id)fp8;
- (BOOL)selfApplicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (void)_handleAppDidNotChange;
- (BOOL)selfApplicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (void)_kickOffActivation;
- (void)_commit;
- (void)_beginAnimation;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (BOOL)shouldAnimateOrientationChangeOnCompletion;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 exitedApp:(id)fp16;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 from:(id)fp16 to:(id)fp20;

@end

