/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

#import "SBUIFullscreenAnimationViewDelegate-Protocol.h"

@class SBAppToAppTransitionView;

@interface SBAppToAppTransitionController : SBUIAnimationController <SBUIFullscreenAnimationViewDelegate>
{
    SBAppToAppTransitionView *_transitionView;
    BOOL _requiresHostView;
    BOOL _dismissBanner;
}

+ (id)_transitionWindow;
- (void)setTransitionView:(id)fp8;
- (id)transitionView;
- (void)appTransitionViewAnimationDidStop:(id)fp8;
- (void)appTransitionView:(id)fp8 animationWillStartWithDuration:(double)fp12 afterDelay:(double)fp20;
- (void)_cleanupAnimation;
- (void)_cancelAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)fp8;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;

@end

