/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UILabel;

@interface SBAppSwitcherLabel : _ABAddressBookCopyLocalizedLabel
{
    UILabel *_label;
}

- (void)setMarqueeRunning:(BOOL)fp8;
- (BOOL)marqueeRunning;
- (void)setText:(id)fp8;
- (id)text;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

