/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class BKSApplicationActivationAssertion, SBAlert, SBApplication, SBUIAnimationController;

@interface SBAppToAlertWorkspaceTransaction : SBWorkspaceTransaction <SBUIAnimationControllerDelegate>
{
    SBApplication *_topApplication;
    BKSApplicationActivationAssertion *_topApplicationActivationAssertion;
    BOOL _topApplicationSuppressesSpringBoardStatusBar;
    SBAlert *_activatingAlert;
    SBUIAnimationController *_animation;
    id _alertActivationBlock;
    BOOL _animatedAppDeactivation;
}

- (void)setAlertActivationBlock:(id)fp(null);
- (id)alertActivationBlock;
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 didCommitAnimation:(BOOL)fp12 withDuration:(double)fp16 afterDelay:(double)fp24;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (void)_transactionComplete;
- (BOOL)selfAlertDidActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfAlertWillActivate:(id)fp8 overAlerts:(id)fp12;
- (void)_commit;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 alert:(id)fp16 overTopApplication:(id)fp20;

@end

