/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBNewsstandItemIconViewBase.h"

@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconViewBase
{
}

+ (Class)_labelImageParametersClassForIcon:(id)fp8 location:(int)fp12;
- (id)_superviewForAccessoryView;
- (void)positionIconImageView;
- (void)positionCloseBoxOfType:(int)fp8;
- (void)_updateLabelVisibility;
- (void)setShadowsHidden:(BOOL)fp8;
- (struct CGRect)defaultFrameForProgressBar;
- (id)initWithFrame:(struct CGRect)fp8;

@end

