/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBAppSwitcherVolumeSlider : _ABAddressBookCopyLocalizedLabel
{
}

- (void)setSliderEnabled:(BOOL)fp8 withDuration:(double)fp12;
- (struct UIEdgeInsets)_thumbHitEdgeInsets;
- (struct CGRect)thumbRectForBounds:(struct CGRect)fp8 trackRect:(struct CGRect)fp24 value:(float)fp40;
- (struct CGRect)trackRectForBounds:(struct CGRect)fp8;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)initWithFrame:(struct CGRect)fp8;

@end

