/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface SBApplicationPersistence : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_state;
    BOOL _dirty;
    NSObject<OS_dispatch_queue> *_stateQueue;
    NSObject<OS_dispatch_queue> *_writeQueue;
}

+ (void)migrateSystemLocalNotifications;
+ (id)_statePath;
+ (id)sharedInstance;
- (void)_markDirty;
- (void)_flushSynchronously;
- (void)flushSynchronously;
- (void)purgeKeysForBundleAndDisplayIdentifiersOtherThan:(id)fp8;
- (id)allBundleOrDisplayIdentifiersWithState;
- (void)setArchivedObject:(id)fp8 forKey:(id)fp12 bundleOrDisplayIdentifier:(id)fp16;
- (id)archivedObjectForKey:(id)fp8 bundleOrDisplayIdentifier:(id)fp12 ofType:(Class)fp16;
- (void)setValue:(id)fp8 forKey:(id)fp12 bundleOrDisplayIdentifier:(id)fp16;
- (id)valueForKey:(id)fp8 bundleOrDisplayIdentifier:(id)fp12 ofType:(Class)fp16;
- (id)init;

@end

