/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBAutoPurgingImageView : _ABAddressBookCopyLocalizedLabel
{
    id _block;
}

- (void)setImage:(id)fp8;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithImageNamed:(id)fp8;
- (id)_initWithImageBlock:(id)fp(null) andInitialLoadBlock:(void)fp8;

@end

