/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBAwayBulletinTableView : _ABAddressBookCopyLocalizedLabel
{
}

- (BOOL)touchesShouldBegin:(id)fp8 withEvent:(id)fp12 inContentView:(id)fp16;

@end

