/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBAwayBulletinListViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BBObserver, NSMutableArray, SBAwayBulletinCell, SBAwayBulletinListView, SBAwayListActionContext;

@interface SBAwayBulletinListController : _ABAddressBookCopyLocalizedLabel <BBObserverDelegate, UITableViewDataSource, UITableViewDelegate, SBAwayBulletinListViewDelegate>
{
    BBObserver *_observer;
    NSMutableArray *_listItems;
    NSMutableArray *_realertTimers;
    SBAwayBulletinCell *_unlockingCell;
    BOOL _lockBarIsTracking;
    NSMutableArray *_trackingCells;
    SBAwayBulletinListView *_view;
    struct CGRect _viewRect;
    float _contentHeight;
    BOOL _dimmed;
    BOOL _presentingNewBulletin;
    BOOL _dimmingForLockButtonPress;
    BOOL _hibernating;
    BOOL _quietModeEnabled;
    BOOL _autoHidesNotifications;
    BOOL _autoHideTimerActive;
    BOOL _hasManuallyShownNotifications;
    struct CGAffineTransform _pinnedViewTransform;
    SBAwayListActionContext *_actionContext;
    NSMutableArray *_pendingSystemAlerts;
    id _itemToBlink;
    id _itemToFloat;
}

- (BOOL)quietModeEnabled;
- (BOOL)autoHidesNotifications;
- (BOOL)presentingNewBulletin;
- (id)listItems;
- (BOOL)lockBarIsTracking;
- (struct CGRect)viewRect;
- (BOOL)dimmed;
- (id)view;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (float)_rowHeightForItem:(id)fp8 floating:(BOOL)fp12;
- (void)_configureAndPositionView;
- (void)setPinnedViewTransform:(struct CGAffineTransform)fp8;
- (void)setViewHiddenForUnlock:(BOOL)fp8 force:(BOOL)fp12;
- (void)setViewHiddenForUnlock:(BOOL)fp8;
- (double)animationDurationForShowPasscodeUI:(BOOL)fp8 duration:(double)fp12;
- (double)animationDelayForShowPasscodeUI:(BOOL)fp8 duration:(double)fp12;
- (void)setViewRect:(struct CGRect)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)_setContentForTableCell:(id)fp8 withItem:(id)fp12 floating:(BOOL)fp16;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)pendOrDeactivateAlertItems:(BOOL)fp8;
- (void)deactivateAlertItem:(id)fp8;
- (void)activateAlertItem:(id)fp8 didUndimScreen:(BOOL)fp12;
- (void)updateCardItem:(id)fp8;
- (void)deactivateCardItem:(id)fp8;
- (void)activateCardItem:(id)fp8 animated:(BOOL)fp12;
- (void)activateOrUpdateCardItem:(id)fp8 animated:(BOOL)fp12;
- (void)observer:(id)fp8 noteAlertBehaviorOverridesChanged:(unsigned int)fp12;
- (id)observer:(id)fp8 composedAttachmentImageForType:(int)fp12 thumbnailData:(id)fp16 key:(id)fp20;
- (id)observer:(id)fp8 multipleThumbnailSizeConstraintsForAttachmentType:(int)fp12;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)fp8;
- (void)observer:(id)fp8 removeBulletin:(id)fp12;
- (void)observer:(id)fp8 modifyBulletin:(id)fp12;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (id)_floatingItemToUseForNewItem:(id)fp8;
- (void)_updateModelAndTableViewForRemoval:(id)fp8 originalHeight:(float)fp12;
- (void)_updateModelAndTableViewForModification:(id)fp8 originalHeight:(float)fp12;
- (void)_updateModelAndTableViewForAddition:(id)fp8;
- (void)_updateModelAndTableViewForAddition:(id)fp8 animated:(BOOL)fp12;
- (int)_rowAnimationForDelete;
- (int)_rowAnimationForInsert;
- (void)_hardwareButtonPressed:(id)fp8;
- (void)_scheduleRealerts:(id)fp8;
- (void)_killRealerts:(id)fp8;
- (void)_realertTimerFired:(id)fp8;
- (void)_alertForBulletin:(id)fp8;
- (BOOL)_shouldTreatBulletinAsInert:(id)fp8;
- (void)_forceTopBarShadowVisibilityUpdate;
- (BOOL)wantsToHideTopBarShadow;
- (void)resetLockBarIfUnlocking;
- (void)resetLockBarsIfTracking;
- (void)lockBarStoppedTrackingForCell:(id)fp8;
- (void)lockBarStartedTrackingForCell:(id)fp8;
- (BOOL)setUnlockingTableViewCell:(id)fp8;
- (void)setDimmed:(BOOL)fp8;
- (void)_awayControllerRelocked:(id)fp8;
- (BOOL)usesFloatingPanelAndBlinkingItems;
- (void)_autoDismissTimerElapsed;
- (void)_startOrEndAutoDismissTimerIfNecessary;
- (void)_cancelAutoDismissTimer;
- (void)sliderGrabDidEnd;
- (void)sliderGrabWillEnd:(BOOL)fp8;
- (void)willSetViewStyle:(int)fp8;
- (BOOL)hasShownNotificationsManually;
- (BOOL)shouldAutoHideNotifications;
- (void)setTableItemToFloat:(id)fp8;
- (void)setTableItemToFloat:(id)fp8 force:(BOOL)fp12;
- (void)_animateResetConfigurationAndPositioning:(BOOL)fp8 clearingUnlockContext:(BOOL)fp12 clearsFloatingItem:(BOOL)fp16;
- (void)_animateResetConfigurationAndPositioning:(BOOL)fp8 clearingUnlockContext:(BOOL)fp12;
- (void)_animateResetConfigurationAndPositioning:(BOOL)fp8;
- (void)setTableItemToBlink:(id)fp8;
- (id)unlockActionContext;
- (id)visibleActionContext;
- (void)_sortListItems;
- (id)_systemAlertItem;
- (id)_listItemContainingCardItem:(id)fp8;
- (id)_listItemContainingBulletinID:(id)fp8;
- (id)_listItemForNewBulletin:(id)fp8;
- (void)showTestBulletin;
- (void)setUnlockActionContext:(id)fp8;
- (void)_autoHideNotificationsChanged;
- (void)setAutoHidesNotifications:(BOOL)fp8;
- (BOOL)isHibernating;
- (void)rebuildViewsAndStopHibernating;
- (int)defaultStyle;
- (void)clearViewsAndHibernate;
- (void)_configureBBObserver;
- (void)dealloc;
- (id)init;

@end

