/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary, UIButton, UIView;

@interface SBAwayLockBar : _ABAddressBookCopyLocalizedLabel
{
    UIButton *_slideshowButton;
    UIView *_cameraGrabber;
    NSMutableDictionary *_orientationToButtonImages;
}

- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)_slideshowButtonActivated:(id)fp8;
- (void)_setShowsButton:(BOOL)fp8 button:(id *)fp12 buttonTag:(int)fp16 hasComposedImage:(BOOL)fp20 action:(SEL)fp24 animated:(BOOL)fp28;
- (void)_setImagesForButton:(id)fp8 orientation:(int)fp12;
- (id)_selectedImageForButtonTag:(int)fp8 interfaceOrientation:(int)fp12;
- (id)_unselectedImageForButtonTag:(int)fp8 interfaceOrientation:(int)fp12;
- (id)_newButtonWithAction:(SEL)fp8 tag:(int)fp12 hasComposedImage:(BOOL)fp16;
- (void)setOrientation:(int)fp8;
- (BOOL)showsCameraGrabber;
- (void)setShowsCameraGrabber:(BOOL)fp8;
- (void)setSlideshowButtonSelected:(BOOL)fp8;
- (void)setShowsSlideshowButton:(BOOL)fp8;
- (BOOL)_shouldStopLabelAnimationForGrab;
- (void)setLabel:(id)fp8;
- (void)dealloc;

@end

