/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAwayListCellButtonHandler-Protocol.h"

@class NSArray, NSString, SBAlertItem, UIImage;

@interface SBAwaySystemAlertItem : _ABAddressBookCopyLocalizedLabel <SBAwayListCellButtonHandler>
{
    SBAlertItem *_currentAlert;
    NSString *_title;
    NSArray *_buttonLabels;
    UIImage *_appImage;
    NSString *_message;
    int _cancelButtonIdx;
    BOOL _isAlarm;
}

- (BOOL)isAlarm;
- (int)cancelButtonIndex;
- (void)buttonPressedAtIndex:(int)fp8;
- (id)buttonLabels;
- (id)sortDate;
- (id)iconImage;
- (id)title;
- (id)message;
- (void)setCurrentAlert:(id)fp8;
- (id)currentAlert;
- (void)dealloc;
- (id)initWithSystemAlert:(id)fp8;

@end

