/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBAwayListActionContext : _ABAddressBookCopyLocalizedLabel
{
    NSString *_lockLabel;
    NSString *_shortLockLabel;
    id _unlockAction;
    NSString *_bulletinID;
    float _fontsize;
    BOOL _requiresUnlock;
    BOOL _deactivateAwayController;
    BOOL _launchActionCanBypassPinLock;
    BOOL _hasCustomUnlockLabel;
    BOOL _canBypassPinLock;
}

+ (id)actionContextForCardItem:(id)fp8;
+ (id)actionContextForAlertItem:(id)fp8;
+ (id)actionContextForBulletin:(id)fp8 pluginActionsAllowed:(BOOL)fp12;
- (void)setHasCustomUnlockLabel:(BOOL)fp8;
- (BOOL)hasCustomUnlockLabel;
- (void)setRequiresUnlock:(BOOL)fp8;
- (BOOL)requiresUnlock;
- (void)setDeactivateAwayController:(BOOL)fp8;
- (BOOL)deactivateAwayController;
- (void)setCanBypassPinLock:(BOOL)fp8;
- (BOOL)canBypassPinLock;
- (float)lockLabelFontSize;
- (id)bulletinID;
- (id)shortLockLabel;
- (id)lockLabel;
- (id)unlockAction;
- (void)dealloc;
- (id)_initWithLockLabel:(id)fp8 shortLockLabel:(id)fp12 unlockAction:(id)fp(null) bulletinID:(void)fp16 fontSize:(id)fp20;
- (id)_initWithLockLabel:(id)fp8 shortLockLabel:(id)fp12 unlockAction:(id)fp(null) bulletinID:(void)fp16;

@end

