/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBulletinCellContentViewBase.h"

@interface SBAwayBulletinFloatingContentView : SBBulletinCellContentViewBase
{
    BOOL _hasButton;
}

+ (float)heightForSystemAlertStyleWithTitle:(id)fp8 maxLines:(unsigned int)fp12 message:(id)fp16 maxLines:(unsigned int)fp20 buttonHeight:(float)fp24 contentWidth:(float)fp28;
+ (float)heightForBulletinStyleWithSubtitle:(id)fp8 message:(id)fp12 maxLines:(unsigned int)fp16 attachmentText:(id)fp20 imageHeight:(float)fp24 contentWidth:(float)fp28;
+ (float)heightForBulletinStyleWithSubtitle:(id)fp8 message:(id)fp12 maxLines:(unsigned int)fp16 contentWidth:(float)fp20;
- (void)setHasButton:(BOOL)fp8;
- (BOOL)hasButton;
- (void)_configureLabel:(id)fp8 withFont:(id)fp12 color:(id)fp16 alignment:(int)fp20;
- (void)layoutSubviews;
- (void)setAttachmentText:(id)fp8;
- (void)setStartDate:(id)fp8 endDate:(id)fp12 timeZone:(id)fp16 allDay:(BOOL)fp20 formatStyle:(int)fp24;
- (void)setMessage:(id)fp8;
- (void)setSubtitle:(id)fp8;
- (void)setTitle:(id)fp8;
- (id)_vipAccessoryImage;
- (id)_dateFont;
- (id)_attachmentFont;
- (id)_messageFont;
- (id)_subtitleFont;
- (id)_titleFont;

@end

