/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAwaySystemAlertCell.h"

@interface SBAwaySystemAlertFloatingCell : SBAwaySystemAlertCell
{
}

+ (float)_cellContentExtraPadding;
+ (float)_cellContentTopPadding;
+ (float)_cellContentRightPadding;
+ (float)_cellContentLeftPadding;
+ (float)_buttonVerticalInset;
+ (float)_buttonHorizontalInset;
+ (id)_buttonFont;
+ (id)_cancelButtonBackgroundImage;
+ (id)_buttonBackgroundImage;
+ (id)_alarmButtonBackgroundImage;
+ (float)rowHeightForTitle:(id)fp8 message:(id)fp12 rowWidth:(float)fp16 buttonLabels:(id)fp20;
+ (float)_rowHeightForContentHeight:(float)fp8;
- (void)layoutSubviews;
- (void)_clearButtonHandler;
- (void)_getButtonWidth:(float *)fp8 inset:(float *)fp12;
- (struct CGRect)_cellContentViewFrame;
- (struct CGRect)_contentRect;
- (BOOL)_drawsSeparator;
- (void)setButtonLabels:(id)fp8 handler:(id)fp12 isAlarm:(BOOL)fp16;
- (void)setIconImage:(id)fp8;
- (BOOL)_hasBackgroundColor;
- (void)_createContentView;

@end

