/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, NSTimer, SBAwayMediaControlsView, TPLCDTextView, UILabel;

@interface SBAwayDateView : _ABAddressBookCopyLocalizedLabel
{
    NSTimer *_dateTimer;
    TPLCDTextView *_timeLabel;
    TPLCDTextView *_dateAndTetheringLabel;
    NSString *_title;
    NSString *_artist;
    NSString *_album;
    UILabel *_nowPlayingTitleLabel;
    UILabel *_nowPlayingArtistLabel;
    UILabel *_nowPlayingAlbumLabel;
    SBAwayMediaControlsView *_controlsView;
    id <SBAwayDateViewDelegate> _delegate;
    int _orientation;
    unsigned int _isPlaying:1;
}

- (int)orientation;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)isPlaying;
- (void)setPlaying:(BOOL)fp8;
- (BOOL)isMediaControlsShowingOverlays;
- (BOOL)isShowingControls;
- (void)dismissMediaControlsOverlaysAnimated:(BOOL)fp8;
- (void)setIsShowingControls:(BOOL)fp8;
- (void)_tearDownMediaControlsView;
- (id)controlsView;
- (void)didMoveToSuperview;
- (void)setVisible:(BOOL)fp8;
- (void)removeFromSuperview;
- (void)setAlbum:(id)fp8;
- (void)setArtist:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (void)updateClock;
- (void)updateClockFormat;
- (void)_createFormattersIfNecessary;
- (void)update;
- (void)resizeAndPositionNowPlayingLabels;
- (id)newNowPlayingLabelWithFont:(id)fp8 color:(id)fp12;
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12;
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12 fontName:(const char *)fp20;
- (void)setOrientation:(int)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

