/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBAwayBulletinListController, SBBulletinCellContentViewBase, UIImageView;

@interface SBAwayListItemCell : _ABAddressBookCopyLocalizedLabel
{
    UIImageView *_separatorTopHalf;
    UIImageView *_separatorBottomHalf;
    UIImageView *_iconImageView;
    SBBulletinCellContentViewBase *_cellContentView;
    SBAwayBulletinListController *_controller;
    BOOL _shouldBlinkIcon;
}

+ (float)_cellContentExtraPadding;
+ (float)_cellContentTopPadding;
+ (float)_cellContentRightPadding;
+ (float)_cellContentLeftPadding;
+ (float)_cellIconLeftPadding;
+ (float)_contentWidthForRowWidth:(float)fp8;
+ (float)_rowHeightForContentHeight:(float)fp8;
- (BOOL)shouldBlinkIcon;
- (void)setController:(id)fp8;
- (struct CGRect)_cellContentViewFrame;
- (struct CGRect)_contentRect;
- (BOOL)_drawsSeparator;
- (void)layoutSubviews;
- (void)setMessage:(id)fp8;
- (void)setTitle:(id)fp8;
- (void)setShouldBlinkIcon:(BOOL)fp8;
- (void)setIconImage:(id)fp8;
- (void)dealloc;
- (void)setBackgroundColor:(id)fp8;
- (id)initWithReuseIdentifier:(id)fp8;
- (void)_createContentView;
- (void)_removeIconBlinkAnimation;
- (void)_addIconBlinkAnimation;
- (BOOL)_hasBackgroundColor;

@end

