/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAwayListItemCell.h"

@class SBAwayListActionContext, SBBulletinLockBar;

@interface SBAwayBulletinCell : SBAwayListItemCell
{
    SBBulletinLockBar *_lockBar;
    SBAwayListActionContext *_actionContext;
    BOOL _disableUnlockSound;
}

+ (float)rowHeightForSubtitle:(id)fp8 imageHeight:(float)fp12;
+ (float)rowHeightForSubtitle:(id)fp8 message:(id)fp12 maxLines:(unsigned int)fp16 rowWidth:(float)fp20;
- (id)actionContext;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)_lockBarSlidBackToOrigin:(id)fp8 withDuration:(double)fp12;
- (void)lockBarSlidBackToOrigin:(id)fp8;
- (void)lockBarStoppedTracking:(id)fp8;
- (void)lockBarStartedTracking:(id)fp8;
- (void)lockBarUnlocked:(id)fp8;
- (void)resetLockBar;
- (void)setDisableUnlockSound:(BOOL)fp8;
- (void)setUnlockActionContext:(id)fp8;
- (void)_createLockBar;
- (BOOL)_createsLockBarEarly;
- (void)layoutSubviews;
- (void)setVIP:(BOOL)fp8;
- (void)setAttachmentText:(id)fp8;
- (void)setAttachmentImage:(id)fp8;
- (void)setStartDate:(id)fp8 endDate:(id)fp12 timeZone:(id)fp16 allDay:(BOOL)fp20 formatStyle:(int)fp24;
- (void)setSubtitle:(id)fp8;
- (void)setMaxMessageLines:(unsigned int)fp8;
- (void)dealloc;
- (void)_createContentView;

@end

