/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class UIImageView, UITableView, UIView;

@interface SBAwayBulletinListView : _ABAddressBookCopyLocalizedLabel <UIGestureRecognizerDelegate>
{
    UITableView *_tableView;
    UIView *_tableContainerView;
    UIView *_tableBackgroundView;
    UIView *_tableTopFadeOverlay;
    UIView *_tableBottomFadeOverlay;
    UIView *_tableFadeMaskContainer;
    UIImageView *_grabberFadeMaskImageView;
    UIView *_tableHeaderView;
    UIView *_tableFooterView;
    UIView *_dropShadowView;
    UITableView *_firstAlertTableView;
    UIView *_firstAlertBGView;
    float _firstAlertTableHeight;
    UIView *_tableGrabberView;
    int _normalViewStyle;
    float _normalTableHeight;
    id <SBAwayBulletinListViewDelegate> _delegate;
    int _viewStyle;
    BOOL _hiddenForUnlock;
    BOOL _shouldShowFirstAlertTable;
    BOOL _animatingGrabEnded;
    BOOL _grabberGrabbed;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)firstAlertTableView;
- (int)viewStyle;
- (id)tableView;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (struct CGRect)_grabberHitFrame;
- (void)_grabEndedWithVelocity:(struct CGPoint)fp8 cancelled:(BOOL)fp16;
- (void)_grabEndedWithVelocity:(struct CGPoint)fp8 cancelled:(BOOL)fp16 animated:(BOOL)fp20;
- (void)_updateForGrabBeganOrMovedWithLocation:(struct CGPoint)fp8 velocity:(struct CGPoint)fp16;
- (void)handleGrabberPan:(id)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (id)_tableFooterView;
- (id)_tableHeaderView;
- (void)clearFloatingAlertButtonHandler;
- (BOOL)floatingAlertNeedsMainUnlockAction;
- (void)setFirstAlertTableHeight:(float)fp8;
- (void)setFirstAlertTableViewHidden:(BOOL)fp8;
- (void)layoutSubviews;
- (void)lockBarStoppedTracking;
- (void)lockBarStartedTracking;
- (float)floatingTableContainerHeightForContentHeight:(float)fp8;
- (void)setHiddenForUnlock:(BOOL)fp8 force:(BOOL)fp12;
- (BOOL)wantsToHideTopBarShadowView;
- (BOOL)isHiddenForUnlock;
- (BOOL)shouldHideBySlidingOut;
- (void)_slideOutTransforms:(struct CGAffineTransform *)fp8 grabberTransform:(struct CGAffineTransform *)fp12;
- (BOOL)hasShownNotificationsManually;
- (BOOL)shouldAutoHideNotifications;
- (void)setViewStyle:(int)fp8 withFloatingAlert:(BOOL)fp12 andTableHeight:(float)fp16 force:(BOOL)fp20;
- (void)setViewStyle:(int)fp8 withFloatingAlert:(BOOL)fp12 andTableHeight:(float)fp16;
- (BOOL)shouldOverrideToSlideUpStyle:(BOOL)fp8;
- (float)_tableContainerViewAlphaForSlideUp;
- (float)_translationDistanceForGrabber;
- (struct CGSize)_maxPinnedContainerSize;
- (void)setFrame:(struct CGRect)fp8;
- (void)_setupHierarchyIfNecessaryWithStyle:(int)fp8;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 style:(int)fp12;

@end

