/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAwayBulletinCell.h"

@interface SBAwayBulletinFloatingCell : SBAwayBulletinCell
{
    BOOL _hideIcon;
}

+ (float)_cellContentExtraPadding;
+ (float)_cellContentTopPadding;
+ (float)_cellContentRightPadding;
+ (float)_cellContentLeftPadding;
+ (float)_cellIconLeftPadding;
+ (float)rowHeightForSubtitle:(id)fp8 message:(id)fp12 maxLines:(unsigned int)fp16 attachmentText:(id)fp20 imageSize:(struct CGSize)fp24 rowWidth:(float)fp32;
+ (float)rowHeightForSubtitle:(id)fp8 message:(id)fp12 maxLines:(unsigned int)fp16 rowWidth:(float)fp20;
+ (float)_rowHeightForContentHeight:(float)fp8;
+ (float)_contentWidthForRowWidth:(float)fp8 leaveRoomForIcon:(BOOL)fp12;
- (BOOL)_createsLockBarEarly;
- (void)layoutSubviews;
- (struct CGRect)_cellContentViewFrame;
- (struct CGRect)_contentRect;
- (BOOL)_drawsSeparator;
- (id)_lockBar;
- (void)setUnlockActionContext:(id)fp8;
- (void)setAttachmentImage:(id)fp8;
- (BOOL)_hasBackgroundColor;
- (void)_createContentView;

@end

