/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBSCardItem;

@interface SBAwayCardListItem : _ABAddressBookCopyLocalizedLabel
{
    SBSCardItem *_cardItem;
}

- (void)setCardItem:(id)fp8;
- (id)cardItem;
- (BOOL)inertWhenLocked;
- (id)sortDate;
- (void)dealloc;

@end

