/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBAwaySwipeGestureRecognizer : _ABAddressBookCopyLocalizedLabel
{
    struct CGPoint _startLocation;
    unsigned int _startTouchCount;
    double _startTime;
    unsigned int _requiredTouchCount;
    int _gestureType;
}

- (void)setRequiredTouchCount:(unsigned int)fp8;
- (unsigned int)requiredTouchCount;
- (BOOL)_isView:(id)fp8 subviewOfClass:(Class)fp12;
- (struct CGPoint)averagePositionForTouches:(id)fp8;
- (BOOL)isGestureFromLocation:(struct CGPoint)fp8 count:(unsigned int)fp16 toLocation:(struct CGPoint)fp20 count:(unsigned int)fp28 elapsedTime:(double)fp32 gestureType:(int *)fp40;
- (unsigned int)fingerCount;
- (int)recognizedGestureType;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;

@end

