/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBBulletinBusyClient-Protocol.h"
#import "SBBulletinWindowClient-Protocol.h"
#import "SBUIBannerSourceManager-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, SBBannerAndShadowView, UIView;

@interface SBBannerController : _ABAddressBookCopyLocalizedLabel <SBUIBannerSourceManager, SBBulletinWindowClient, SBBulletinBusyClient, UIGestureRecognizerDelegate>
{
    NSMutableSet *_sources;
    NSMutableArray *_pendingStickyBannerItems;
    SBBannerAndShadowView *_bannerAndShadowView;
    UIView *_snapshotViewForAssistantShrinkFromFull;
    UIView *_snapshotView;
    BOOL _soundIsPlaying;
    BOOL _dismissalOverdue;
    BOOL _replaceDelayIsActive;
    BOOL _showingStickyDurationBanner;
    BOOL _suppressingBanners;
    BOOL _enableDelayActive;
    BOOL _assistantIsFullyVisible;
    BOOL _bannerPanGestureInProgress;
    float _showcaseHeight;
    id _animationContext;
    id _dismissOverdueContext;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (void)setDismissOverdueContext:(id)fp8;
- (id)dismissOverdueContext;
- (void)setSnapshotViewForAssistantShrinkFromFull:(id)fp8;
- (id)snapshotViewForAssistantShrinkFromFull;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (id)_meshTransformForDegreesOfRotation:(float)fp8 flipInsets:(struct UIEdgeInsets)fp12 orientation:(int)fp28 topIsLive:(BOOL)fp32;
- (void)_removePerspective;
- (void)_setUpPerspectiveForNormalFlipRect:(struct CGRect)fp8;
- (struct CGRect)_calculateFlipRectAndCreateSnapshotViewForBannerFrame:(struct CGRect)fp8 orientation:(int)fp24;
- (struct CGRect)_currentBannerFrameForOrientation:(int)fp8;
- (struct CGRect)_normalBannerFrameForOrientation:(int)fp8;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)_flipWithContext:(id)fp8;
- (void)_soundDidFinishPlayingForBannerItem:(id)fp8;
- (void)_dismissOverdueOrDequeueIfPossible;
- (void)_stopCurrentSound;
- (void)_replaceIntervalElapsed;
- (void)_dismissIntervalElapsed;
- (void)_sendDismissCallbacksIfNecessary:(int)fp8;
- (void)_tryToDismissBannerWithContext:(id)fp8;
- (void)_tryToDismissBannerWithAnimation:(int)fp8;
- (void)_tryToDismissBannerWithAnimation:(int)fp8 dismissReason:(int)fp12;
- (void)_handleBannerTapGesture:(id)fp8;
- (void)_handleBannerPanGesture:(id)fp8;
- (void)_adjustShadowAlphasForProgress:(float)fp8;
- (float)_progressForBannerTranslation:(float)fp8 maxTranslation:(float)fp12;
- (void)_setBannerTranslation:(float)fp8 progress:(float)fp12;
- (BOOL)_presentBannerForItem:(id)fp8 existingDismissReason:(int)fp12;
- (void)_presentBannerView:(id)fp8 dismissReason:(int)fp12;
- (void)_presentBannerView:(id)fp8;
- (void)_tearDownView:(BOOL)fp8 reason:(int)fp12;
- (void)_tearDownView;
- (BOOL)_shouldPendStickyBannerItem:(id)fp8 withReason:(int)fp12;
- (BOOL)_dequeueBannerIfPossibleIgnoringStickyBanner:(BOOL)fp8 existingDismissReason:(int)fp12;
- (BOOL)_dequeueBannerIfPossibleIgnoringStickyBanner:(BOOL)fp8;
- (BOOL)_dequeueBannerIfPossible;
- (BOOL)_canDequeueIgnoringStickyBanner:(BOOL)fp8;
- (BOOL)_canDequeue;
- (id)_dequeueNextBannerItem;
- (BOOL)_isItemShowable:(id)fp8;
- (id)_animationContext;
- (void)_dequeueAfterDelayIfPossible;
- (void)_updateBannerSuppressionStateAndDequeueIfPossible:(BOOL)fp8 withDelay:(BOOL)fp12;
- (void)_updateBannerSuppressionState;
- (void)_removePendingStickyItemsForSource:(id)fp8;
- (id)_pendingStickyBannerItemForSource:(id)fp8;
- (void)assistantRevealModeDidChange:(id)fp8;
- (void)assistantRevealModeWillChange:(id)fp8;
- (void)bulletinWindowDidRotateFromOrientation:(int)fp8;
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)fp8;
- (void)bulletinWindowWillRotateToOrientation:(int)fp8;
- (void)bulletinWindowStoppedBeingBusy;
- (void)dismissCurrentBannerItemForSource:(id)fp8;
- (id)currentBannerItemForSource:(id)fp8;
- (void)signalSource:(id)fp8;
- (void)unregisterSource:(id)fp8;
- (void)registerSource:(id)fp8;
- (void)adjustLayoutForShowcaseHeight:(float)fp8;
- (id)newBannerSnapshotViewRotatedForOrientation:(int)fp8;
- (void)setBannerAlpha:(float)fp8;
- (void)dismissBannerWithAnimation:(int)fp8 reason:(int)fp12;
- (void)dismissBannerWithoutAnimationForReason:(int)fp8;
- (id)currentBannerItem;
- (BOOL)isShowingBanner;
- (void)dealloc;
- (id)init;

@end

