/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SUDescriptor;

@interface SBBaseSoftwareUpdateAlertItem : _ABAddressBookCopyLocalizedLabel
{
    SUDescriptor *_descriptor;
}

- (id)descriptor;
- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (BOOL)forcesModalAlertAppearance;
- (void)activateDisplayWithURL:(id)fp8;
- (void)activateSoftwareUpdateSettingsDisplay;
- (id)updateName;
- (void)dealloc;
- (id)initWithDescriptor:(id)fp8;

@end

