/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImage;

@interface SBBatteryReflectionView : _ABAddressBookCopyLocalizedLabel
{
    UIImage *_image;
    UIImage *_maskImage;
    float _bottomMargin;
}

- (void)drawRect:(struct CGRect)fp8;
- (void)setImage:(id)fp8;
- (void)dealloc;
- (id)initWithImage:(id)fp8 bottomMargin:(float)fp12;

@end

