/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBatteryReflectionView, UIImage, UIImageView, UILabel;

@interface SBBatteryChargingView : _ABAddressBookCopyLocalizedLabel
{
    int _type;
    UIImageView *_topBatteryView;
    SBBatteryReflectionView *_bottomBatteryView;
    UIImage *_lastBatteryImage;
    UILabel *_percentLabel;
    int _lastBatteryIndex;
    int _lastBatteryPercentage;
    unsigned int _showReflection:1;
}

+ (int)redChargeIndexForType:(int)fp8;
+ (float)batteryHeightForType:(int)fp8;
+ (struct CGSize)defaultSizeForType:(int)fp8;
- (void)_batteryStatusChanged:(id)fp8;
- (id)_imageFormatString;
- (int)_currentBatteryIndex;
- (void)setShowsReflection:(BOOL)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 type:(int)fp24;

@end

