/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView<SBUIBannerItemView>;

@interface SBBannerTransitionContext : _ABAddressBookCopyLocalizedLabel
{
    UIView<SBUIBannerItemView> *_fromView;
    UIView<SBUIBannerItemView> *_toView;
    int dismissReason;
    int animation;
}

+ (id)contextFromView:(id)fp8 toView:(id)fp12;
- (void)setAnimation:(int)fp8;
- (int)animation;
- (void)setDismissReason:(int)fp8;
- (int)dismissReason;
- (void)setToView:(id)fp8;
- (id)toView;
- (void)setFromView:(id)fp8;
- (id)fromView;
- (void)dealloc;

@end

