/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView, UIView, UIView<SBUIBannerItemView>;

@interface SBBannerAndShadowView : _ABAddressBookCopyLocalizedLabel
{
    UIView<SBUIBannerItemView> *_banner;
    UIImageView *_shadow[5];
    struct CGRect _shadowFrame[5];
    struct CGSize _bannerSize;
    struct CGPoint _bannerOrigin;
    float _sideWidth;
    float _bottomHeight;
    BOOL _shadowsInPortraitWindow;
    UIView *_rollerContainer;
    UIImageView *_roller;
}

- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)clearRoller;
- (void)setRollerProgress:(float)fp8;
- (void)prepareRoller;
- (void)setShadowAlpha:(float)fp8;
- (void)pullShadowsBack;
- (void)moveShadowsToPortraitWindow:(id)fp8 fromOrientation:(int)fp12;
- (void)_layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (struct CGRect)_frameForBannerFrame:(struct CGRect)fp8;
- (BOOL)_showsSideShadows;
- (void)setBannerFrame:(struct CGRect)fp8;
- (void)replaceBannerWithBanner:(id)fp8;
- (id)banner;
- (void)dealloc;
- (id)initWithBanner:(id)fp8;

@end

