/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray;

@interface SBBluetoothController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableArray *_devices;
    BOOL _tetheringConnected;
}

+ (id)sharedInstance;
- (void)bluetoothDeviceEndedVoiceControl:(id)fp8;
- (void)bluetoothDeviceInitiatedVoiceControl:(id)fp8;
- (BOOL)tetheringConnected;
- (id)deviceForAudioRoute:(id)fp8;
- (void)updateBattery;
- (void)batteryChanged:(id)fp8;
- (void)connectionChanged:(id)fp8;
- (void)updateTetheringConnected;
- (void)removeDeviceNotification:(id)fp8;
- (void)addDeviceNotification:(id)fp8;
- (void)iapDeviceChanged:(id)fp8;
- (void)stopWatchingForDevices;
- (void)startWatchingForDevices;
- (void)noteDevicesChanged;
- (int)batteryLevel;
- (BOOL)canReportBatteryLevel;
- (id)firstBTDeviceToReportBatteryLevel;
- (void)dealloc;

@end

