/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@class UIWebClip;

@interface SBBookmarkIcon : SBLeafIcon
{
    UIWebClip *_webClip;
}

- (void)setWebClip:(id)fp8;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)webClip;
- (void)completeUninstall;
- (void)launch;
- (id)displayName;
- (id)generateIconImage:(int)fp8;
- (BOOL)allowsUninstall;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithWebClip:(id)fp8;

@end

