/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBBrightnessController : _ABAddressBookCopyLocalizedLabel
{
    BOOL _debounce;
    struct BKSDisplayBrightnessTransaction *_brightnessDownTransaction;
    struct BKSDisplayBrightnessTransaction *_brightnessUpTransaction;
}

+ (id)sharedBrightnessController;
- (void)cancelBrightnessEvent;
- (void)handleBrightnessEvent:(struct __GSEvent *)fp8;
- (void)decreaseBrightnessAndRepeat;
- (void)increaseBrightnessAndRepeat;
- (void)setBrightnessLevel:(float)fp8;
- (void)_setBrightnessLevel:(float)fp8 showHUD:(BOOL)fp12;
- (void)adjustBacklightLevel:(BOOL)fp8;
- (float)_calcButtonRepeatDelay;

@end

