/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBulletinLinenSegmentView.h"

#import "SBBulletinClearButtonDelegate-Protocol.h"

@class NSString, SBBulletinBlurredShadowLabel, SBBulletinClearButton, UIView;

@interface SBBulletinHeaderView : SBBulletinLinenSegmentView <SBBulletinClearButtonDelegate>
{
    UIView *_translucentOverlay;
    UIView *_iconView;
    SBBulletinBlurredShadowLabel *_sectionLabel;
    SBBulletinBlurredShadowLabel *_sectionAltLabel;
    SBBulletinClearButton *_clearButton;
    id <SBBulletinHeaderViewDelegate> _delegate;
    NSString *_sectionID;
}

+ (float)headerHeight;
- (id)clearButton;
- (id)sectionID;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)willMoveToWindow:(id)fp8;
- (void)layoutSubviews;
- (void)_dateOrLocaleChanged:(id)fp8;
- (struct CGRect)_positionAltLabel;
- (BOOL)_configureAltTextInAvailableWidth:(float)fp8;
- (BOOL)_showingAltLabel;
- (void)setShowsClearButton:(BOOL)fp8 animated:(BOOL)fp12;
- (void)clearButton:(id)fp8 willTransitionWithDuration:(double)fp12;
- (void)clearButtonWasPressed:(id)fp8;
- (void)dealloc;
- (void)configureWithSection:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 linenView:(id)fp24;

@end

