/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView;

@interface SBBulletinClearButton : _ABAddressBookCopyLocalizedLabel
{
    BOOL _showingClear;
    UIImageView *_backgroundView;
    UIImageView *_xImageView;
    UIImageView *_clearImageView;
    float _widthWhenShowingX;
    float _widthWhenShowingClear;
    id _clearShownAction;
    id _clearPressedAction;
    id <SBBulletinClearButtonDelegate> _delegate;
}

+ (void)initialize;
+ (void)_removeCachedClearImage;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setClearPressedAction:(id)fp(null);
- (id)clearPressedAction;
- (void)setClearShownAction:(id)fp(null);
- (id)clearShownAction;
- (id)_precompositedXImage;
- (id)_background;
- (id)_xImage;
- (id)_clearImage;
- (void)_setShowsClear:(BOOL)fp8 animated:(BOOL)fp12;
- (void)_switchToUsingSubviews;
- (struct CGRect)_clearImageFrame;
- (struct CGRect)_xImageFrame;
- (struct CGRect)_xImageFrameInBounds:(struct CGRect)fp8;
- (void)_pressAction;
- (void)setHighlighted:(BOOL)fp8;
- (void)resetAnimated:(BOOL)fp8;
- (BOOL)showingClear;
- (void)dealloc;
- (id)init;

@end

