/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@interface SBBulletinListTouchEater : _ABAddressBookCopyLocalizedLabel <UIGestureRecognizerDelegate>
{
}

- (BOOL)canBePreventedByGestureRecognizer:(id)fp8;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;

@end

