/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBBulletinFadeOverlayOwner-Protocol.h"
#import "SBBulletinHeaderViewDelegate-Protocol.h"

@class NSMutableSet, SBBulletinLinenFadeView;

@interface SBBulletinTableView : _ABAddressBookCopyLocalizedLabel <SBBulletinHeaderViewDelegate, SBBulletinFadeOverlayOwner>
{
    NSMutableSet *_visibleSectionHeaders;
    SBBulletinLinenFadeView *_fadeContainer;
    BOOL _suppressUpdates;
    BOOL _hasReloadedOnce;
    unsigned int _animatingUpdateCount;
}

- (void)setSuppressUpdates:(BOOL)fp8;
- (BOOL)suppressUpdates;
- (void)headerViewWillDisappear:(id)fp8;
- (void)headerViewWillAppear:(id)fp8;
- (BOOL)hasReloadedOnce;
- (void)reloadData;
- (void)endUpdates;
- (void)beginUpdates;
- (void)_decrementAnimatingCount;
- (void)_incrementAnimatingCount;
- (BOOL)isAnimatingUpdates;
- (void)layoutSubviews;
- (void)_orderHeierarchyAndAdjustLinenViewBackingAsNecessary;
- (void)setLinenGradientAlpha:(float)fp8;
- (void)setRasterizesFadeOverlay:(BOOL)fp8;
- (id)visibleSectionHeaders;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 linenView:(id)fp24;

@end

