/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBBulletinLinenBackedCell : _ABAddressBookCopyLocalizedLabel
{
    UIView *_linenView;
    BOOL _showsLinen;
}

- (void)setFrame:(struct CGRect)fp8;
- (void)setLinenGradientAlpha:(float)fp8;
- (void)adjustLinenContents;
- (void)setShowsLinen:(BOOL)fp8;
- (BOOL)showsLinen;
- (void)dealloc;
- (id)initWithLinenView:(id)fp8 reuseIdentifier:(id)fp12;

@end

