/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBulletinLinenSegmentView, UIImageView;

@interface SBBulletinLinenFadeView : _ABAddressBookCopyLocalizedLabel
{
    SBBulletinLinenSegmentView *_fadeSegment;
    UIImageView *_fadeOverlayMask;
}

- (void)setGradientAlpha:(float)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (float)fadeHeight;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 linenView:(id)fp24;

@end

