/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBBulletinListViewDelegate-Protocol.h"
#import "SBBulletinWindowClient-Protocol.h"
#import "SBWeeAppDelegate-Protocol.h"

@class BBObserver, NSArray, NSMutableArray, NSMutableDictionary, NSTimer, SBApplication, SBBulletinClearButton, SBBulletinListTabView, SBBulletinListView, SBWeeApp, SBWeeAppPresentationView, UIView;

@interface SBBulletinListController : _ABAddressBookCopyLocalizedLabel <BBObserverDelegate, SBBulletinListViewDelegate, SBBulletinWindowClient, SBWeeAppDelegate>
{
    BBObserver *_observer;
    NSMutableDictionary *_enabledSectionsByID;
    NSMutableArray *_visibleSectionIDs;
    NSArray *_possibleSectionIDs;
    unsigned int _sectionOrderRule;
    NSMutableArray *_weeApps;
    NSMutableArray *_visibleWeeApps;
    NSMutableDictionary *_headerViewsBySectionID;
    SBBulletinListTabView *_tabView;
    SBBulletinListView *_listView;
    BOOL _listViewTableViewHasLoaded;
    BOOL _listViewIsActive;
    BOOL _animating;
    BOOL _weeAppFullViewsHaveBeenLoaded;
    BOOL _weeAppPresentingFullscreen;
    SBWeeApp *_presentingWeeApp;
    SBWeeAppPresentationView *_presentationView;
    UIView *_presentedFirstResponder;
    SBApplication *_coveredApplication;
    SBBulletinClearButton *_clearButtonCurrentlyInClearState;
    NSMutableArray *_enqueuedUpdates;
    BOOL _grabbed;
    float _grabbedY;
    BOOL _pullingDownOutsideList;
    float _showcaseOffset;
    NSTimer *_weeAppSnapshotTimer;
    id _keyboardNotificationObserverToken;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (BOOL)weeAppWantsNotificationCenterDismissal:(id)fp8;
- (BOOL)weeApp:(id)fp8 updatePresentationMode:(int)fp12 duration:(float)fp16 delay:(float)fp20;
- (void)weeAppWantsSizeUpdate:(id)fp8;
- (void)finishedScrollTest;
- (void)runScrollTest:(id)fp8 iterations:(int)fp12 delta:(int)fp16;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)tableView:(id)fp8 didEndDisplayingCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (void)tableViewDidFinishReload:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)_weeAppCellForSection:(id)fp8 sectionIndex:(unsigned int)fp12 tableView:(id)fp16;
- (BOOL)_useTopPaddingForWeeAppAtSectionIndex:(unsigned int)fp8;
- (id)_bulletinCellForSection:(id)fp8 sectionIndex:(unsigned int)fp12 row:(unsigned int)fp16 tableView:(id)fp20;
- (int)_separatorStyleForRow:(unsigned int)fp8 inSection:(id)fp12 sectionIndex:(unsigned int)fp16;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (struct CGSize)observer:(id)fp8 composedAttachmentSizeForType:(int)fp12 thumbnailWidth:(float)fp16 height:(float)fp20 key:(id)fp24;
- (id)observer:(id)fp8 composedAttachmentImageForType:(int)fp12 thumbnailData:(id)fp16 key:(id)fp20;
- (id)observer:(id)fp8 thumbnailSizeConstraintsForAttachmentType:(int)fp12;
- (BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)fp8;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)fp8;
- (void)observer:(id)fp8 updateSectionInfo:(id)fp12;
- (void)observer:(id)fp8 updateSectionOrder:(id)fp12;
- (void)observer:(id)fp8 updateSectionOrderRule:(unsigned int)fp12;
- (void)observer:(id)fp8 removeBulletin:(id)fp12;
- (void)observer:(id)fp8 modifyBulletin:(id)fp12;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (void)_updateModelAndTableViewForRemoval:(id)fp8 originalIndex:(unsigned int)fp12;
- (void)_updateModelAndTableViewForModification:(id)fp8 originalIndex:(unsigned int)fp12;
- (void)_updateModelAndTableViewForAddition:(id)fp8;
- (void)_fixLastRowSeparatorsAndWeeAppTopPaddingInAllSections;
- (void)_fixCellSeparatorAboveRow:(unsigned int)fp8 inSection:(id)fp12 sectionIndex:(unsigned int)fp16;
- (void)_updateModelAndTableViewForNewSectionInfo:(id)fp8;
- (void)_updateModelAndTableViewForEnabledWeeAppSection:(id)fp8 withVisibility:(BOOL)fp12;
- (void)_updateModelAndTableViewForNewSectionOrder:(id)fp8;
- (void)_updateModelAndTableViewForNewSectionOrderRule:(unsigned int)fp8;
- (void)bulletinWindowDidRotateFromOrientation:(int)fp8;
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)fp8;
- (void)bulletinWindowWillRotateToOrientation:(int)fp8;
- (void)bulletinWindowDidResignKey;
- (void)bulletinWindowDidBecomeKey;
- (BOOL)requiresKeyWindow;
- (void)_setClearButtonCurrentlyInClearState:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (void)handleEatenTouch:(id)fp8;
- (void)handlePan:(id)fp8;
- (void)handleTap:(id)fp8;
- (void)handleShowNotificationsGestureCanceled;
- (void)handleShowNotificationsGestureEndedWithVelocity:(struct CGPoint)fp8 completion:(id)fp(null);
- (void)handleShowNotificationsGestureChangedWithTouchLocation:(struct CGPoint)fp8 velocity:(struct CGPoint)fp16;
- (void)handleShowNotificationsGestureBeganWithTouchLocation:(struct CGPoint)fp8;
- (void)_updateForTouchCanceled;
- (void)_updateForTouchEndedWithVelocity:(struct CGPoint)fp8 completion:(id)fp(null);
- (void)_updateForTouchBeganOrMovedWithLocation:(struct CGPoint)fp8 velocity:(struct CGPoint)fp16;
- (void)_handleUngrabWithVelocity:(struct CGPoint)fp8 completion:(id)fp(null);
- (void)_clearSection:(id)fp8;
- (float)_headerHeightForSection:(id)fp8;
- (float)_rowHeightForBulletin:(id)fp8;
- (id)_indexPathForBulletin:(id)fp8;
- (id)_bulletinAtIndexPath:(id)fp8;
- (id)_sectionAtIndex:(unsigned int)fp8;
- (void)_configureForChangedContentAnimated:(BOOL)fp8;
- (void)_reloadTableView;
- (void)_loadSections;
- (void)_performEnqueuedUpdates;
- (void)_performOrEnqueueUpdate:(id)fp(null);
- (BOOL)_canPerformUpdate;
- (id)_weeAppForSectionID:(id)fp8 bundlePath:(id)fp12;
- (void)_removeWeeAppForSectionID:(id)fp8;
- (id)_weeAppForSectionID:(id)fp8;
- (unsigned int)_insertVisibleSectionID:(id)fp8;
- (void)_sortVisibleSectionIDs;
- (BOOL)isAnimating;
- (BOOL)weeAppIsFullScreen;
- (BOOL)listViewIsActive;
- (BOOL)isActive;
- (void)_tearDownPresentationView;
- (void)_tearDownTabView;
- (void)_tearDownListViewKeepingWindow:(BOOL)fp8;
- (void)_snapshotTimerFired;
- (void)_clearWeeAppSnapshots;
- (void)_clearSnapshotTimer;
- (void)adjustViewForShowcaseOffset:(float)fp8;
- (void)_setListViewActive:(BOOL)fp8;
- (void)showListViewWithInitialVelocity:(float)fp8 completion:(id)fp(null);
- (void)hideListViewWithInitialVelocity:(float)fp8 completion:(id)fp(null);
- (void)hideListViewWithInitialVelocity:(float)fp8 hiddenY:(float)fp12 extraPull:(BOOL)fp16 additionalValueApplier:(id)fp(null) completion:(void)fp20;
- (void)showListViewWithInitialVelocity:(float)fp8 additionalValueApplier:(id)fp(null) completion:(void)fp12;
- (id)_newDynamicAnimationForShow:(BOOL)fp8 targetValue:(double)fp12 withInitialVelocity:(double)fp20 extraPull:(BOOL)fp28;
- (void)hideFullScreenWeeApp;
- (void)hideListViewAnimated:(BOOL)fp8 useFade:(BOOL)fp12 keepWindow:(BOOL)fp16;
- (void)hideListViewAnimated:(BOOL)fp8 useFade:(BOOL)fp12;
- (void)hideListViewAnimated:(BOOL)fp8;
- (void)showListViewAnimated:(BOOL)fp8;
- (void)finishShowingListView;
- (void)_finishShowingListViewAnimated:(BOOL)fp8;
- (void)_cleanupAfterHideListViewKeepingWindow:(BOOL)fp8;
- (void)_cleanupAfterShowListView;
- (void)setListViewBottomShadowAlpha:(float)fp8;
- (void)positionListViewAtY:(float)fp8;
- (void)_positionTabViewAtY:(float)fp8;
- (void)prepareToHideListViewAnimated:(BOOL)fp8;
- (void)prepareToShowListViewAnimated:(BOOL)fp8 aboveBanner:(BOOL)fp12;
- (BOOL)isShowingTabView;
- (void)hideTabViewAnimated:(BOOL)fp8;
- (void)showTabViewAnimated:(BOOL)fp8;
- (float)listViewHeight;
- (id)listView;
- (void)_configureBBObserver;
- (void)dealloc;
- (id)init;

@end

