/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBObserverDelegate-Protocol.h"
#import "SBBulletinAlertHandler-Protocol.h"
#import "SBBulletinBusyClient-Protocol.h"

@class BBObserver, NSMapTable, NSMutableArray, NSMutableDictionary;

@interface SBBulletinModalController : _ABAddressBookCopyLocalizedLabel <BBObserverDelegate, SBBulletinAlertHandler, SBBulletinBusyClient>
{
    BBObserver *_observer;
    BOOL _deviceIsLocked;
    NSMutableArray *_incomingBulletinEventQueue;
    NSMutableDictionary *_handlersBySectionID;
    NSMapTable *_handlersByBulletinID;
    NSMapTable *_alertsByBulletinID;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)fp8;
- (void)handleEvent:(int)fp8 withBulletin:(id)fp12 forRegistry:(id)fp16;
- (BOOL)bindBulletin:(id)fp8 forRegistry:(id)fp12;
- (void)bulletinWindowStoppedBeingBusy;
- (void)observer:(id)fp8 purgeReferencesToBulletinID:(id)fp12;
- (void)observer:(id)fp8 removeBulletin:(id)fp12;
- (void)observer:(id)fp8 modifyBulletin:(id)fp12;
- (void)observer:(id)fp8 addBulletin:(id)fp12 forFeed:(unsigned int)fp16;
- (BOOL)_enqueueEventBlock:(id)fp(null);
- (void)_dequeuePendedEventsIfPossible;
- (void)_configureBBObserver;
- (id)init;
- (void)destroyingAlert:(id)fp8 withBulletinID:(id)fp12;

@end

