/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinClearButtonDelegate <NSObject>
- (void)clearButton:(id)fp8 willTransitionWithDuration:(double)fp12;
- (void)clearButtonWasPressed:(id)fp8;
@end

