/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBDateLabelDelegate-Protocol.h"

@class SBStringMetrics, UIColor, UIImageView, UILabel, UILabel<SBBulletinDateLabel>;

@interface SBBulletinCellContentViewBase : _ABAddressBookCopyLocalizedLabel <SBDateLabelDelegate>
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_messageLabel;
    SBStringMetrics *_messageMetrics;
    UILabel<SBBulletinDateLabel> *_dateLabel;
    UILabel<SBBulletinDateLabel> *_endDateLabel;
    UIImageView *_attachmentImageView;
    UILabel *_attachmentLabel;
    BOOL _isVIP;
    UIImageView *_vipImageView;
    unsigned int _maxMessageLines;
    unsigned int _maxTitleLines;
    struct CGSize _imageSize;
    UIColor *_shadowColor;
    int _layoutStyle;
    float _titleLineHeight;
    float _subtitleLineHeight;
    float _messageLineHeight;
    float _attachmentLineHeight;
    BOOL _highlighted;
    int _dateFormatStyle;
}

- (void)setDateFormatStyle:(int)fp8;
- (int)dateFormatStyle;
- (void)setLayoutStyle:(int)fp8;
- (int)layoutStyle;
- (BOOL)isHighlighted;
- (void)setAttachmentImageView:(id)fp8;
- (id)attachmentImageView;
- (void)setEndDateLabel:(id)fp8;
- (id)endDateLabel;
- (void)setDateLabel:(id)fp8;
- (id)dateLabel;
- (void)setAttachmentLabel:(id)fp8;
- (id)attachmentLabel;
- (void)setMessageLabel:(id)fp8;
- (id)messageLabel;
- (void)setSubtitleLabel:(id)fp8;
- (id)subtitleLabel;
- (void)setTitleLabel:(id)fp8;
- (id)titleLabel;
- (id)_vipAccessoryImage;
- (id)_attachmentFont;
- (id)_messageFont;
- (id)_subtitleFont;
- (id)_titleFont;
- (id)_dateFont;
- (void)_configureLabel:(id)fp8 withFont:(id)fp12 color:(id)fp16 alignment:(int)fp20;
- (float)_heightForLabel:(id)fp8 forWidth:(float)fp12 maxHeight:(float)fp16;
- (float)_heightForLabel:(id)fp8 forWidth:(float)fp12 minLines:(unsigned int)fp16 maxLines:(unsigned int)fp20 lineHeight:(float)fp24;
- (void)_updateLabelFontsAndLineHeights;
- (void)setVIP:(BOOL)fp8;
- (void)setAttachmentImageSize:(struct CGSize)fp8;
- (void)setAttachmentImage:(id)fp8;
- (void)setStartDate:(id)fp8 endDate:(id)fp12 timeZone:(id)fp16 allDay:(BOOL)fp20 formatStyle:(int)fp24;
- (void)dateLabelDidChange:(id)fp8;
- (void)setAttachmentText:(id)fp8;
- (void)setMessage:(id)fp8;
- (void)setSubtitle:(id)fp8;
- (void)setTitle:(id)fp8;
- (id)_modifiedLabel:(id)fp8 withText:(id)fp12 font:(id)fp16;
- (id)_modifiedLabel:(id)fp8 withText:(id)fp12 font:(id)fp16 alignment:(int)fp20;
- (void)setHighlighted:(BOOL)fp8;
- (void)setShadowColor:(id)fp8;
- (void)setMessageMaxLines:(unsigned int)fp8;
- (void)setTitleMaxLines:(unsigned int)fp8;
- (void)dealloc;
- (id)initForSystemAlertStyle;
- (id)initForBulletinStyle;
- (id)_initForLayoutStyle:(int)fp8;

@end

