/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BBSettingsGateway, BBSystemStateProvider;

@interface SBBulletinSystemStateAdapter : _ABAddressBookCopyLocalizedLabel
{
    BBSystemStateProvider *_stateProvider;
    BBSettingsGateway *_settingsGateway;
    BOOL _quietModeEnabled;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
- (void)_lostModeStateChanged;
- (void)_screenDimmed:(id)fp8;
- (void)_lockStateChanged:(id)fp8;
- (BOOL)quietModeEnabled;
- (void)_activeBehaviorOverrideTypesChanged:(unsigned int)fp8;
- (void)dealloc;
- (id)init;

@end

