/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinDateLabel <NSObject>
- (void)setLabelType:(int)fp8;
- (int)labelType;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAllDay:(BOOL)fp8;
- (BOOL)isAllDay;
- (void)prepareForReuse;
- (void)stopCoalescingUpdates;
- (void)startCoalescingUpdates;
- (void)setEndDate:(id)fp8 withTimeZone:(id)fp12;
- (void)setStartDate:(id)fp8 withTimeZone:(id)fp12;
@end

