/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BBBulletin, BBObserver, NSArray, SBUISound, UIImage;

@interface SBBulletinBannerItem : _ABAddressBookCopyLocalizedLabel
{
    BBBulletin *_seedBulletin;
    BBObserver *_observer;
    NSArray *_additionalBulletins;
    UIImage *_iconImage;
    SBUISound *_sound;
}

+ (id)itemWithSeedBulletin:(id)fp8 additionalBulletins:(id)fp12 andObserver:(id)fp16;
+ (id)itemWithBulletin:(id)fp8 andObserver:(id)fp12;
- (BOOL)canShowInAssistant;
- (id)sortDate;
- (id)seedBulletin;
- (id)action;
- (id)sound;
- (void)_setSound;
- (int)accessoryStyle;
- (id)attachmentText;
- (id)message;
- (id)title;
- (id)_appName;
- (id)iconImage;
- (id)attachmentImage;
- (id)additionalBulletins;
- (void)dealloc;
- (id)_initWithSeedBulletin:(id)fp8 additionalBulletins:(id)fp12 andObserver:(id)fp16;

@end

