/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinAlertHandler <NSObject>
- (void)handleEvent:(int)fp8 withBulletin:(id)fp12 forRegistry:(id)fp16;
- (BOOL)bindBulletin:(id)fp8 forRegistry:(id)fp12;
@end

