/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBulletinImageView.h"

@class UIView;

@interface SBBulletinLinenSegmentView : SBBulletinImageView
{
    UIView *_linenView;
    struct CGSize _linenSize;
    BOOL _showsLinen;
    SBBulletinImageView *_gradientView;
}

- (BOOL)showsLinen;
- (void)didMoveToWindow;
- (void)setFrame:(struct CGRect)fp8;
- (void)setGradientAlpha:(float)fp8;
- (void)adjustContents;
- (void)setShowsLinen:(BOOL)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 linenView:(id)fp24;

@end

