/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIActiveOrientationObserver-Protocol.h"

@class NSMutableSet, UIWindow;

@interface SBBulletinWindowController : _ABAddressBookCopyLocalizedLabel <SBUIActiveOrientationObserver>
{
    UIWindow *_bulletinWindow;
    int _trueBulletinWindowOrientation;
    int _overrideBulletinWindowOrientation;
    BOOL _rotatingKeyboard;
    BOOL _aboveShowcase;
    NSMutableSet *_windowClients;
    NSMutableSet *_keyClients;
    NSMutableSet *_busyClients;
    NSMutableSet *_busyReasons;
}

+ (BOOL)shouldSuppressAlertForBulletin:(id)fp8;
+ (id)sharedInstance;
- (BOOL)isWindowAboveShowcase;
- (id)window;
- (BOOL)_hasKeyWindowClients;
- (void)activeInterfaceOrientationDidChangeToOrientation:(int)fp8 willAnimateWithDuration:(double)fp12 fromOrientation:(int)fp20;
- (void)activeInterfaceOrientationWillChangeToOrientation:(int)fp8;
- (void)_setTrueWindowOrientation:(int)fp8;
- (void)_setOverrideWindowOrientation:(int)fp8;
- (void)_cleanUpAfterRotatingFromOrientation:(int)fp8;
- (void)_doRotationToOrientation:(int)fp8 duration:(double)fp12 forOverride:(BOOL)fp20;
- (void)_prepareToRotateToOrientation:(int)fp8 forOverride:(BOOL)fp12;
- (void)clearOverrideWindowOrientation;
- (BOOL)_hasOrientationOverride;
- (void)overrideWindowOrientation:(int)fp8;
- (void)updateBulletinWindowOrientation;
- (int)windowOrientationWithoutOverrides;
- (int)windowOrientation;
- (void)removeBusyClient:(id)fp8;
- (void)addBusyClient:(id)fp8;
- (void)removeWindowClient:(id)fp8;
- (void)_updateWindowTransformAndFrameForOrientation;
- (void)addWindowClient:(id)fp8;
- (void)_didResignKeyWindow:(id)fp8;
- (void)_didBecomeKeyWindow:(id)fp8;
- (void)_resignAsKeyWindow;
- (void)_becomeKeyWindow;
- (BOOL)allowsDismissBannerGesture;
- (BOOL)allowsHideNotificationsGesture;
- (BOOL)allowsShowNotificationsGesture;
- (BOOL)allowsShowNotificationsGestureFromBanner;
- (BOOL)_allowsShowNotificationsGestureFromBanner:(BOOL)fp8;
- (BOOL)_isBusyForReason:(id)fp8;
- (BOOL)isBusy;
- (void)setWindowAboveShowcase:(BOOL)fp8;
- (void)_assignWindowLevel;
- (void)setBusy:(BOOL)fp8 forReason:(id)fp12;
- (void)dealloc;
- (id)init;

@end

