/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BBBulletin, NSArray;

@interface SBBulletinModalAlert : _ABAddressBookCopyLocalizedLabel
{
    BBBulletin *_bulletin;
    NSArray *_buttons;
    NSArray *_bulletinButtonIndices;
    BOOL _playedSound;
    SBBulletinModalAlert *_superseded;
}

- (void)setBulletinButtonIndices:(id)fp8;
- (id)bulletinButtonIndices;
- (void)setButtons:(id)fp8;
- (id)buttons;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)willDeactivateForReason:(int)fp8;
- (void)didPresentAlertView:(id)fp8;
- (void)willPresentAlertView:(id)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)dismiss:(int)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)dealloc;
- (id)initWithBulletin:(id)fp8 supersededAlert:(id)fp12;
- (id)initWithBulletin:(id)fp8;

@end

