/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBulletinBannerItem, UIImageView, UILabel, UIView;

@interface SBBulletinBannerView : _ABAddressBookCopyLocalizedLabel
{
    SBBulletinBannerItem *_item;
    UIView *_iconView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    float _imageWidth;
    UIImageView *_accessoryImageView;
    UIImageView *_backgroundImageView;
}

- (id)_backgroundImageWithAttachmentImage:(id)fp8;
- (void)layoutSubviews;
- (void)_createSubviewsWithBackgroundImage:(id)fp8;
- (void)dealloc;
- (id)bannerItem;
- (id)initWithItem:(id)fp8;

@end

