/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBBulletinLockBar : _ABAddressBookCopyLocalizedLabel
{
}

- (void)setWellWidth:(float)fp8;
- (void)setAlpha:(float)fp8;
- (void)hideKnob;
- (void)showKnob;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (float)_calcKnobYOffset;
- (void)_adjustLabelOrigin;
- (float)knobTrackInsetRight;
- (BOOL)_shouldStopLabelAnimationForGrab;
- (BOOL)usesBackgroundImage;
- (BOOL)allowsTouchTrackingBeyondVerticalThreshold;
- (id)wellImageName;
- (float)defaultWellWidth;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 knobImage:(id)fp24;

@end

