/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSArray, NSDate, NSMutableArray, NSString, SBWeeApp, UIImage;

@interface SBBulletinListSection : _ABAddressBookCopyLocalizedLabel
{
    NSString *_sectionID;
    unsigned int _sectionType;
    SBWeeApp *_weeApp;
    NSMutableArray *_bulletins;
    NSArray *_sortDescriptors;
    NSString *_displayName;
    UIImage *_iconImage;
    BOOL _displaysCriticalBulletins;
    NSDate *_lastSortDate;
}

- (void)setSectionID:(id)fp8;
- (id)sectionID;
- (void)setIconImage:(id)fp8;
- (id)iconImage;
- (void)setDisplayName:(id)fp8;
- (id)sortDescriptors;
- (void)setWeeApp:(id)fp8;
- (id)weeApp;
- (id)bulletinAtIndex:(unsigned int)fp8;
- (unsigned int)replaceBulletin:(id)fp8 withBulletin:(id)fp12;
- (unsigned int)removeBulletin:(id)fp8;
- (unsigned int)_removeBulletin:(id)fp8;
- (unsigned int)addBulletin:(id)fp8;
- (unsigned int)indexOfBulletinID:(id)fp8;
- (unsigned int)_indexForNewBulletin:(id)fp8;
- (void)setSortDescriptors:(id)fp8;
- (int)compareSection:(id)fp8 forOrder:(unsigned int)fp12;
- (int)compare:(id)fp8;
- (id)displayName;
- (void)dealloc;
- (id)initWithSectionInfo:(id)fp8;
- (BOOL)showsTodaysDate;
- (BOOL)displaysCriticalBulletins;
- (id)lastSortDate;
- (BOOL)hasClearableBulletins;
- (unsigned int)bulletinCount;
- (BOOL)isBulletinSection;
- (BOOL)isWeeAppSection;
- (id)description;

@end

