/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBBulletinAttachmentFactory : _ABAddressBookCopyLocalizedLabel
{
}

+ (id)bannerTextForAdditionalAttachments:(unsigned int)fp8 showingImage:(BOOL)fp12;
+ (id)listTextForAdditionalAttachmentCount:(unsigned int)fp8;
+ (id)_nAttachments:(unsigned int)fp8;
+ (id)_nMoreAttachments:(unsigned int)fp8;
+ (id)bannerImageForAttachmentType:(int)fp8 thumbnailData:(id)fp12;
+ (id)lockScreenFloatingImageForAttachmentType:(int)fp8 thumbnailData:(id)fp12;
+ (id)listImageForAttachmentType:(int)fp8 thumbnailData:(id)fp12;
+ (id)_listImageForAttachmentType:(int)fp8 thumbnailData:(id)fp12 forFloatingAlert:(BOOL)fp16;
+ (id)_imageFromPNGData:(id)fp8;
+ (id)_imageByCroppingOrPaddingImage:(id)fp8 toSize:(struct CGSize)fp12;
+ (id)_genericImageForAttachmentType:(int)fp8;
+ (id)bannerThumbnailConstraintsForAttachmentType:(int)fp8;
+ (id)lockScreenFloatingThumbnailContraintsForAttachmentType:(int)fp8;
+ (id)listThumbnailConstraintsForAttachmentType:(int)fp8;
+ (struct CGSize)bannerImageSizeForAttachmentType:(int)fp8 thumbnailWidth:(float)fp12 height:(float)fp16;
+ (struct CGSize)listImageSizeForAttachmentType:(int)fp8 thumbnailWidth:(float)fp12 height:(float)fp16;

@end

