/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class CALayer;

@interface SBBuddyLogoZoomView : _ABAddressBookCopyLocalizedLabel
{
    CALayer *_contentLayer;
    id _animationCompleteBlock;
}

- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)startAnimationWithCompletionBlock:(id)fp(null);
- (id)initWithFrame:(struct CGRect)fp8;

@end

