/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBBulletinBlurredShadowLabel, SBBulletinListTouchEater, SBBulletinTableView, SBLinenFadeContainer, SBWeeAppPresentationView, UIImageView, UIStatusBar, UIView;

@interface SBBulletinListView : _ABAddressBookCopyLocalizedLabel
{
    int _orientation;
    float _currentY;
    UIView *_slidingView;
    UIImageView *_linenView;
    UIView *_linenContainer;
    struct CGSize _linenSize;
    SBBulletinTableView *_tableView;
    SBLinenFadeContainer *_tableContainer;
    UIStatusBar *_statusBar;
    UIView *_statusBarPocket;
    UIView *_grabber;
    SBWeeAppPresentationView *_presentationView;
    SBBulletinBlurredShadowLabel *_noNotificationsLabel;
    SBBulletinListTouchEater *_clearButtonTouchEater;
    UIView *_cornerView[4];
    UIView *_bottomShadowView;
    UIView *_linenGradient;
    UIView *_linenRim;
    UIView *_wholeShadowView;
    UIView *_sideShadowView[2];
    float _contentHeight;
}

+ (id)linen;
+ (void)load;
- (void)presentWeeApp:(id)fp8 animateWithDuration:(float)fp12 delay:(float)fp16 completion:(id)fp(null);
- (id)presentingWeeApp;
- (void)_removePresentingWeeAppWithDuration:(float)fp8 delay:(float)fp12 completion:(id)fp(null);
- (void)_presentWeeApp:(id)fp8 duration:(float)fp12 delay:(float)fp16 completion:(id)fp(null);
- (void)_removePresentationView;
- (void)didRotateFromOrientation:(int)fp8;
- (void)willRotateToOrientation:(int)fp8;
- (void)adjustLayoutForTableViewReload;
- (void)adjustLayoutForAnimatedTableViewContentHeightChange:(float)fp8 duration:(float)fp12 delay:(float)fp16;
- (void)adjustLayoutForAnimatedTableViewContentHeightChange:(float)fp8;
- (float)_linenGradientAlphaForHeight:(float)fp8;
- (float)_iPadSlidingViewHeightInOrientation:(int)fp8;
- (void)_ensureContentHeightHasBeenComputed;
- (void)layoutForOrientation:(int)fp8;
- (void)handleTableViewOffsetChange;
- (float)_pocketAlphaForTableViewOffset;
- (void)handleStatusBarTap:(id)fp8;
- (id)clearButtonTouchEater;
- (id)slidingView;
- (struct CGRect)slidingViewFrame;
- (void)setShowsNoNotificationsLabel:(BOOL)fp8 animated:(BOOL)fp12;
- (void)_positionNoNotificationsLabel;
- (void)setBottomShadowAlpha:(float)fp8;
- (void)setCornerAlpha:(float)fp8;
- (void)setBottomCornersOffscreen:(BOOL)fp8 animated:(BOOL)fp12;
- (float)currentY;
- (float)offscreenY;
- (float)onscreenY;
- (void)positionSlidingViewAtY:(float)fp8;
- (id)activeContentView;
- (float)linenGradientAlpha;
- (id)linenView;
- (id)tableView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 delegate:(id)fp24;

@end

