/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView;

@interface SBBulletinCellSelectionView : _ABAddressBookCopyLocalizedLabel
{
    UIImageView *_gradientView;
    float _cellSeparatorHeight;
}

- (void)layoutSubviews;
- (void)setCellSeparatorHeight:(float)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

