/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBulletinCellContentViewBase.h"

@class UIView;

@interface SBBulletinCellContentView : SBBulletinCellContentViewBase
{
    UIView *_blurView;
    UIView *_contentView;
    float _shadowBlur;
    void *_data;
    unsigned long _dataLength;
    BOOL _buttonsBelowContent;
}

+ (float)heightForSystemAlertStyleWithTitle:(id)fp8 maxLines:(unsigned int)fp12 message:(id)fp16 maxLines:(unsigned int)fp20 contentWidth:(float)fp24;
+ (float)heightForBulletinStyleWithSubtitle:(id)fp8 imageHeight:(float)fp12;
+ (float)heightForBulletinStyleWithSubtitle:(id)fp8 message:(id)fp12 maxLines:(unsigned int)fp16 contentWidth:(float)fp20;
+ (id)_attachmentFont;
+ (id)_messageFont;
+ (id)_subtitleFont;
+ (id)_dateFont;
+ (id)_titleFont;
- (void)displayLayer:(id)fp8;
- (void)drawInGrayscaleContexts;
- (void)drawInColorContext;
- (BOOL)getSourceData:(struct vImage_Buffer *)fp8 dstData:(struct vImage_Buffer *)fp12;
- (void)setNeedsDisplay;
- (void)setShadowColor:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)_drawLabel:(id)fp8 inContext:(struct CGContext *)fp12;
- (void)_drawLabel:(id)fp8 withMetrics:(id)fp12 inContext:(struct CGContext *)fp16;
- (void)_configureCTMForDrawingLabel:(id)fp8 inContext:(struct CGContext *)fp12;
- (void)layoutSubviews;
- (void)_layoutAttachmentTextAtX:(float)fp8;
- (float)_layoutMessageAtX:(float)fp8 y:(float)fp12;
- (float)_layoutAttachmentImageAtX:(float)fp8 y:(float)fp12;
- (float)_layoutSubtitleAtX:(float)fp8 y:(float)fp12;
- (float)_layoutTitleAtX:(float)fp8 y:(float)fp12;
- (BOOL)_shouldVerticallyCenterBulletinStyleDate;
- (BOOL)_shouldVerticallyCenterBulletinStyleTitle;
- (id)_attachmentFont;
- (id)_messageFont;
- (id)_subtitleFont;
- (id)_titleFont;
- (id)_dateFont;
- (void)_configureLabel:(id)fp8 withFont:(id)fp12 color:(id)fp16 alignment:(int)fp20;
- (void)dealloc;
- (id)_initForLayoutStyle:(int)fp8;
- (void)setHasButtonBelow:(BOOL)fp8;
- (void)setShadowBlur:(float)fp8;

@end

