/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBBulletinAlertHandlerRegistry-Protocol.h"

@class NSMutableDictionary;

@interface SBBulletinAlertHandlerRegistry : _ABAddressBookCopyLocalizedLabel <SBBulletinAlertHandlerRegistry>
{
    NSMutableDictionary *_handlersBySectionID;
}

- (void)addAlertHandler:(id)fp8 forSection:(id)fp12;
- (id)alertHandlersForSection:(id)fp8;
- (void)dealloc;
- (id)init;

@end

