/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, NSURL, SBApplication;

@interface SBCallPermissionAlertItem : _ABAddressBookCopyLocalizedLabel
{
    NSURL *_url;
    SBApplication *_appHandlingURL;
    NSString *_sender;
}

- (BOOL)allowMenuButtonDismissal;
- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)dealloc;
- (id)initWithURL:(id)fp8 applicationHandlingURL:(id)fp12 sender:(id)fp16;

@end

