/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBCallFailureAlertItem : _ABAddressBookCopyLocalizedLabel
{
    long _causeCode;
    NSString *_address;
    struct __CTCall *_call;
}

- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)performUnlockAction;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (id)shortLockLabel;
- (id)lockLabel;
- (void)_callback;
- (void)dealloc;
- (id)initWithCauseCode:(long)fp8 call:(struct __CTCall *)fp12;

@end

