/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBCalendarApplicationIcon : SBApplicationIcon
{
}

- (BOOL)canGenerateImageInBackgroundForFormat:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (void)localeChanged;
- (void)dealloc;
- (id)initWithApplication:(id)fp8;

@end

