/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBCardItemsControllerRemoteInterface-Protocol.h"
#import "XPCProxyTarget-Protocol.h"

@class NSMutableArray, NSMutableDictionary;

@interface SBCardItemsController : _ABAddressBookCopyLocalizedLabel <SBCardItemsControllerRemoteInterface, XPCProxyTarget>
{
    NSMutableArray *_remoteControllers;
    NSMutableDictionary *_cardItems;
}

- (id)proxy:(id)fp8 detailedSignatureForSelector:(SEL)fp12;
- (void)getCardItemsForControllerWithIdentifier:(id)fp8 withHandler:(id)fp(null);
- (void)clearCardItemsForControllerWithIdentifier:(id)fp8;
- (void)removeCardItems:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)addCardItems:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)setCardItems:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)_activateAllCardItems;
- (void)cardItemsDidChange:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)_addControllerWithConnection:(id)fp8;
- (void)dealloc;
- (id)init;

@end

