/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBCardItemsControllerRemoteInterface <NSObject>
- (void)getCardItemsForControllerWithIdentifier:(id)fp8 withHandler:(id)fp(null);
- (void)clearCardItemsForControllerWithIdentifier:(id)fp8;
- (void)setCardItems:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)removeCardItems:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)addCardItems:(id)fp8 forControllerWithIdentifier:(id)fp12;
- (void)cardItemsDidChange:(id)fp8 forControllerWithIdentifier:(id)fp12;
@end

