/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBZoomView.h"

@class SBFullscreenZoomView, UIView;

@interface SBClippedZoomView : SBZoomView
{
    SBFullscreenZoomView *_fullscreenZoomViewToClip;
    UIView *_clippingView;
}

- (void)setRoundedCorners:(int)fp8 withCornersFrame:(struct CGRect)fp12;
- (void)dealloc;
- (id)initWithClippingFrame:(struct CGRect)fp8 fullscreenZoomView:(id)fp24;

@end

