/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBCornerViewFactory : _ABAddressBookCopyLocalizedLabel
{
}

+ (id)newCornerWindowForCorner:(int)fp8 windowLevel:(float)fp12 cornersFrame:(struct CGRect)fp16;
+ (id)newCornerViewForCorner:(int)fp8 cornersFrame:(struct CGRect)fp12;

@end

