/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray;

@interface SBCompassRecalibrationController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableArray *_assertionPorts;
}

+ (id)sharedInstance;
- (void)_clientInvalidated:(struct __CFMachPort *)fp8;
- (void)clientRequestedCompassHUD:(unsigned int)fp8;
- (void)removeHUD;
- (void)showHUD;
- (BOOL)isCompassCalibrationHUDVisible;
- (void)dealloc;

@end

