/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class CALayerHost;

@interface SBContext : _ABAddressBookCopyLocalizedLabel
{
    unsigned int _contextId;
    float _windowLevel;
    BOOL _hidden;
    BOOL _orderOutPending;
    CALayerHost *_layerHost;
}

- (void)setOrderOutPending:(BOOL)fp8;
- (BOOL)isOrderOutPending;
- (void)setLayerHost:(id)fp8;
- (id)layerHost;
- (void)setHidden:(BOOL)fp8;
- (BOOL)isHidden;
- (void)setWindowLevel:(float)fp8;
- (float)windowLevel;
- (void)setContextId:(unsigned int)fp8;
- (unsigned int)contextId;
- (id)description;
- (void)dealloc;

@end

