/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBDaemonRequest : _ABAddressBookCopyLocalizedLabel
{
    id _enabler;
    id _disabler;
}

+ (id)requestWithEnabler:(id)fp(null) disabler:(void)fp8;
- (void)setDisabler:(id)fp(null);
- (id)disabler;
- (void)setEnabler:(id)fp(null);
- (id)enabler;
- (void)dispatchDisablerOnQueue:(id)fp8;
- (void)dispatchEnablerOnQueue:(id)fp8;
- (void)dealloc;

@end

