/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary, NSObject<OS_dispatch_source>;

@interface SBDaemonContext : _ABAddressBookCopyLocalizedLabel
{
    NSObject<OS_dispatch_source> *_dispatchSource;
    NSMutableDictionary *_daemonRequests;
    int _pid;
}

- (id)description;
- (void)removeRequestForKey:(id)fp8;
- (void)addRequest:(id)fp8 forKey:(id)fp12;
- (void)_handleCancelation;
- (id)_newDispatchSourceForPid:(int)fp8 queue:(id)fp12;
- (int)pid;
- (void)dealloc;
- (id)initWithPid:(int)fp8 queue:(id)fp12;

@end

