/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDataPlanAccountAlertItem.h"

@class NSDate;

@interface SBDataPlanExpirationAlertItem : SBDataPlanAccountAlertItem
{
    NSDate *_expirationDate;
}

- (void)setExpirationDate:(id)fp8;
- (id)expirationDate;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)dealloc;
- (id)initWithAccountURL:(id)fp8 expirationDate:(id)fp12;

@end

