/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDataPlanAlertItem.h"

@class NSString;

@interface SBDataPlanCompletionAlertItem : SBDataPlanAlertItem
{
    NSString *_carrierName;
    BOOL _newAccount;
}

- (void)setNewAccount:(BOOL)fp8;
- (BOOL)isNewAccount;
- (void)setCarrierName:(id)fp8;
- (id)carrierName;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)dealloc;
- (id)initWithCarrierName:(id)fp8 newAccount:(BOOL)fp12;

@end

