/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBDataPlanAccountAlertItem.h"

@class NSString;

@interface SBDataPlanFailureAlertItem : SBDataPlanAccountAlertItem
{
    NSString *_carrierName;
    BOOL _newAccount;
}

+ (id)nowButtonTitle;
+ (id)laterButtonTitle;
- (void)setNewAccount:(BOOL)fp8;
- (BOOL)isNewAccount;
- (void)setCarrierName:(id)fp8;
- (id)carrierName;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)dealloc;
- (id)initWithAccountURL:(id)fp8 carrierName:(id)fp12 newAccount:(BOOL)fp16;

@end

