/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBDateTimeCache : _ABAddressBookCopyLocalizedLabel
{
    double _yesterday;
    double _today;
    double _tomorrow;
    double _2daysFromNow;
    double _6daysAgo;
    double _prevWeek;
    double _nextWeek;
    double _lastAttemptedResetTime;
    double _lastSuccessfulResetTime;
}

+ (id)sharedInstance;
- (id)description;
- (void)_resetAndConfigure;
- (void)_resetAndConfigureIfNecessary;
- (BOOL)isWithinNextWeek:(double)fp8;
- (BOOL)isWithinPrevWeek:(double)fp8 includeToday:(BOOL)fp16;
- (BOOL)isWithinPrevWeek:(double)fp8;
- (BOOL)isYesterday:(double)fp8;
- (BOOL)isTomorrow:(double)fp8;
- (BOOL)_isToday:(double)fp8;
- (BOOL)isToday:(double)fp8;
- (double)nextWeek;
- (double)prevWeek;
- (double)yesterday;
- (double)tomorrow;
- (double)today;
- (void)dealloc;
- (id)init;

@end

