/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSDictionary, NSMutableSet;

@interface SBDataLookupResults : _ABAddressBookCopyLocalizedLabel
{
    NSDictionary *_applicationDictionaries;
    NSMutableSet *_registeredBundleIDs;
    NSMutableSet *_unregisteredBundleIDs;
}

- (id)unregisteredBundleIDs;
- (id)registeredBundleIDs;
- (id)applicationDictionaries;
- (void)updateWithResults:(id)fp8;
- (void)dealloc;
- (id)initWithApplicationDictionaries:(id)fp8 registeredBundleIDs:(id)fp12 unregisteredBundleIDs:(id)fp16;

@end

