/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImage;

@interface SBDefaultImageInfo : _ABAddressBookCopyLocalizedLabel
{
    int _launchingInterfaceOrientation;
    float _launchingScale;
    int _originalOrientation;
    int _currentOrientation;
    BOOL _hasSnapshot;
    UIImage *_image;
}

- (void)setImage:(id)fp8;
- (id)image;
- (void)setHasSnapshot:(BOOL)fp8;
- (BOOL)hasSnapshot;
- (void)setCurrentOrientation:(int)fp8;
- (int)currentOrientation;
- (void)setOriginalOrientation:(int)fp8;
- (int)originalOrientation;
- (void)setLaunchingScale:(float)fp8;
- (float)launchingScale;
- (void)setLaunchingInterfaceOrientation:(int)fp8;
- (int)launchingInterfaceOrientation;
- (id)description;
- (void)dealloc;

@end

