/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableSet, NSTimeZone, PCPersistentTimer;

@interface SBDeviceLockController : _ABAddressBookCopyLocalizedLabel
{
    int _deviceLockState;
    BOOL _isPermanentlyBlocked;
    BOOL _isBlockedForThermalCondition;
    double _deviceLockBlockTime;
    double _lastLockWallTime;
    NSTimeZone *_lastLockTimeZone;
    double _lastLockSecondsSinceBoot;
    PCPersistentTimer *_deviceLockTimer;
    int _gracePeriodWhenLocked;
    NSMutableSet *_preventLockAssertions;
    NSMutableSet *_gracePeriodSuspendAssertions;
    BOOL _okToSendNotifications;
}

+ (id)sharedController;
- (void)removeDeviceLockDisableAssertion:(id)fp8;
- (void)addDeviceLockDisableAssertion:(id)fp8;
- (BOOL)_hasAnyActiveDeviceLockDisableAssertions;
- (BOOL)_hasActiveGracePeriodSuspendAssertions;
- (BOOL)_hasActivePreventLockAssertions;
- (BOOL)attemptDeviceUnlockWithPassword:(id)fp8 appRequested:(BOOL)fp12;
- (void)notePasscodeGracePeriodMayHaveChanged;
- (void)_clearBlockedState;
- (BOOL)isPermanentlyBlocked:(double *)fp8;
- (BOOL)isBlocked;
- (void)_setDeviceLockState:(int)fp8;
- (void)enableDeviceLock;
- (void)_clearDeviceLockedTimer;
- (BOOL)_shouldLockDeviceWithCurrentGracePeriod:(int)fp8;
- (int)_getGracePeriod;
- (void)_beginGracePeriod;
- (void)_updateDeviceLockedState;
- (void)_setDeviceLockTimer;
- (BOOL)_shouldSetDeviceLockTimer;
- (void)_cancelGracePeriodIfNecessaryAndPossible;
- (BOOL)_shouldLockDeviceNow;
- (BOOL)_shouldBeginGracePeriodNow;
- (void)setBlockedForThermalCondition:(BOOL)fp8;
- (void)_sendBlockStateChangeNotification;
- (BOOL)isBlockedForThermalCondition;
- (BOOL)isDeviceLockedOrBlocked;
- (BOOL)isDeviceLocked;
- (BOOL)isPasswordProtected;
- (id)lastLockDate;
- (void)profileConnectionDidReceivePasscodeChangedNotification:(id)fp8 userInfo:(id)fp12;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)fp8 userInfo:(id)fp12;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)fp8 userInfo:(id)fp12;
- (void)dealloc;
- (id)init;

@end

