/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString;

@interface SBDeviceLockDisableAssertion : _ABAddressBookCopyLocalizedLabel
{
    NSString *_identifier;
    int _type;
}

- (void)dealloc;
- (int)type;
- (id)description;
- (id)initWithIdentifier:(id)fp8 type:(int)fp12;

@end

