/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIAlertViewDelegate-Protocol.h"

@class SBIcon;

@interface SBDeleteIconAlertItem : _ABAddressBookCopyLocalizedLabel <UIAlertViewDelegate>
{
    SBIcon *_icon;
    BOOL _checkedDocumentsInCloudState;
    BOOL _appHasDocumentsInCloud;
    BOOL _appHasDocumentsWithPendingUpdates;
    BOOL _askedUserAboutDocumentsDocumentsInCloud;
    BOOL _askedUserAboutDocumentsWithPendingUpdates;
}

- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)_checkDocumentsInCloudStateIfNeeded;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (id)icon;
- (void)dealloc;
- (id)initWithIcon:(id)fp8;

@end

