/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBDetailSlider : _ABAddressBookCopyLocalizedLabel
{
}

- (struct CGRect)thumbRectForBounds:(struct CGRect)fp8 trackRect:(struct CGRect)fp24 value:(float)fp40;
- (id)timeLabelTextColorForStyle:(int)fp8;
- (struct CGSize)timeLabelShadowOffsetForStyle:(int)fp8;
- (id)timeLabelShadowColorForStyle:(int)fp8;
- (id)timeLabelFontForStyle:(int)fp8;
- (id)currentThumbImage;

@end

