/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBDisplayProtocol <NSObject>
- (id)deactivationValue:(unsigned int)fp8;
- (BOOL)deactivationFlag:(unsigned int)fp8;
- (void)setDeactivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDeactivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDeactivationSettings;
- (id)activationValue:(unsigned int)fp8;
- (BOOL)activationFlag:(unsigned int)fp8;
- (void)setActivationSetting:(unsigned int)fp8 value:(id)fp12;
- (void)setActivationSetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearActivationSettings;
- (id)displayValue:(unsigned int)fp8;
- (BOOL)displayFlag:(unsigned int)fp8;
- (void)setDisplaySetting:(unsigned int)fp8 value:(id)fp12;
- (void)setDisplaySetting:(unsigned int)fp8 flag:(BOOL)fp12;
- (void)clearDisplaySettings;
- (BOOL)expectsFaceContactInLandscape;
- (BOOL)expectsFaceContact;
- (void)setExpectsFaceContact:(BOOL)fp8 inLandscape:(BOOL)fp12;
- (void)setExpectsFaceContact:(BOOL)fp8;
- (void)deactivate;
- (void)activate;
- (double)autoLockTime;
- (double)autoDimTime;
- (BOOL)suppressesNotifications;
- (double)accelerometerSampleInterval;
- (void)setAccelerometerSampleInterval:(double)fp8;
- (BOOL)orientationChangedEventsEnabled;
- (void)setOrientationChangedEventsEnabled:(BOOL)fp8;
- (BOOL)allowsEventOnlySuspension;
- (int)statusBarStyle;
@end

