/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SSDownloadQueueObserver-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, SSDownloadQueue;

@interface SBDownloadController : _ABAddressBookCopyLocalizedLabel <SSDownloadQueueObserver>
{
    SSDownloadQueue *_downloadQueue;
    NSMutableSet *_pendingDownloadRemovals;
    NSMutableArray *_downloads;
    unsigned int _downloadLoadCount;
    NSMutableDictionary *_bundleIDDownloadMap;
    BOOL _hasDownloadedStoreDownload;
}

+ (id)sharedInstance;
- (void)downloadingIconStatusDidChange:(id)fp8;
- (id)bundleIdentifiersBeingDownloaded:(id)fp8;
- (BOOL)bundledIdentifierIsBeingDownloaded:(id)fp8;
- (BOOL)moveDownloadToFrontOfQueue:(id)fp8;
- (void)cancelDownload:(id)fp8;
- (id)currentDownloads;
- (BOOL)checkQueue;
- (void)downloadQueueError:(id)fp8;
- (void)_showDownloadQueueError;
- (void)downloadQueueNetworkUsageChanged:(id)fp8;
- (void)downloadQueue:(id)fp8 downloadStatusChangedAtIndex:(int)fp12;
- (void)_processDownloadQueueChangedWithPendingRemovals;
- (void)downloadQueue:(id)fp8 changedWithRemovals:(id)fp12;
- (id)downloadWithBundleIdentifier:(id)fp8;
- (void)_delayedDownloadQueueChange;
- (void)_downloadsEnded;
- (void)_downloadingIconWasRemoved:(id)fp8;
- (void)_finishDownloadInStore:(id)fp8;
- (void)_finishDownloadInLocalState:(id)fp8;
- (void)_finishDownload:(id)fp8;
- (BOOL)hasDownloadedStoreDownload;
- (void)dealloc;
- (id)init;

@end

