/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView, UIView;

@interface SBDownloadingProgressBar : _ABAddressBookCopyLocalizedLabel
{
    UIView *_clipView;
    UIImageView *_fillView;
    float _progress;
}

+ (float)defaultHeight;
- (void)updateFill;
- (float)progress;
- (void)setProgress:(float)fp8;
- (id)fillImage;
- (id)trackImage;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

