/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@class NSMutableArray, NSOperation, NSString, SSDownload, SSDownloadStatus;

@interface SBDownloadingIcon : SBLeafIcon
{
    NSString *_applicationBundleID;
    SSDownload *_download;
    float _progress;
    BOOL _installing;
    BOOL _wasUninstalledByUser;
    BOOL _isNewsstandDownload;
    SSDownloadStatus *_lastStatus;
    SSDownload *_downloadForImageDataBeingLoaded;
    NSOperation *_iconImageGenerationOperation;
    NSMutableArray *_imageCacheFilePaths;
    BOOL _imageCacheBeingRead;
}

+ (id)__iconImageFromData:(id)fp8 format:(int)fp12 scale:(float)fp16 options:(int)fp20 darken:(BOOL)fp24;
+ (id)__darkenedIconImageForImage:(id)fp8;
+ (id)leafIdentifierForDownload:(id)fp8;
+ (id)leafIdentifierForDownloadUniqueID:(id)fp8;
+ (void)setupDownloadingIconImageCache;
+ (id)__imageCacheDirectoryPath;
+ (id)backgroundQueue;
- (BOOL)iconAppearsInNewsstand;
- (void)_showAlertForError:(id)fp8;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitle;
- (void)setUninstalledByUser:(BOOL)fp8;
- (BOOL)uninstalledByUser;
- (void)retry;
- (void)setNewsstandDownload:(BOOL)fp8;
- (BOOL)isNewsstandDownload;
- (id)download;
- (void)setDownload:(id)fp8;
- (void)setDownload:(id)fp8 allowReloadImage:(BOOL)fp12;
- (void)setApplicationBundleID:(id)fp8;
- (id)applicationBundleID;
- (BOOL)isDone;
- (float)progress;
- (void)reloadForStatusChange;
- (void)completeUninstall;
- (BOOL)allowsUninstall;
- (void)launch;
- (id)realDisplayName;
- (id)displayName;
- (id)_downloadingLabel;
- (BOOL)canEllipsizeLabel;
- (id)generateIconImage:(int)fp8;
- (void)_removeImageCacheFileAtPath:(id)fp8;
- (void)_reloadThumbnailImage;
- (void)loadAndDarkenHomeScreenIconImageInBackground;
- (BOOL)shouldCacheImageForFormat:(int)fp8;
- (id)getGenericIconImage:(int)fp8;
- (int)_iconImageOptions;
- (id)undarkenedHomeScreenIconImage;
- (id)identifierForCorrespondingApplicationIcon;
- (id)description;
- (id)representation;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithDownload:(id)fp8;
- (id)initWithDownload:(id)fp8 tryLoadImageImmediately:(BOOL)fp12;
- (id)initWithLeafIdentifier:(id)fp8;

@end

