/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconListView.h"

@interface SBDockIconListView : SBIconListView
{
}

+ (id)backgroundImageForOrientation:(int)fp8;
+ (unsigned int)iconRowsForInterfaceOrientation:(int)fp8;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)fp8;
- (unsigned int)columnAtPoint:(struct CGPoint)fp8;
- (struct CGPoint)originForIconAtX:(unsigned int)fp8 Y:(unsigned int)fp12;
- (float)_additionalSideInsetToCenterIcons;
- (float)sideIconInset;
- (unsigned int)rowAtPoint:(struct CGPoint)fp8;
- (float)topIconInset;
- (unsigned int)iconsInRowForSpacingCalculation;
- (int)visibleIconsInDock;
- (void)setOrientation:(int)fp8 duration:(double)fp12;
- (void)setOrientation:(int)fp8;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)_updateForOrientation:(int)fp8 duration:(double)fp12;
- (id)initWithFrame:(struct CGRect)fp8 viewMap:(id)fp24;
- (id)initForOrientation:(int)fp8 viewMap:(id)fp12;

@end

