/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconView.h"

#import "SBDownloadingIconObserver-Protocol.h"

@class SBDownloadingProgressBar;

@interface SBDownloadingIconView : SBIconView <SBDownloadingIconObserver>
{
    SBDownloadingProgressBar *_progressView;
}

+ (Class)_labelImageParametersClassForIcon:(id)fp8 location:(int)fp12;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)downloadingIconStatusDidChange:(id)fp8;
- (void)setGhostly:(BOOL)fp8 requester:(int)fp12;
- (void)_updateProgressBar;
- (void)setDisplayedIconImage:(id)fp8;
- (void)setIcon:(id)fp8;
- (void)setDownloadingIcon:(id)fp8;
- (id)downloadingIcon;
- (void)dealloc;
- (id)initWithDefaultSize;

@end

