/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBEmergencyCallView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_topBar;
}

- (void)dealloc;
- (void)setTopBar:(id)fp8;
- (id)topBar;
- (id)initWithFrame:(struct CGRect)fp8 topBarFrame:(struct CGRect)fp24 bottomBarFrame:(struct CGRect)fp40;

@end

