/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary;

@interface SBEventObserverRegistry : _ABAddressBookCopyLocalizedLabel
{
    void *_provider;
    NSMutableDictionary *_observers;
}

+ (id)sharedInstance;
- (void)setValue:(BOOL)fp8 forState:(struct __CFString *)fp12;
- (void)postEventToInterestedObservers:(struct __CFString *)fp8;
- (void)removeObserverWithToken:(unsigned long long)fp8 forEvent:(id)fp16;
- (void)addObserverWithToken:(unsigned long long)fp8 forEvent:(id)fp16;
- (id)init;
- (void)handleEvent:(id)fp8 token:(unsigned long long)fp12 action:(long)fp20;

@end

