/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIAlertView;

@interface SBFlippyAlertItem : _ABAddressBookCopyLocalizedLabel
{
    UIAlertView *_frontAlertSheet;
    UIAlertView *_backAlertSheet;
    BOOL _showingBack;
    BOOL _isLocked;
    BOOL _requirePasscode;
}

- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)flip;
- (void)configureBack:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)configureFront:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)cleanPreviousConfiguration;
- (void)dealloc;
- (id)alertSheet;
- (id)backAlertSheet;
- (id)frontAlertSheet;
- (id)newBackAlertSheet;
- (id)newFrontAlertSheet;
- (Class)alertSheetClass;
- (Class)backAlertSheetClass;
- (Class)frontAlertSheetClass;

@end

