/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconListView.h"

@interface SBFolderIconListView : SBIconListView
{
}

+ (unsigned int)iconRowsForInterfaceOrientation:(int)fp8;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)fp8;
- (struct CGRect)nineIconRectForScrollPosition:(int)fp8;
- (float)bottomIconInset;
- (float)topIconInset;

@end

