/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

#import "SBIconIndexNodeObserver-Protocol.h"
#import "SBIconObserver-Protocol.h"

@class NSHashTable, NSMutableSet, SBFolder;

@interface SBFolderIcon : SBIcon <SBIconObserver, SBIconIndexNodeObserver>
{
    SBFolder *_folder;
    NSHashTable *_nodeObservers;
    NSMutableSet *_finishedDownloadIdentifiers;
    float _progress;
}

+ (Class)_iconGridImageClass;
+ (unsigned int)_maxIconsInGridImage;
- (id)folder;
- (BOOL)isFolderIcon;
- (void)node:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)node:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (id)nodeDescriptionWithPrefix:(id)fp8;
- (void)removeNodeObserver:(id)fp8;
- (void)addNodeObserver:(id)fp8;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (id)nodeIdentifier;
- (void)downloadingIconStatusDidChange:(id)fp8;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)iconImageDidUpdate:(id)fp8;
- (id)miniGridCellImageForIcon:(id)fp8;
- (id)gridImageWithSkipping:(BOOL)fp8;
- (id)_miniIconGridWithSkipping:(BOOL)fp8;
- (unsigned int)gridCellIndexForIconIndex:(unsigned int)fp8 withSkipping:(BOOL)fp12;
- (BOOL)gridImageShouldSkipIcons;
- (struct _NSRange)_gridImageSkippedIconsRange;
- (void)_containedIconImageChanged:(id)fp8;
- (void)noteContainedIcon:(id)fp8 replacedIcon:(id)fp12;
- (void)noteContainedIconsAdded:(id)fp8 removed:(id)fp12;
- (void)_adjustForIconsAdded:(id)fp8 removed:(id)fp12;
- (void)updateProgress;
- (float)progress;
- (void)_updateProgressBar;
- (void)noteCompletedDownloadIdentifier:(id)fp8;
- (void)_updateBadgeValue;
- (void)updateLabel;
- (void)launch;
- (id)description;
- (void)localeChanged;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)representation;
- (id)displayName;
- (id)iconOverlayImageForLocation:(int)fp8;
- (id)getGenericIconImage:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (void)dealloc;
- (id)initWithFolder:(id)fp8;

@end

