/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSSet;

@interface SBFolderRotationAnimationContext : _ABAddressBookCopyLocalizedLabel
{
    NSSet *_icons;
    CDAnonymousStruct6 _notchInfo;
    double _duration;
}

- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setNotchInfo:(CDAnonymousStruct6)fp8;
- (CDAnonymousStruct6)notchInfo;
- (void)setIcons:(id)fp8;
- (id)icons;
- (void)dealloc;

@end

