/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBFolderNotchHighlightView : _ABAddressBookCopyLocalizedLabel
{
    CDAnonymousStruct6 _notchInfo;
}

- (void)drawRect:(struct CGRect)fp8;
- (id)initWithNotchInfo:(CDAnonymousStruct6)fp8;

@end

