/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconIndexMutableListObserver-Protocol.h"
#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, NSMutableDictionary, NSMutableSet, NSString, SBFolderIcon, SBIconIndexMutableList;

@interface SBFolder : _ABAddressBookCopyLocalizedLabel <SBIconIndexNode, SBIconIndexMutableListObserver>
{
    NSString *_displayName;
    NSString *_defaultDisplayName;
    BOOL _open;
    SBFolderIcon *_icon;
    BOOL _cancelable;
    NSMutableSet *_addedIcons;
    NSMutableSet *_removedIcons;
    NSMutableDictionary *_coalesceChangesRequests;
    NSHashTable *_nodeObservers;
    SBIconIndexMutableList *_lists;
}

+ (int)maxListCount;
- (void)setCancelable:(BOOL)fp8;
- (BOOL)isCancelable;
- (void)setIcon:(id)fp8;
- (id)icon;
- (BOOL)isOpen;
- (id)displayName;
- (void)list:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)list:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (id)nodeDescriptionWithPrefix:(id)fp8;
- (void)removeNodeObserver:(id)fp8;
- (void)addNodeObserver:(id)fp8;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (id)nodeIdentifier;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)representation;
- (id)folderType;
- (BOOL)resetWithRepresentation:(id)fp8 model:(id)fp12 leafIdentifiersAdded:(id)fp16;
- (void)_setDisplayNameFromRepresentation:(id)fp8;
- (void)stopCoalescingContentChangesForRequestID:(id)fp8 forceReload:(BOOL)fp12;
- (void)stopCoalescingContentChangesForRequestID:(id)fp8;
- (void)startCoalescingContentChangesWithRequestID:(id)fp8;
- (void)noteIcon:(id)fp8 replacedIcon:(id)fp12;
- (void)noteIconRemoved:(id)fp8;
- (void)noteIconAdded:(id)fp8;
- (BOOL)_isCoalescingContentChanges;
- (id)folderContainingIndexPath:(id)fp8 relativeIndexPath:(id *)fp12;
- (id)iconAtIndexPath:(id)fp8;
- (id)indexPathForIconWithIdentifier:(id)fp8;
- (id)indexPathForIcon:(id)fp8 includingPlaceholders:(BOOL)fp12;
- (id)indexPathForIcon:(id)fp8;
- (id)indexPathForNodeIdentifier:(id)fp8;
- (id)listContainingLeafIconWithIdentifier:(id)fp8;
- (id)listContainingIcon:(id)fp8;
- (id)visibleIcons;
- (id)folderIcons;
- (id)leafIcons;
- (id)allIcons;
- (id)iconsOfClass:(Class)fp8;
- (id)indexPathForFirstFreeSlotAvoidingFirstList:(BOOL)fp8;
- (id)performCascadingIconInsertion:(id)fp8 listIndex:(unsigned int)fp12 iconIndex:(unsigned int)fp16 addPageIfNecessary:(BOOL)fp20;
- (BOOL)canAddIcon;
- (id)addIcon:(id)fp8;
- (void)removeIconAtIndexPath:(id)fp8;
- (id)insertIcon:(id)fp8 atIndexPath:(id *)fp12;
- (id)placeIcon:(id)fp8 atIndexPath:(id *)fp12;
- (void)purgeLists;
- (unsigned int)indexOfList:(id)fp8;
- (id)listAtIndex:(unsigned int)fp8;
- (void)markIconStateClean;
- (BOOL)isIconStateDirty;
- (void)removeEmptyList:(id)fp8;
- (id)addEmptyList;
- (void)compactIconsAndLists;
- (BOOL)compactLists;
- (BOOL)isNewsstandFolder;
- (BOOL)isFull;
- (BOOL)isEmpty;
- (unsigned int)listCount;
- (id)lists;
- (void)purgeIconImages;
- (void)setIsOpen:(BOOL)fp8;
- (void)setDisplayName:(id)fp8;
- (void)dealloc;
- (id)init;
- (Class)folderSlidingViewClass;
- (Class)folderViewClass;
- (Class)listViewClass;
- (Class)listModelClass;

@end

