/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UITextFieldDelegate-Protocol.h"

@class SBFolder, SBFolderIconListView, SBFolderTextField, UIImageView, UILabel, UIView;

@interface SBFolderView : _ABAddressBookCopyLocalizedLabel <UITextFieldDelegate>
{
    SBFolder *_folder;
    UILabel *_label;
    SBFolderTextField *_textField;
    SBFolderIconListView *_iconListView;
    UIView *_backgroundView;
    BOOL _isEditing;
    UIImageView *_shadows[12];
    unsigned int _rows;
    CDAnonymousStruct6 _notchInfo;
    int _orientation;
}

- (void)_placeShadows;
- (void)_placeShadow:(int)fp8;
- (id)_shadowForPosition:(int)fp8;
- (id)_shadowImageForPosition:(int)fp8;
- (id)editTitleField;
- (void)setBackgroundAlpha:(float)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (struct _NSRange)textField:(id)fp8 willChangeSelectionFromCharacterRange:(struct _NSRange)fp12 toCharacterRange:(struct _NSRange)fp20;
- (BOOL)textFieldShouldClear:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)textFieldDidEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (void)enableShiftForFolderTextFieldAfterBeginEditing;
- (void)setIsEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)canEditTitle;
- (void)_placeBars;
- (void)_placeBackgroundView;
- (void)_placeLabelAndTextField;
- (void)setFolderName:(id)fp8;
- (float)_labelVerticalInset;
- (float)_labelHorizontalInset;
- (void)setFolder:(id)fp8;
- (void)dealloc;
- (id)iconListView;
- (void)_placeIconListView;
- (void)setScrollOffset:(id)fp8;
- (id)scrollOffset;
- (BOOL)isScrolling;
- (void)noteGrabbedIconLocation:(struct CGPoint)fp8;
- (void)noteHasGrabbedIcon:(id)fp8;
- (void)setIconListView:(id)fp8;
- (void)_createInitialIconViews;
- (struct CGRect)rectForNotchLinen;
- (Class)notchViewClass;
- (unsigned int)rows;
- (void)didDropIconView;
- (void)prepareToDropIconView:(id)fp8 targetFolderBounds:(struct CGRect *)fp12;
- (void)cleanUpAfterOrientationChange;
- (void)setRows:(unsigned int)fp8 notchInfo:(CDAnonymousStruct6)fp12 orientation:(int)fp32;
- (void)prepareToSetOrientation:(int)fp8;
- (struct CGSize)_sizeForCurrentConfiguration;
- (float)_contentHeightForCurrentConfiguration;
- (float)_contentHeightForRows:(unsigned int)fp8;
- (void)_setupFolderTitleLabel;
- (void)_setupBackgroundView;
- (void)_setupNavigationBar;
- (id)initWithFrame:(struct CGRect)fp8;

@end

