/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconView.h"

#import "SBFolderIconObserver-Protocol.h"

@class NSMutableSet, SBDownloadingProgressBar, UIImageView;

@interface SBFolderIconView : SBIconView <SBFolderIconObserver>
{
    UIImageView *_iconBackgroundView;
    UIImageView *_iconForegroundView;
    SBDownloadingProgressBar *_progressBar;
    NSMutableSet *_animatingIcons;
    unsigned int _currentScrollRow;
    BOOL _skippingGridIcons;
    float _miniIconVisibleOffset;
}

- (void)folderIcon:(id)fp8 didUpdateGridImage:(id)fp12 withSkipping:(BOOL)fp16 forContainedIconImageUpdate:(id)fp20;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)iconImageDidUpdate:(id)fp8;
- (void)prepareForRecycling;
- (void)_updateProgressBar;
- (double)grabDurationForEvent:(id)fp8;
- (BOOL)delaysUnhighlightWhenTapped;
- (BOOL)allowsTapWhileEditing;
- (id)description;
- (id)folder;
- (void)positionCloseBoxOfType:(int)fp8;
- (id)iconBackgroundView;
- (id)progressBar;
- (void)setPartialGhostly:(float)fp8 requester:(int)fp12;
- (void)setGhostly:(BOOL)fp8 requester:(int)fp12;
- (void)placeGhostlyImageView;
- (id)_iconBoundsForAccessory:(struct CGRect *)fp8;
- (struct CGRect)frameForIconOverlay;
- (void)showDropGlow:(BOOL)fp8;
- (struct CGAffineTransform)transformToMakeIconBorderExpandToSizeOfDropGlow;
- (void)positionIconImageView;
- (void)_positionMiniGrid;
- (id)iconImageSnapshot:(id)fp8;
- (id)snapshotSettings;
- (id)_folderForegroundImage;
- (id)_folderBackgroundImage;
- (struct CGRect)rectForMiniIconAtIndex:(unsigned int)fp8;
- (void)setIsOverlapping:(BOOL)fp8;
- (void)setIconScrollPosition:(int)fp8 animated:(BOOL)fp12;
- (void)setIcon:(id)fp8;
- (void)setFolderIcon:(id)fp8;
- (id)folderIcon;
- (void)dealloc;

@end

