/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBFolderNotchHighlightView, SBFolderNotchView, SBFolderView, SBSlidingViewHighlight, SBWallpaperView, UIImageView, UIView;

@interface SBFolderSlidingView : _ABAddressBookCopyLocalizedLabel
{
    int _position;
    SBFolderView *_folderView;
    int _orientation;
    CDAnonymousStruct6 _notchInfo;
    struct CGRect _wallpaperRect;
    UIView *_rasterizationView;
    UIView *_wallpaperContainerView;
    SBWallpaperView *_wallpaperView;
    SBFolderNotchView *_linenNotchView;
    SBSlidingViewHighlight *_highlightView;
    SBFolderNotchHighlightView *_notchHighlightView;
    UIImageView *_dockView;
    UIImageView *_outgoingDockView;
}

- (void)handleGestureInWallpaperContainer:(id)fp8;
- (void)setShouldRasterize:(BOOL)fp8;
- (void)setShowsHighlight:(BOOL)fp8;
- (id)_newDockViewForOrientation:(int)fp8;
- (void)_placeNotchAndHighlights;
- (struct CGRect)_rectByAddingOverlapToRect:(struct CGRect)fp8;
- (void)dealloc;
- (id)folderView;
- (void)setOrientation:(int)fp8 wallpaperRect:(struct CGRect)fp12 notchInfo:(CDAnonymousStruct6)fp28;
- (void)cleanUpAfterDockOrientationChange;
- (void)prepareToSetDockOrientation:(int)fp8;
- (id)initWithPosition:(int)fp8 folderView:(id)fp12;

@end

