/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBFolderNotchView : _ABAddressBookCopyLocalizedLabel
{
    CDAnonymousStruct6 _notchInfo;
    int _orientation;
}

+ (id)notchForNotchInfo:(CDAnonymousStruct6)fp8 orientation:(int)fp28;
+ (id)_imageForNotchInfo:(CDAnonymousStruct6)fp8 orientation:(int)fp28;
+ (id)_squareImageForNotchInfo:(CDAnonymousStruct6)fp8 orientation:(int)fp28;
+ (id)_keyForNotchInfo:(CDAnonymousStruct6)fp8 orientation:(int)fp28;
+ (id)_keyComponentForNotchInfoRect:(struct CGRect)fp8;
- (void)setNotchInfo:(CDAnonymousStruct6)fp8 orientation:(int)fp28;
- (id)initWithFrame:(struct CGRect)fp8 notchInfo:(CDAnonymousStruct6)fp24 orientation:(int)fp44;

@end

