/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBZoomView.h"

@class NSMutableArray;

@interface SBFullscreenZoomView : SBZoomView
{
    BOOL _hasImage;
    BOOL _hasFullSizedImage;
    int _corners;
    NSMutableArray *_cornerViews;
}

- (void)setRoundedCorners:(int)fp8 withCornersFrame:(struct CGRect)fp12;
- (void)dealloc;
- (id)initWithView:(id)fp8;
- (id)initWithImage:(id)fp8;
- (id)initWithSnapshotFrame:(struct CGRect)fp8 ioSurface:(void *)fp24 snapshotTransform:(struct CGAffineTransform)fp28;
- (id)initWithSnapshotFrame:(struct CGRect)fp8 image:(id)fp24 originalImageOrientation:(int)fp28 currentImageOrientation:(int)fp32 interfaceOrientation:(int)fp36 doubleHeightStatusBar:(BOOL)fp40 preventSplit:(BOOL)fp44 chrome:(id)fp48 chromeStatusBarHidden:(BOOL)fp52 needsZoomFilter:(BOOL)fp56 asyncDecodeImage:(BOOL)fp60;
- (id)_initWithFrame:(struct CGRect)fp8;

@end

