/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class CPLRUDictionary;

@interface SBGestureViewVendor : _ABAddressBookCopyLocalizedLabel
{
    CPLRUDictionary *m_cache;
}

+ (id)sharedInstance;
- (void)maskViewIfNeeded:(id)fp8 gestureType:(unsigned int)fp12 viewType:(int)fp16 contextHostViewRequester:(id)fp20 app:(id)fp24;
- (void)dealloc;
- (id)init;
- (void)clearCacheForReason:(id)fp8;
- (void)clearCacheForApp:(id)fp8 reason:(id)fp12;
- (id)viewForApp:(id)fp8 gestureType:(unsigned int)fp12 includeStatusBar:(BOOL)fp16 decodeImage:(BOOL)fp20;
- (id)viewForApp:(id)fp8 gestureType:(unsigned int)fp12 includeStatusBar:(BOOL)fp16;

@end

