/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray;

@interface SBGestureRecognizer : _ABAddressBookCopyLocalizedLabel
{
    unsigned int m_types;
    int m_state;
    id m_handler;
    unsigned int m_activeTouchesCount;
    CDAnonymousStruct7 m_activeTouches[30];
    unsigned int m_strikes;
    unsigned int m_templateMatches;
    NSMutableArray *m_touchTemplates;
    BOOL m_includedInGestureRecognitionIsPossibleTest;
    BOOL m_sendsTouchesCancelledToApplication;
    id m_canBeginCondition;
}

- (void)setCanBeginCondition:(id)fp(null);
- (id)canBeginCondition;
- (void)setSendsTouchesCancelledToApplication:(BOOL)fp8;
- (BOOL)sendsTouchesCancelledToApplication;
- (void)setIncludedInGestureRecognitionIsPossibleTest:(BOOL)fp8;
- (BOOL)includedInGestureRecognitionIsPossibleTest;
- (void)setHandler:(id)fp(null);
- (id)handler;
- (int)state;
- (void)setTypes:(unsigned int)fp8;
- (unsigned int)types;
- (void)touchesCancelled:(struct __SBGestureContext *)fp8;
- (void)touchesEnded:(struct __SBGestureContext *)fp8;
- (void)touchesMoved:(struct __SBGestureContext *)fp8;
- (void)touchesBegan:(struct __SBGestureContext *)fp8;
- (void)setState:(int)fp8;
- (int)templateMatch;
- (void)addTouchTemplate:(id)fp8;
- (void)sendTouchesCancelledToApplicationIfNeeded;
- (void)reset;
- (BOOL)shouldReceiveTouches;
- (void)dealloc;
- (id)init;

@end

