/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, UIView;

@interface SBGestureViewCacheNode : _ABAddressBookCopyLocalizedLabel
{
    UIView *m_view;
    int m_viewType;
    NSString *m_contextHostViewRequester;
    int m_orientation;
    NSString *m_bundleIdentifier;
}

+ (id)node;
- (void)setBundleIdentifier:(id)fp8;
- (id)bundleIdentifier;
- (void)setOrientation:(int)fp8;
- (int)orientation;
- (void)setContextHostViewRequester:(id)fp8;
- (id)contextHostViewRequester;
- (void)setViewType:(int)fp8;
- (int)viewType;
- (void)setView:(id)fp8;
- (id)view;
- (void)dealloc;

@end

