/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIGradient;

@interface SBGradientLabel : _ABAddressBookCopyLocalizedLabel
{
    UIGradient *_gradient;
}

- (id)gradient;
- (void)setGradient:(id)fp8;
- (void)drawTextInRect:(struct CGRect)fp8;
- (void)dealloc;

@end

