/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBHandMotionExtractor : _ABAddressBookCopyLocalizedLabel
{
    CDAnonymousStruct9 _pixelDeltas;
    CDAnonymousStruct9 _smoothedDeltas;
    CDAnonymousStruct9 _allPixelDeltas;
    float _averageTranslation;
    float _farthestFingerSeparation;
    struct CGPoint _movementVelocityInPointsPerSecond;
}

- (struct CGPoint)movementVelocityInPointsPerSecond;
- (float)farthestFingerSeparation;
- (float)averageTranslation;
- (CDAnonymousStruct9)averageVelocities;
- (CDAnonymousStruct9)allPixelDeltas;
- (CDAnonymousStruct9)pixelDeltas;
- (void)extractHandMotionForActiveTouches:(CDAnonymousStruct7 *)fp8 count:(unsigned int)fp12 centroid:(struct CGPoint)fp16;
- (void)clear;

@end

