/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBHarmonicOscillator : _ABAddressBookCopyLocalizedLabel
{
    float A;
    float Z;
    float k;
    float dk;
    float mink;
    float m;
    float dm;
    float minm;
    float psi_n;
    float psi_d;
    float zeta;
}

- (void)setMinimumMass:(float)fp8;
- (float)minimumMass;
- (void)setMassDecay:(float)fp8;
- (float)massDecay;
- (float)mass;
- (void)setMinimumSpringStrength:(float)fp8;
- (float)minimumSpringStrength;
- (void)setSpringDecay:(float)fp8;
- (float)springDecay;
- (void)setSpringStrength:(float)fp8;
- (float)springStrength;
- (void)setEndingAmplitude:(float)fp8;
- (float)endingAmplitude;
- (void)setStartingAmplitude:(float)fp8;
- (float)startingAmplitude;
- (float)amplitudeForElapsedTime:(double)fp8;
- (void)updateParameters;
- (void)setMass:(float)fp8;
- (void)setSpringConstant:(float)fp8;
- (id)init;

@end

