/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSDictionary, NSMutableSet, SBHostWrapperView;

@interface SBHostRequesterInfo : _ABAddressBookCopyLocalizedLabel
{
    SBHostWrapperView *_wrapperView;
    NSMutableSet *_hiddenContexts;
    NSDictionary *_realContextHostViewChangedProperties;
    NSDictionary *_realContextHostViewOriginalProperties;
}

- (void)setRealContextHostViewOriginalProperties:(id)fp8;
- (id)realContextHostViewOriginalProperties;
- (void)setRealContextHostViewChangedProperties:(id)fp8;
- (id)realContextHostViewChangedProperties;
- (id)hiddenContexts;
- (id)wrapperView;
- (void)dealloc;
- (id)init;

@end

