/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBUIActiveOrientationObserver-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegatePrivate-Protocol.h"

@class UIPopoverController, UIWindow;

@interface SBHomeCentricPopoverController : _ABAddressBookCopyLocalizedLabel <UIPopoverControllerDelegate, UIPopoverControllerDelegatePrivate, SBUIActiveOrientationObserver>
{
    UIWindow *_window;
    UIPopoverController *_popover;
    id <SBHomeCentricPopoverControllerDelegate> _delegate;
    BOOL _presented;
    int _presentedOrientation;
    unsigned int _orientationChangeCount;
    BOOL _shouldSendDidPresent;
    BOOL _shouldSendDidDismiss;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)popoverController:(id)fp8 animationCompleted:(int)fp12;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (BOOL)popoverControllerShouldDismissPopover:(id)fp8;
- (void)activeInterfaceOrientationDidChangeToOrientation:(int)fp8 willAnimateWithDuration:(double)fp12 fromOrientation:(int)fp20;
- (void)activeInterfaceOrientationWillChangeToOrientation:(int)fp8;
- (void)_commonDidDismiss;
- (void)_hidePopoverWindow;
- (void)dismissPopoverAnimated:(BOOL)fp8;
- (void)setDesiredContentSize:(struct CGSize)fp8 animated:(BOOL)fp16;
- (BOOL)presentPopoverView:(id)fp8 withDesiredContentSize:(struct CGSize)fp12 animated:(BOOL)fp20;
- (BOOL)isVisible;
- (BOOL)ignoresKeyboardAvoidance;
- (void)setIgnoresKeyboardAvoidance:(BOOL)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithUIPopoverControllerClass:(Class)fp8;

@end

