/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBHostView <NSObject>
- (void)setBackgroundColorWhileNotHosting:(id)fp8;
- (id)backgroundColorWhileNotHosting;
- (void)setBackgroundColorWhileHosting:(id)fp8;
- (id)backgroundColorWhileHosting;
@end

