/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBHostView-Protocol.h"

@class SBAppContextHostManager, UIColor;

@interface SBHostWrapperView : _ABAddressBookCopyLocalizedLabel <SBHostView>
{
    UIColor *_backgroundColorWhileNotHosting;
    UIColor *_backgroundColorWhileHosting;
    SBAppContextHostManager *_manager;
}

- (id)backgroundColorWhileNotHosting;
- (id)backgroundColorWhileHosting;
- (void)setManager:(id)fp8;
- (id)manager;
- (id)window;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)description;
- (void)willRemoveSubview:(id)fp8;
- (void)didAddSubview:(id)fp8;
- (void)_toggleBackgroundColorIfNecessary;
- (void)_hostingStatusChanged;
- (BOOL)_isReallyHosting;
- (void)setBackgroundColorWhileNotHosting:(id)fp8;
- (void)setBackgroundColorWhileHosting:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 contextHostManager:(id)fp24;

@end

