/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView, UILabel;

@interface SBHUDView : _ABAddressBookCopyLocalizedLabel
{
    int _level;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_imageView;
    BOOL _showsProgress;
    float _progress;
}

+ (float)progressIndicatorStep;
+ (int)numberOfProgressIndicatorSteps;
- (float)progress;
- (BOOL)showsProgress;
- (void)setLevel:(int)fp8;
- (int)level;
- (void)drawRect:(struct CGRect)fp8;
- (void)drawBlockForValue:(float)fp8 point:(struct CGPoint)fp12;
- (void)setProgress:(float)fp8;
- (void)setShowsProgress:(BOOL)fp8;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setSubtitle:(id)fp8;
- (id)subtitle;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)layoutSubviews;
- (BOOL)displaysLabel;
- (void)dealloc;
- (id)initWithHUDViewLevel:(int)fp8;

@end

