/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBIcon, UIView;

@interface SBIconRotationContainer : _ABAddressBookCopyLocalizedLabel
{
    UIView *_startSnapshot;
    UIView *_endSnapshot;
    SBIcon *_icon;
    BOOL _shouldCrossfade;
    int _toOrientation;
    int _fromOrientation;
    unsigned int _startIndex;
    unsigned int _endIndex;
}

- (void)setIcon:(id)fp8;
- (id)icon;
- (id)newSnapshot:(id)fp8 includingShadows:(BOOL)fp12;
- (void)crossfadeWithDuration:(double)fp8 inIconList:(id)fp16;
- (void)prepareToCrossfade;
- (void)setOrigin:(struct CGPoint)fp8;
- (void)setStartIcon:(id)fp8 endIcon:(id)fp12 inIconList:(id)fp16 fromOrientation:(int)fp20 toOrientation:(int)fp24;
- (void)dealloc;

@end

