/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBIconIndexNode <NSObject>
- (id)nodeDescriptionWithPrefix:(id)fp8;
- (void)removeNodeObserver:(id)fp8;
- (void)addNodeObserver:(id)fp8;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (id)nodeIdentifier;
@end

