/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBIconAccessoryImage;

@interface SBIconAccessoryImageView : _ABAddressBookCopyLocalizedLabel
{
    SBIconAccessoryImage *_baseImage;
    float _brightness;
    BOOL _brightnessHasBeenSet;
    BOOL _coalescingChanges;
    BOOL _needsUpdate;
}

- (id)description;
- (void)_updateImage;
- (void)setImage:(id)fp8 brightness:(float)fp12;
- (void)setBrightness:(float)fp8;
- (float)brightness;
- (void)setImage:(id)fp8;
- (id)image;
- (void)dealloc;

@end

