/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBIconIndexMutableListObserver <NSObject>
- (void)list:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)list:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
@end

