/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSDictionary, NSMutableDictionary, NSSet, SBNewsstandIcon, SBPrintStatusIcon, SBRootFolder;

@interface SBIconModel : _ABAddressBookCopyLocalizedLabel
{
    NSDictionary *_desiredIconState;
    NSSet *_desiredIconStateFlattened;
    NSMutableDictionary *_leafIconsByIdentifier;
    NSSet *_hiddenIconTags;
    NSSet *_visibleIconTags;
    BOOL _tagsHaveBeenSet;
    SBRootFolder *_rootFolder;
    SBNewsstandIcon *_newsstandIcon;
    SBPrintStatusIcon *_printStatusIcon;
    id <SBIconModelStore> _store;
    id <SBIconModelDelegate> _delegate;
    BOOL _allowsSaving;
}

+ (id)modernIconStateForState:(id)fp8;
+ (id)_modernIconListsForLists:(id)fp8;
+ (id)_modernIconListForList:(id)fp8;
+ (id)_modernIconCellForCell:(id)fp8;
+ (id)_migrateLeafIdentifierIfNecessary:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAllowsSaving:(BOOL)fp8;
- (BOOL)allowsSaving;
- (void)setLeafIconsByIdentifier:(id)fp8;
- (id)leafIconsByIdentifier;
- (BOOL)importState:(id)fp8;
- (id)_iTunesDictionaryForDownloadingIcon:(id)fp8;
- (id)_iTunesDictionaryForLeafIcon:(id)fp8;
- (id)_iTunesDictionaryForLeafIdentifier:(id)fp8;
- (id)_iTunesIconCellForCell:(id)fp8 preApex:(BOOL)fp12 forPending:(BOOL)fp16;
- (id)_iTunesIconListForList:(id)fp8 preApex:(BOOL)fp12 forPending:(BOOL)fp16;
- (id)_iTunesIconListsForLists:(id)fp8 preApex:(BOOL)fp12 forPending:(BOOL)fp16;
- (id)exportFlattenedState:(BOOL)fp8 includeMissingIcons:(BOOL)fp12;
- (id)exportPendingState:(BOOL)fp8 includeMissingIcons:(BOOL)fp12;
- (id)exportState:(BOOL)fp8;
- (id)forecastedLayoutForIconState:(id)fp8 includeMissingIcons:(BOOL)fp12;
- (void)layout;
- (id)_flattenIconState:(id)fp8;
- (id)_newsstandIconIdentifiersFromIconState:(id)fp8;
- (id)newsstandFolderFromIconState:(id)fp8;
- (void)_flattenIconListState:(id)fp8 intoArray:(id)fp12;
- (void)_replaceAppIconsWithDownloadingIcons:(id)fp8;
- (void)_replaceAppIconsWithDownloadingIcons;
- (void)saveIconState;
- (void)_saveDesiredIconState;
- (void)deleteIconState;
- (void)_addNewIconToDesignatedLocation:(id)fp8;
- (id)indexPathForNewIcon:(id)fp8 isDesignatedLocation:(char *)fp12 replaceExistingIconAtIndexPath:(id *)fp16;
- (id)_indexPathForFirstFreeNewsstandSlot;
- (void)clearDesiredIconStateIfPossible;
- (void)clearDesiredIconState;
- (BOOL)hasDesiredIconState;
- (id)_indexPathForIdentifier:(id)fp8 inListsRepresentation:(id)fp12;
- (id)_indexPathForIdentifier:(id)fp8 inListRepresentation:(id)fp12;
- (id)indexPathForIconInPlatformState:(id)fp8;
- (void)removeIconForIdentifier:(id)fp8;
- (void)removeIcon:(id)fp8;
- (void)addIcon:(id)fp8;
- (void)_createIconLists;
- (id)firstPageLeafIdentifiers;
- (id)_modernPlatformState;
- (id)_iconState;
- (id)iconState;
- (id)applicationIconForDisplayIdentifier:(id)fp8;
- (id)leafIconForIdentifier:(id)fp8;
- (id)expectedIconForDisplayIdentifier:(id)fp8;
- (id)_applicationIcons;
- (id)leafIcons;
- (id)visibleIconIdentifiers;
- (void)loadAllIcons;
- (void)addNewsstandIcon;
- (void)addIconForApplication:(id)fp8;
- (id)addBookmarkIconForWebClip:(id)fp8;
- (id)leafIconForWebClipIdentifier:(id)fp8;
- (id)leafIconForWebClip:(id)fp8;
- (id)downloadingIconForIdentifier:(id)fp8;
- (void)removeApplicationIconForDownloadingIcon:(id)fp8;
- (id)addDownloadingIconForIdentifier:(id)fp8;
- (id)addDownloadingIconForDownload:(id)fp8;
- (BOOL)isIconVisible:(id)fp8;
- (void)setVisibilityOfIconsWithVisibleTags:(id)fp8 hiddenTags:(id)fp12;
- (void)_postIconVisibilityChangedNotificationShowing:(id)fp8 hiding:(id)fp12;
- (void)localeChanged;
- (id)newsstandFolder;
- (id)newsstandIcon;
- (id)printStatusIcon;
- (id)rootFolder;
- (void)dealloc;
- (id)initWithStore:(id)fp8;

@end

