/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconAccessoryImage.h"

@interface SBIconBadgeImage : SBIconAccessoryImage
{
}

+ (id)creationBlockForText:(SEL)fp4;
+ (float)_badgeLabelVerticalOffset;
- (struct CGRect)accessoryFrameForIconBounds:(struct CGRect)fp8;
- (id)countedMapKey;
- (void)dealloc;
- (id)initWithCGImage:(struct CGImage *)fp8 scale:(float)fp12 orientation:(int)fp16 text:(id)fp20;

@end

