/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBIconViewMapDelegate <NSObject>
- (Class)viewMap:(id)fp8 iconViewClassForIcon:(id)fp12;
- (int)viewMap:(id)fp8 locationForIcon:(id)fp12;
- (unsigned int)viewMap:(id)fp8 maxRecycledIconViewsOfClass:(Class)fp12;
@end

