/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconObserver-Protocol.h"

@class NSTimer, SBIcon, SBIconAccessoryImageView, SBIconImageContainerView, SBIconImageView, SBIconLabelImageView, UIImage, UIImageView, UIView;

@interface SBIconView : _ABAddressBookCopyLocalizedLabel <SBIconObserver>
{
    SBIcon *_icon;
    id <SBIconViewDelegate> _delegate;
    id <SBIconViewObserver> _observer;
    SBIconImageContainerView *_iconImageContainer;
    SBIconImageView *_iconImageView;
    UIImageView *_iconDarkeningOverlay;
    UIImageView *_ghostlyImageView;
    UIImageView *_reflection;
    UIImageView *_shadow;
    SBIconAccessoryImageView *_accessoryView;
    SBIconLabelImageView *_labelView;
    BOOL _labelHidden;
    UIView *_closeBox;
    int _closeBoxType;
    UIImageView *_dropGlow;
    unsigned int _drawsLabel:1;
    unsigned int _isGrabbed:1;
    unsigned int _isOverlapping:1;
    unsigned int _refusesRecipientStatus:1;
    unsigned int _highlighted:1;
    unsigned int _launchDisabled:1;
    unsigned int _isJittering:1;
    unsigned int _allowJitter:1;
    unsigned int _touchDownInIcon:1;
    unsigned int _hideShadow:1;
    NSTimer *_delayedUnhighlightTimer;
    unsigned int _ghostlyRequesters;
    int _iconLocation;
    float _iconImageAlpha;
    float _iconImageBrightness;
    float _iconLabelAlpha;
    float _accessoryAlpha;
    struct CGPoint _unjitterPoint;
    struct CGPoint _grabPoint;
    NSTimer *_longPressTimer;
    unsigned int _ghostlyTag;
    UIImage *_ghostlyImage;
    BOOL _ghostlyPending;
}

+ (id)_jitterTransformAnimation;
+ (id)_jitterPositionAnimation;
+ (id)_labelImageParametersForIcon:(id)fp8 location:(int)fp12;
+ (Class)_labelImageParametersClassForIcon:(id)fp8 location:(int)fp12;
+ (struct CGSize)_maxLabelSize;
+ (struct CGSize)defaultIconImageSize;
+ (struct CGSize)defaultIconSize;
- (void)setObserver:(id)fp8;
- (id)observer;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)iconLaunchEnabledDidChange:(id)fp8;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)iconImageDidUpdate:(id)fp8;
- (struct CGRect)defaultFrameForProgressBar;
- (void)prepareForRecycling;
- (id)createShadowImageView;
- (int)_delegateCloseBoxType;
- (BOOL)_delegateTapAllowed;
- (void)_delegateTouchEnded:(BOOL)fp8;
- (BOOL)_delegatePositionIsEditable;
- (void)_updateShadowFrame;
- (void)_updateShadowFrameForShadow:(id)fp8;
- (void)setShadowsHidden:(BOOL)fp8;
- (struct UIEdgeInsets)snapshotEdgeInsets;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)closeBoxTapped;
- (BOOL)isShowingCloseBox;
- (void)setShowsCloseBox:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setShowsCloseBox:(BOOL)fp8;
- (id)_newCloseBoxOfType:(int)fp8;
- (void)positionCloseBoxOfType:(int)fp8;
- (void)hideCloseBoxAnimationDidStop:(id)fp8 didFinish:(id)fp12 closeBox:(id)fp16;
- (void)setTouchDownInIcon:(BOOL)fp8;
- (BOOL)isTouchDownInIcon;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)cancelLongPressTimer;
- (void)longPressTimerFired;
- (int)ghostlyRequesters;
- (BOOL)isGhostly;
- (void)removeGhostlyImageView;
- (void)setPartialGhostly:(float)fp8 requester:(int)fp12;
- (void)setGhostly:(BOOL)fp8 requester:(int)fp12;
- (void)prepareGhostlyImageView;
- (void)prepareGhostlyImage;
- (void)prepareGhostlyImageIfNeeded;
- (id)_genGhostlyImage:(id)fp8;
- (void)placeGhostlyImageView;
- (BOOL)isShowingDropGlow;
- (id)dropGlow;
- (void)removeDropGlow;
- (void)showDropGlow:(BOOL)fp8;
- (void)prepareDropGlow;
- (struct CGAffineTransform)transformToMakeDropGlowShrinkToIconSize;
- (void)setIsOverlapping:(BOOL)fp8;
- (BOOL)isGrabbed;
- (void)setIsGrabbed:(BOOL)fp8;
- (double)grabDurationForEvent:(id)fp8;
- (BOOL)canReceiveGrabbedIcon:(id)fp8;
- (void)setRefusesRecipientStatus:(BOOL)fp8;
- (void)setIconPosition:(struct CGPoint)fp8;
- (void)removeAllIconAnimations;
- (BOOL)allowJitter;
- (void)setAllowJitter:(BOOL)fp8;
- (void)setIsJittering:(BOOL)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (float)_reflectionImageOffset;
- (BOOL)showsReflection;
- (void)updateReflection;
- (void)_updateShadow;
- (id)_shadowImage;
- (BOOL)isInDock;
- (void)_delayedUnhighlight;
- (void)setHighlighted:(BOOL)fp8 delayUnhighlight:(BOOL)fp12;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)isHighlighted;
- (BOOL)delaysUnhighlightWhenTapped;
- (BOOL)allowsTapWhileEditing;
- (void)_updateIconBrightness;
- (void)updateIconOverlayView;
- (void)placeIconOverlayView;
- (struct CGRect)frameForIconOverlay;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)_automationID;
- (void)updateBadge;
- (void)_updateAccessoryPosition;
- (id)_superviewForAccessoryView;
- (struct CGRect)_frameForAccessoryView;
- (id)_iconBoundsForAccessory:(struct CGRect *)fp8;
- (struct UIEdgeInsets)_viewInsetsForAccessoryType:(int)fp8;
- (void)updateLabel;
- (void)positionLabel;
- (void)setLabelHidden:(BOOL)fp8;
- (id)iconImageView;
- (void)setIconLabelAlpha:(float)fp8;
- (void)setIconImageAlpha:(float)fp8;
- (id)reflectedIconWithBrightness:(float)fp8;
- (id)iconImageSnapshot:(id)fp8;
- (id)snapshotSettings;
- (void)setDisplayedIconImage:(id)fp8;
- (void)applyIconImageTransform:(struct CATransform3D)fp8 duration:(float)fp72 delay:(float)fp76;
- (void)positionIconImageView;
- (void)setLocation:(int)fp8;
- (int)location;
- (void)setIcon:(id)fp8;
- (id)icon;
- (void)dealloc;
- (id)initWithDefaultSize;

@end

