/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface SBIconLabelImageParameters : _ABAddressBookCopyLocalizedLabel <NSCopying>
{
    NSString *_text;
    BOOL _containsNonLatinLikeCharacters;
    BOOL _containsEmoji;
    BOOL _canEllipsize;
    struct CGSize _maxSize;
}

+ (id)parametersWithText:(id)fp8 canEllipsize:(BOOL)fp12 maxSize:(struct CGSize)fp16;
- (struct CGSize)shadowOffset;
- (float)shadowBlur;
- (id)shadowColor;
- (id)textColor;
- (id)font;
- (BOOL)colorspaceIsGrayscale;
- (struct CGSize)maxSize;
- (BOOL)canEllipsize;
- (id)text;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (id)initWithText:(id)fp8 canEllipsize:(BOOL)fp12 maxSize:(struct CGSize)fp16;

@end

