/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "NSFastEnumeration-Protocol.h"
#import "SBIconIndexNodeObserver-Protocol.h"

@class NSMapTable, NSMutableArray;

@interface SBIconIndexMutableList : _ABAddressBookCopyLocalizedLabel <SBIconIndexNodeObserver, NSFastEnumeration>
{
    NSMutableArray *_nodes;
    NSMapTable *_index;
    id <SBIconIndexMutableListObserver> _observer;
}

- (void)setObserver:(id)fp8;
- (id)observer;
- (id)indexDescriptionWithPrefix:(id)fp8;
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct8 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (void)node:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)node:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (void)removeAllNodes;
- (void)removeNodeAtIndex:(unsigned int)fp8;
- (void)removeNode:(id)fp8;
- (void)replaceNodeAtIndex:(unsigned int)fp8 withNode:(id)fp12;
- (void)addNode:(id)fp8;
- (void)insertNode:(id)fp8 atIndex:(unsigned int)fp12;
- (id)nodeAtIndex:(unsigned int)fp8;
- (BOOL)containsNode:(id)fp8;
- (unsigned int)indexOfNode:(id)fp8;
- (unsigned int)count;
- (id)nodes;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (void)dealloc;
- (id)init;

@end

