/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSArray, SBFolderIcon;

@interface SBIconsIntoFolderAnimationContext : _ABAddressBookCopyLocalizedLabel
{
    SBFolderIcon *_folderIcon;
    NSArray *_iconSnapshots;
    NSArray *_miniSnapshots;
    NSArray *_addedIcons;
    BOOL _openFolderOnFinish;
    id _completeBlock;
}

- (void)setCompleteBlock:(id)fp(null);
- (id)completeBlock;
- (void)setOpenFolderOnFinish:(BOOL)fp8;
- (BOOL)openFolderOnFinish;
- (void)setMiniSnapshots:(id)fp8;
- (id)miniSnapshots;
- (void)setIconSnapshots:(id)fp8;
- (id)iconSnapshots;
- (void)setAddedIcons:(id)fp8;
- (id)addedIcons;
- (void)setFolderIcon:(id)fp8;
- (id)folderIcon;
- (void)dealloc;

@end

