/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBIconListPageControl : _ABAddressBookCopyLocalizedLabel
{
    id _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setFrame:(struct CGRect)fp8;
- (id)_pageIndicatorCurrentImageForPage:(int)fp8;
- (id)_pageIndicatorImageForPage:(int)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;

@end

