/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, NSMutableSet, SBIcon, SBIconListModel, SBIconViewMap, UIView;

@interface SBIconListView : _ABAddressBookCopyLocalizedLabel
{
    SBIconListModel *_model;
    SBIconViewMap *_viewMap;
    int _orientation;
    SBIcon *_bouncedIcon;
    NSMutableArray *_removedIcons;
    NSMutableArray *_iconContainerMatrix;
    unsigned int _scattered:1;
    unsigned int _needsLayout:1;
    unsigned int _rotating:1;
    UIView *_fadeView;
    BOOL _iconsAreElsewhere;
    BOOL _recyclesIconViewsWhenNotShowing;
    NSMutableSet *_notShownIconViews;
    BOOL _showingCloseBoxes;
}

+ (unsigned int)maxIcons;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)fp8;
+ (unsigned int)maxVisibleIconRowsInterfaceOrientation:(int)fp8;
+ (unsigned int)iconRowsForInterfaceOrientation:(int)fp8;
- (void)cleanupAfterRotation;
- (void)performRotationWithDuration:(double)fp8;
- (void)prepareToRotateToInterfaceOrientation:(int)fp8;
- (Class)iconRotationContainerClass;
- (id)rotationIconContainers;
- (unsigned int)_rotationReferenceRow;
- (unsigned int)_postRotationFirstVisibleRow;
- (unsigned int)_preRotationFirstVisibleRow;
- (unsigned int)rowAtPoint:(struct CGPoint)fp8;
- (unsigned int)columnAtPoint:(struct CGPoint)fp8;
- (struct CGPoint)originForIconAtX:(unsigned int)fp8 Y:(unsigned int)fp12;
- (float)verticalIconPadding;
- (float)horizontalIconPadding;
- (float)horizontalBumpForColumn:(unsigned int)fp8;
- (float)sideIconInset;
- (float)bottomIconInset;
- (float)topIconInset;
- (id)bouncedIcon;
- (void)setBouncedIcon:(id)fp8;
- (BOOL)isDock;
- (void)makeIconViewsPerformBlock:(id)fp(null);
- (void)makeIconsPerformBlock:(id)fp(null);
- (void)makeIconViewsPerformSelector:(SEL)fp8;
- (void)makeIconsPerformSelector:(SEL)fp8;
- (void)hideCloseBoxes;
- (void)showCloseBoxes;
- (void)startJittering;
- (void)stopJittering;
- (void)showIconImagesFromColumn:(int)fp8 toColumn:(int)fp12 totalColumns:(int)fp16 visibleIconsJitter:(BOOL)fp20;
- (id)iconAtPoint:(struct CGPoint)fp8 index:(unsigned int *)fp16 proposedOrder:(int *)fp20 grabbedIcon:(id)fp24;
- (id)iconAtPoint:(struct CGPoint)fp8 index:(unsigned int *)fp16;
- (float)layoutIconsIfNeeded:(float)fp8 domino:(BOOL)fp12;
- (struct CATransform3D)_transformForIconAtIndex:(unsigned int)fp8 inOrientation:(int)fp12;
- (void)layoutIconsNow;
- (void)setIconsNeedLayout;
- (BOOL)recyclesIconViewsWhenNotShowing;
- (void)setRecyclesIconViewsWhenNotShowing:(BOOL)fp8;
- (BOOL)iconsAreElsewhere;
- (void)setIconsAreElsewhere:(BOOL)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (struct CGPoint)originForIcon:(id)fp8;
- (struct CGPoint)originForIconAtIndex:(int)fp8;
- (struct CGSize)defaultIconSize;
- (void)removeAllIconAnimations;
- (void)unscatterWithDuration:(double)fp8 delay:(double)fp16;
- (void)unscatterAnimationDidStop;
- (void)scatterWithDuration:(double)fp8 delay:(double)fp16;
- (void)setAlphaForAllIcons:(float)fp8;
- (BOOL)isScattered;
- (void)removeIcon:(id)fp8;
- (void)removeIconAtIndex:(unsigned int)fp8;
- (id)removedIcons;
- (id)insertIcon:(id)fp8 atIndex:(unsigned int)fp12 moveNow:(BOOL)fp16;
- (id)insertIcon:(id)fp8 atIndex:(unsigned int)fp12 moveNow:(BOOL)fp16 pop:(BOOL)fp20;
- (id)placeIcon:(id)fp8 atIndex:(unsigned int)fp12 moveNow:(BOOL)fp16 pop:(BOOL)fp20;
- (void)_layoutIcon:(id)fp8 atIndex:(unsigned int)fp12 moveNow:(BOOL)fp16 pop:(BOOL)fp20;
- (void)_noteNewIconInModel:(id)fp8;
- (void)_popIconView:(id)fp8;
- (void)showIconAnimationDidStop:(id)fp8 didFinish:(id)fp12 iconView:(id)fp16;
- (unsigned int)firstFreeSlotOrLastSlotIndexForType:(int)fp8;
- (unsigned int)firstFreeSlotOrLastSlotIndex;
- (unsigned int)firstFreeSlotIndexForType:(int)fp8;
- (unsigned int)firstFreeSlotIndex;
- (BOOL)isFull;
- (BOOL)isEmpty;
- (id)visibleIcons;
- (id)icons;
- (BOOL)compactIcons:(BOOL)fp8;
- (unsigned int)rowForIcon:(id)fp8;
- (void)getX:(unsigned int *)fp8 Y:(unsigned int *)fp12 forIndex:(unsigned int)fp16 forOrientation:(int)fp20;
- (unsigned int)indexForX:(unsigned int)fp8 Y:(unsigned int)fp12 forOrientation:(int)fp16;
- (void)setOrientation:(int)fp8;
- (unsigned int)iconsInRowForSpacingCalculation;
- (unsigned int)iconColumnsForCurrentOrientation;
- (unsigned int)iconRowsForCurrentOrientation;
- (id)viewMap;
- (id)model;
- (void)setModel:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 viewMap:(id)fp24;
- (Class)modelClass;

@end

