/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBRelaunchAppWorkspaceTransaction.h"

@class SSKeybagRequest;

@interface SBKeybagNonsenseWorkspaceTransaction : SBRelaunchAppWorkspaceTransaction
{
    SSKeybagRequest *_keybagRequest;
}

- (void)_handleAppRelaunch:(id)fp8;
- (void)_interruptWithReason:(int)fp8;
- (BOOL)_canBeInterrupted;
- (void)_completeKeybagRefetchForApp:(id)fp8 relaunch:(BOOL)fp12;
- (void)_transactionComplete;
- (void)_commit;
- (id)_setupAnimationForApp:(id)fp8;
- (BOOL)_shouldBeWatchdogged:(id *)fp8;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 application:(id)fp16;

@end

