/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIcon.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface SBLeafIcon : SBIcon <NSCopying>
{
    NSString *_leafIdentifier;
}

- (id)nodeIdentifier;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;
- (id)description;
- (BOOL)matchesRepresentation:(id)fp8;
- (id)representation;
- (id)leafIdentifier;
- (void)dealloc;
- (id)initWithLeafIdentifier:(id)fp8;

@end

