/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray;

@interface SBLinenView : _ABAddressBookCopyLocalizedLabel
{
    int _type;
    NSMutableArray *_strips;
}

+ (float)_vOffsetOfTopForType:(int)fp8;
+ (struct CGRect)_scaledRectForIndex:(unsigned int)fp8 ofImage:(id)fp12;
+ (id)_imageKeyForIndex:(unsigned int)fp8;
+ (id)_cachedImageForIndex:(unsigned int)fp8;
+ (unsigned int)_maximumNumberOfStrips;
+ (void)_generateStripsIfNecessary;
+ (id)squareImageForBounds:(struct CGRect)fp8;
+ (float)naturalWidth;
+ (void)load;
- (int)type;
- (float)_vOffsetOfTop;
- (void)setType:(int)fp8;
- (void)layoutSubviews;
- (void)_layoutForBounds:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

