/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBLineFragment : _ABAddressBookCopyLocalizedLabel
{
    unsigned int _index;
    float _lineWidth;
    struct _NSRange _range;
}

+ (id)fragmentWithIndex:(unsigned int)fp8 length:(unsigned int)fp12 lineWidth:(float)fp16;
- (void)setLineWidth:(float)fp8;
- (float)lineWidth;
- (void)setRange:(struct _NSRange)fp8;
- (struct _NSRange)range;
- (void)setIndex:(unsigned int)fp8;
- (unsigned int)index;
- (id)description;

@end

