/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBBulletinFadeOverlayOwner-Protocol.h"

@class SBBulletinLinenFadeView, UIView;

@interface SBLinenFadeContainer : _ABAddressBookCopyLocalizedLabel <SBBulletinFadeOverlayOwner>
{
    UIView *_linenView;
    SBBulletinLinenFadeView *_fadeView;
}

- (void)setLinenGradientAlpha:(float)fp8;
- (void)setRasterizesFadeOverlay:(BOOL)fp8;
- (void)layoutSubviews;
- (void)setShouldShowFadeOverlay:(BOOL)fp8;
- (void)dealloc;
- (id)initWithLinenView:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

