/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBLowPowerAlertItem : _ABAddressBookCopyLocalizedLabel
{
    unsigned int _talkLevel;
}

+ (void)setBatteryLevel:(unsigned int)fp8;
+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned int)fp8;
+ (unsigned int)_thresholdForLevel:(unsigned int)fp8;
+ (void)initialize;
+ (void)saveLowBatteryLogWithCapacity:(int)fp8 voltage:(int)fp12;
+ (id)systemVersionDescription;
- (BOOL)undimsScreen;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)shouldShowInLockScreen;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)willPresentAlertView:(id)fp8;
- (id)initWithLevel:(unsigned int)fp8;
- (id)init;

@end

