/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBLockScreenAudioRoutesAlertItem : _ABAddressBookCopyLocalizedLabel
{
}

- (void)audioRoutingPicker:(id)fp8 didSelectRouteAtIndex:(int)fp12;
- (void)performUnlockAction;
- (BOOL)allowAutoUnlock;
- (BOOL)togglesMediaControls;
- (BOOL)shouldShowInLockScreen;
- (void)willRelockForButtonPress:(BOOL)fp8;
- (BOOL)allowMenuButtonDismissal;
- (id)alertSheet;
- (Class)alertSheetClass;

@end

