/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, SBDismissOnlyAlertItem;

@interface SBLockdownManager : _ABAddressBookCopyLocalizedLabel
{
    int _state;
    BOOL _settingUpActivationState;
    BOOL _isBricked;
    BOOL _isDeveloperDevice;
    BOOL _hasShownMismatchedSIM;
    SBDismissOnlyAlertItem *_activatingAlertItem;
    NSString *_unqiueDeviceIdentifier;
}

+ (id)sharedInstance;
- (id)valueForDomain:(id)fp8 key:(id)fp12;
- (void)dealloc;
- (id)uniqueDeviceIdentifier;
- (int)lockdownState;
- (BOOL)isDeveloperDevice;
- (BOOL)brickedDevice;
- (void)_setupActivationState;
- (void)_serviceAvailabilityChanged:(id)fp8;
- (void)_developerDeviceStateChanged;
- (void)_activationFailed;
- (void)_resetActivationState;
- (void)_postAlertsIfNeeded;
- (BOOL)_shouldShowTelephonyAlerts;
- (void)_setCurrentAlertItem:(id)fp8;
- (BOOL)_isRegisteredToNetwork;
- (void)_setHasEverRegistered:(BOOL)fp8;
- (BOOL)_hasEverRegistered;
- (id)init;

@end

