/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class MPAudioDeviceController, NSDictionary, NSTimer;

@interface SBMediaController : _ABAddressBookCopyLocalizedLabel
{
    int _manualVolumeChangeCount;
    NSDictionary *_nowPlayingInfo;
    float _pendingVolumeChange;
    NSTimer *_volumeCommitTimer;
    BOOL _debounceVolumeRepeat;
    int _numberOfVolumeDecreasesSinceDownButtonDown;
    int _lastNowPlayingAppPID;
    BOOL _lastNowPlayingAppIsPlaying;
    BOOL _suppressHUD;
    BOOL _ringerMuted;
    BOOL _screenSharing;
    BOOL _screenSharingSetsStatusBarOverride;
    NSTimer *_screenSharingStatusBarOverrideTimer;
    NSTimer *_videoOutStatusBarOverrideTimer;
    MPAudioDeviceController *_audioDeviceController;
}

+ (BOOL)applicationCanBeConsideredNowPlaying:(id)fp8;
+ (id)sharedInstance;
- (void)_delayedExtendSleepTimer;
- (void)_commitVolumeChange:(id)fp8;
- (void)_cancelPendingVolumeChange;
- (void)_nowPlayingAppIsPlayingDidChange;
- (void)_nowPlayingPIDChanged;
- (void)_nowPlayingInfoChanged;
- (void)_systemMuteChanged:(id)fp8;
- (void)_softMuteChanged:(id)fp8;
- (void)_systemVolumeChanged:(id)fp8;
- (void)_externalScreenChanged:(id)fp8;
- (void)_updateAVRoutes;
- (void)_serverConnectionDied:(id)fp8;
- (void)_unregisterForNotifications;
- (void)_registerForNotifications;
- (void)_airPlayPasswordAlertWillDisappear;
- (void)_airPlayPasswordAlertWillAppear;
- (BOOL)routeOtherThanHandsetIsAvailable;
- (BOOL)volumeControlIsAvailable;
- (BOOL)handsetRouteIsSelected;
- (void)requestAirPlayRouteDiscovery:(BOOL)fp8;
- (void)audioDeviceControllerMediaServerDied:(id)fp8;
- (void)audioDeviceControllerAudioRoutesChanged:(id)fp8;
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;
- (void)cancelVolumeEvent;
- (void)decreaseVolume;
- (void)increaseVolume;
- (float)_calcButtonRepeatDelay;
- (void)_changeVolumeBy:(float)fp8;
- (BOOL)lastSavedRingerMutedState;
- (BOOL)isRingerMuted;
- (void)setRingerMuted:(BOOL)fp8;
- (BOOL)muted;
- (void)setVolume:(float)fp8;
- (float)volume;
- (BOOL)setPlaybackSpeed:(int)fp8;
- (BOOL)toggleShuffle;
- (BOOL)toggleRepeat;
- (BOOL)skipFifteenSeconds:(int)fp8;
- (BOOL)stop;
- (BOOL)togglePlayPause;
- (BOOL)pause;
- (BOOL)play;
- (BOOL)endSeek:(int)fp8;
- (BOOL)beginSeek:(int)fp8;
- (BOOL)changeTrack:(int)fp8;
- (BOOL)_sendMediaCommand:(unsigned int)fp8;
- (void)_startVideoOutStatusBarStyleOverride;
- (void)_clearVideoOutStatusBarStyleOverride;
- (void)updateScreenSharingStatusBarStyleOverride;
- (void)updateScreenSharingStatusBarStyleOverrideSuppressionPreference;
- (void)_clearScreenSharingStatusBarStyleOverride;
- (void)setSuppressHUD:(BOOL)fp8;
- (BOOL)suppressHUD;
- (id)mediaControlsDestinationApp;
- (id)nowPlayingApplication;
- (BOOL)trackIsBeingPlayedByMusicApp;
- (void)setCurrentTrackTime:(float)fp8;
- (double)trackElapsedTime;
- (double)trackDuration;
- (int)shuffleMode;
- (int)repeatMode;
- (id)nowPlayingAlbum;
- (id)nowPlayingTitle;
- (id)nowPlayingArtist;
- (BOOL)trackSupports15SecondFF;
- (BOOL)trackSupports15SecondRewind;
- (unsigned long long)trackUniqueIdentifier;
- (BOOL)isTVOut;
- (BOOL)isMovie;
- (BOOL)isPlaying;
- (BOOL)isLastTrack;
- (BOOL)isFirstTrack;
- (BOOL)hasTrack;
- (void)setNowPlayingInfo:(id)fp8;
- (id)_nowPlayingInfo;
- (void)dealloc;
- (id)init;

@end

