/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBApplication, UIView;

@interface SBMiniAlertController : _ABAddressBookCopyLocalizedLabel
{
    SBApplication *_displayShowingAnAlert;
    unsigned int _sbMiniAlertVisible:1;
    UIView *_hiddenAlertWindow;
}

+ (id)sharedInstance;
- (BOOL)canShowAlerts;
- (BOOL)miniAlertVisible;
- (void)_setAlertVisibleNotifyState:(BOOL)fp8;
- (void)noteMiniAlertStateChanged;
- (void)hideApplicationMiniAlerts;
- (void)_hideMiniAlertsForApp:(id)fp8;
- (void)showApplicationMiniAlertsIfNeeded;
- (void)displayDidDismissMiniAlert:(id)fp8;
- (void)displayWillDismissMiniAlert:(id)fp8;
- (id)displayShowingAnAlert;
- (void)displayWillShowMiniAlert:(id)fp8;
- (void)_setDisplayShowingAnAlert:(id)fp8;
- (void)deactivateAlertItemsForDisplay:(id)fp8;
- (void)dealloc;
- (id)init;

@end

