/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBNewsstandItemIconViewBase.h"

@class UILabel, UIView;

@interface SBNewsstandItemIconView : SBNewsstandItemIconViewBase
{
    UIView *_iconTransformView;
    UILabel *_indexLabel;
    unsigned int _newsstandIndex;
}

+ (struct CGSize)_maxLabelSize;
+ (struct CGSize)defaultIconSize;
- (void)setNewsstandIndex:(unsigned int)fp8;
- (void)positionLabel;
- (void)setIsGrabbed:(BOOL)fp8;
- (struct CGRect)_frameForAccessoryView;
- (void)positionIconImageView;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)applyIconImageTransform:(struct CATransform3D)fp8 duration:(float)fp72 delay:(float)fp76;
- (id)createShadowImageView;
- (void)positionCloseBoxOfType:(int)fp8;
- (void)prepareForRecycling;
- (struct CGRect)defaultFrameForProgressBar;
- (void)dealloc;
- (id)initWithDefaultSize;
- (id)initWithFrame:(struct CGRect)fp8;

@end

