/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPhoneAlertItem.h"

@interface SBNetworkReselectionAlertItem : SBPhoneAlertItem
{
}

- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)performUnlockAction;
- (id)shortLockLabel;
- (id)lockLabel;
- (void)_showPrefs;
- (id)init;

@end

