/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFolderView.h"

@class NSTimer, SBNewsstandCardView, SBNewsstandShelfFrameView, UIButton, UIImageView, UITableView;

@interface SBNewsstandFolderView : SBFolderView
{
    UIButton *_storeButton;
    UIImageView *_navigationBar;
    UIImageView *_bottomBar;
    UITableView *_shelvesView;
    SBNewsstandShelfFrameView *_shelfFrameView;
    unsigned int _minVisibleRow;
    unsigned int _maxVisibleRow;
    int _lastConfiguredOrientation;
    BOOL _didMakeHeaderVisible;
    float _targetContentOffset;
    BOOL _orientationShenanigans;
    NSTimer *_autoscrollTimer;
    double _autoscrollStartTime;
    int _autoscrollDirection;
    float _autoscrollIntensity;
    SBNewsstandCardView *_cardView;
    BOOL _showingCardView;
}

+ (id)woodImageForNotchDirection:(int)fp8 inOrientation:(int)fp12;
+ (id)_bottombarImageForOrientation:(int)fp8;
+ (id)_navbarImageForOrientation:(int)fp8;
- (void)_placeBackgroundView;
- (void)_placeIconListView;
- (void)_placeBars;
- (float)_labelHorizontalInset;
- (float)_labelVerticalInset;
- (void)_placeShadows;
- (void)_placeShadow:(int)fp8;
- (id)_shadowForPosition:(int)fp8;
- (id)_shadowImageForPosition:(int)fp8;
- (id)editTitleField;
- (BOOL)canEditTitle;
- (void)scrollViewDidScroll:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)showStoreCard:(BOOL)fp8 animate:(BOOL)fp12;
- (void)setFrame:(struct CGRect)fp8;
- (struct CGPoint)_getOriginForCardOnShelf;
- (BOOL)isShowingCard;
- (id)cardView;
- (void)noteHasGrabbedIcon:(id)fp8;
- (void)noteGrabbedIconLocation:(struct CGPoint)fp8;
- (void)_autoscrollTimerFired:(id)fp8;
- (float)_maxVelocityInDirection:(int)fp8;
- (int)_autoscrollableDirections;
- (void)_cancelAutoscroll;
- (void)didDropIconView;
- (void)prepareToDropIconView:(id)fp8 targetFolderBounds:(struct CGRect *)fp12;
- (void)setScrollOffset:(id)fp8;
- (id)scrollOffset;
- (BOOL)isScrolling;
- (void)_storeAvailabilityDidChange:(id)fp8;
- (void)storeButtonClicked;
- (void)cleanUpAfterOrientationChange;
- (void)prepareToSetOrientation:(int)fp8;
- (void)_updateRotationDebugging;
- (void)_prepareToSetOrientation:(int)fp8 dryRun:(BOOL)fp12;
- (unsigned int)_rowForScrollOffset:(float)fp8;
- (void)setRows:(unsigned int)fp8 notchInfo:(CDAnonymousStruct6)fp12 orientation:(int)fp32;
- (void)_createInitialIconViews;
- (void)_setupFolderTitleLabel;
- (void)_setupBackgroundView;
- (void)_setupNavigationBar;
- (void)_configureBars;
- (void)_updateVisibleRows;
- (struct CGSize)_sizeForCurrentConfiguration;
- (struct CGSize)_contentSizeForRows:(unsigned int)fp8 inOrientation:(int)fp12;
- (float)_contentHeightForCurrentConfiguration;
- (float)_contentHeightForRows:(unsigned int)fp8;
- (float)_maxHeightForOrientation:(int)fp8;
- (float)_extraRowPeekage;
- (float)_shelfHeaderHeight;
- (BOOL)_shouldShowStoreButton;
- (float)_heightPerRow;
- (id)iconListView;
- (struct CGRect)rectForNotchLinen;
- (Class)notchViewClass;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

