/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUserInstalledApplicationIcon.h"

@class SBNewsstandApplication;

@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon
{
    SBNewsstandApplication *_fakeApp;
}

+ (id)iconOverlayImageForIcon:(id)fp8 inLocation:(int)fp12;
- (void)setFakeApp:(id)fp8;
- (id)fakeApp;
- (id)_newlyInstalledSashLabel;
- (BOOL)_shouldShowSashForNewlyInstalledApp;
- (id)badgeTextForLocation:(int)fp8;
- (id)badgeNumberOrString;
- (int)accessoryTypeForLocation:(int)fp8;
- (id)gridCellImage;
- (BOOL)shouldCacheImageForFormat:(int)fp8;
- (id)iconOverlayImageForLocation:(int)fp8;
- (id)getGenericIconImage:(int)fp8;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)isNewsstandApplicationIcon;
- (int)iconFormatForLocation:(int)fp8;
- (void)launch;
- (BOOL)launchEnabled;
- (id)application;
- (BOOL)shouldWarmUp;
- (void)dealloc;
- (id)initWithApplication:(id)fp8;

@end

