/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBNewsstandShelfTableView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_backView;
}

- (void)setShelfFrameView:(id)fp8;
- (id)shelfFrameView;
- (void)reloadData;
- (void)willRemoveSubview:(id)fp8;
- (void)didAddSubview:(id)fp8;

@end

