/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBNewsstandShelfHeaderView, SBNewsstandTilingImageView;

@interface SBNewsstandShelfFrameView : _ABAddressBookCopyLocalizedLabel
{
    struct CGSize _borderSize;
    SBNewsstandShelfHeaderView *_headerView;
    SBNewsstandTilingImageView *_leftBorder;
    SBNewsstandTilingImageView *_rightBorder;
    int _orientation;
}

- (void)layoutSubviews;
- (void)configureForOrientation:(int)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)showHeaderView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

