/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconSashImage.h"

@interface SBNewsstandSwitcherSashImage : SBIconSashImage
{
}

+ (float)_labelMinFontSize;
+ (float)_labelMaxFontSize;
+ (struct CGPoint)_sashCenterPoint;
+ (float)_sashWidth;
+ (struct UIEdgeInsets)_sashImageInsets;
+ (id)_baseImage;

@end

