/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplication.h"

@interface SBNewsstandApplication : SBApplication
{
    BOOL _isMagazineApp;
    BOOL _iconIsBoundOnRight;
    unsigned int _supportsNewsstandContentBackgroundMode:1;
    unsigned int _allowedContentNotificationsPerDay;
    unsigned char _newsstandWakes;
    unsigned int _lastPostedState;
}

- (BOOL)iconIsBoundOnRight;
- (BOOL)isMagazineApp;
- (BOOL)isNewsstandApplication;
- (BOOL)shouldThrottleContentNotificationOnDate:(id)fp8 withLastCount:(unsigned int *)fp12 onDay:(int *)fp16;
- (BOOL)isFakeApp;
- (void)resumeForContentAvailable;
- (void)setApplicationState:(unsigned int)fp8;
- (void)activate;
- (Class)iconClass;
- (id)initWithBundleIdentifier:(id)fp8 webClip:(id)fp12 path:(id)fp16 bundle:(id)fp20 infoDictionary:(id)fp24 isSystemApplication:(BOOL)fp28 signerIdentity:(id)fp32 provisioningProfileValidated:(BOOL)fp36;

@end

