/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconGridImage.h"

@interface SBNewsstandIconGridImage : SBIconGridImage
{
}

+ (struct CGRect)rectAtIndex:(unsigned int)fp8 forImage:(id)fp12 maxCount:(unsigned int)fp16;
+ (struct CGSize)cellSpacing;
+ (struct CGSize)cellSize;

@end

