/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconView.h"

@class SBDownloadingProgressBar;

@interface SBNewsstandItemIconViewBase : SBIconView
{
    SBDownloadingProgressBar *_progressBar;
}

+ (Class)_labelImageParametersClassForIcon:(id)fp8 location:(int)fp12;
- (void)downloadingIconStatusDidChange:(id)fp8;
- (void)_adjustProgressBarFrame;
- (void)iconAccessoriesDidUpdate:(id)fp8;
- (void)_updateProgressBar;
- (void)_removeProgressBar;
- (void)_updateLabelVisibility;
- (struct UIEdgeInsets)_viewInsetsForAccessoryType:(int)fp8;
- (id)_iconBoundsForAccessory:(struct CGRect *)fp8;
- (void)iconImageDidUpdate:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

