/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBIconRotationContainer.h"

@interface SBNewsstandIconRotationContainer : SBIconRotationContainer
{
}

- (void)crossfadeWithDuration:(double)fp8 inIconList:(id)fp16;
- (void)setStartIcon:(id)fp8 endIcon:(id)fp12 inIconList:(id)fp16 fromOrientation:(int)fp20 toOrientation:(int)fp24;

@end

