/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFolderIconListView.h"

@class NSMutableArray;

@interface SBNewsstandIconListView : SBFolderIconListView
{
    unsigned int _firstVisibleRow;
    unsigned int _lastVisibleRow;
    unsigned int _preRotationFirstVisibleRow;
    unsigned int _postRotationFirstVisibleRow;
    unsigned int _rotationPlacementRow;
    NSMutableArray *_visibleIcons;
}

+ (unsigned int)maxVisibleIconRowsInterfaceOrientation:(int)fp8;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)fp8;
+ (unsigned int)iconRowsForInterfaceOrientation:(int)fp8;
+ (unsigned int)maxIcons;
- (void)showIconImagesFromRow:(unsigned int)fp8 toRow:(unsigned int)fp12;
- (void)_noteNewIconInModel:(id)fp8;
- (void)_updateVisibleIconsFromRow:(unsigned int)fp8 toRow:(unsigned int)fp12 includeIcon:(id)fp16 layoutIfNeeded:(BOOL)fp20;
- (void)setFirstRowToStartRotation:(unsigned int)fp8 endRotation:(unsigned int)fp12 moveIconsRelativeToRow:(unsigned int)fp16;
- (unsigned int)_rotationReferenceRow;
- (unsigned int)_postRotationFirstVisibleRow;
- (unsigned int)_preRotationFirstVisibleRow;
- (id)visibleIcons;
- (void)cleanupAfterRotation;
- (struct CATransform3D)_transformForIconAtIndex:(unsigned int)fp8 inOrientation:(int)fp12;
- (struct CGSize)defaultIconSize;
- (float)verticalIconPadding;
- (float)sideIconInset;
- (float)bottomIconInset;
- (float)topIconInset;
- (unsigned int)iconRowsForCurrentOrientation;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (Class)iconRotationContainerClass;

@end

