/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBIconView, SBNowPlayingBarMediaControlsView, UIButton, UIImageView, UISlider, UIView;

@interface SBNowPlayingBarView : _ABAddressBookCopyLocalizedLabel
{
    int _toggleType;
    UIView *_toggleButtonContainer;
    UIButton *_toggleButton;
    UISlider *_brightnessSlider;
    UISlider *_volumeSlider;
    UIImageView *_brightnessImage;
    UIImageView *_volumeImage;
    SBNowPlayingBarMediaControlsView *_mediaView;
    SBIconView *_nowPlayingIconView;
}

- (id)nowPlayingIconView;
- (id)mediaView;
- (id)volumeSlider;
- (id)brightnessSlider;
- (id)toggleButton;
- (void)showVolume:(BOOL)fp8;
- (void)showAudioRoutesPickerButton:(BOOL)fp8;
- (void)setNowPlayingIconView:(id)fp8;
- (BOOL)marqueeRunning;
- (void)setMarqueeRunning:(BOOL)fp8;
- (id)airPlayButton;
- (void)_updateToggleButton;
- (void)_layoutForiPad;
- (void)_layoutForiPhone;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setToggleType:(int)fp8;
- (int)toggleType;

@end

