/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBAppSwitcherLabel, UIButton;

@interface SBNowPlayingBarMediaControlsView : _ABAddressBookCopyLocalizedLabel
{
    UIButton *_prevButton;
    UIButton *_playButton;
    UIButton *_nextButton;
    UIButton *_airPlayButton;
    UIButton *_fifteenSecondRewindButton;
    UIButton *_fifteenSecondFFButton;
    SBAppSwitcherLabel *_trackLabel;
    int _toggleType;
    SBAppSwitcherLabel *_toggleLabel;
    BOOL _isAirPlayVisible;
    BOOL _isPlaying;
    int _currentTrackSupportsSkip;
    BOOL _isEnabled;
    BOOL _showingToggleLabel;
}

- (BOOL)airPlayButtonVisible;
- (id)airPlayButton;
- (id)nextButton;
- (id)playButton;
- (id)prevButton;
- (void)_muteChanged:(id)fp8;
- (void)_orientationLockChanged:(id)fp8;
- (id)_toggleLabelText;
- (void)_setToggleType:(int)fp8;
- (void)_toggleStatus:(id)fp8;
- (void)setLabelWidth:(float)fp8;
- (BOOL)marqueeRunning;
- (void)setMarqueeRunning:(BOOL)fp8;
- (void)setAirPlayButtonVisible:(BOOL)fp8;
- (void)setTrackString:(id)fp8;
- (void)_layoutForiPad;
- (void)_layoutForiPhone;
- (void)layoutSubviews;
- (void)updateImages:(BOOL)fp8 enabled:(BOOL)fp12;
- (id)fifteenSecondFFButton;
- (id)fifteenSecondRewindButton;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

