/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBNowPlayingPushButton : _ABAddressBookCopyLocalizedLabel
{
    float _yOffset;
    float _xOffset;
}

+ (id)newButtonWithImage:(id)fp8;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (struct CGRect)hitRect;
- (void)setXOffset:(float)fp8;
- (void)setYOffset:(float)fp8;

@end

