/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UILabel;

@interface SBNoResultsView : _ABAddressBookCopyLocalizedLabel
{
    UILabel *_noResultsLabel;
}

- (void)setShowsText:(BOOL)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

