/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBIconViewDelegate-Protocol.h"
#import "SBSwitcherPopoverWindowControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class MPAudioVideoRoutingActionSheet, MPAudioVideoRoutingPopoverController, SBAirPlayBarView, SBAppSwitcherVolumeSlider, SBApplication, SBNowPlayingBarView, UIButton, UIViewController;

@interface SBNowPlayingBar : _ABAddressBookCopyLocalizedLabel <SBIconViewDelegate, UIPopoverControllerDelegate, SBSwitcherPopoverWindowControllerDelegate>
{
    SBNowPlayingBarView *_barView;
    SBAirPlayBarView *_airPlayView;
    MPAudioVideoRoutingActionSheet *_airPlayActionSheet;
    UIViewController *_airPlayController;
    SBAppSwitcherVolumeSlider *_volumeSlider;
    UIButton *_airPlayButton;
    SBApplication *_nowPlayingApp;
    int _scanDirection;
    MPAudioVideoRoutingPopoverController *_audioRoutingPopoverController;
    BOOL _audioRoutingPopoverVisible;
    BOOL _showPopoverWhenRotationComplete;
    struct BKSDisplayBrightnessTransaction *_brightnessTransaction;
}

- (void)viewControllerRequestsDismissal:(id)fp8;
- (void)switcherPopoverController:(id)fp8 didRotateFromInterfaceOrientation:(int)fp12;
- (void)switcherPopoverController:(id)fp8 willRotateToOrientation:(int)fp12 duration:(double)fp16;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)audioRoutesChanged:(id)fp8;
- (void)backlightLevelChanged;
- (void)iconTouchBegan:(id)fp8;
- (BOOL)iconShouldAllowTap:(id)fp8;
- (void)iconTapped:(id)fp8;
- (BOOL)_isAirPlayOn;
- (void)_showAudioRoutingPopover;
- (BOOL)_shouldShowAirPlayButton;
- (void)_dismissAirPlayDetail;
- (void)_airPlayButtonHit:(id)fp8;
- (void)_brightnessSliderTouchEnded:(id)fp8;
- (void)_brightnessSliderChanged:(id)fp8;
- (void)_iapExtendedModeChanged:(id)fp8;
- (void)_updateAudioRouteDisplay:(BOOL)fp8;
- (void)_updateNowPlayingButtonImages;
- (void)_nowPlayingInfoChanged;
- (void)_updateNowPlayingInfo;
- (void)_updateNowPlayingApp;
- (void)_fifteenSecondSkip:(id)fp8;
- (void)_trackButtonDownSeek:(id)fp8;
- (void)_trackButtonDown:(id)fp8;
- (void)_trackButtonCancel:(id)fp8;
- (void)_trackButtonUp:(id)fp8;
- (void)_playButtonHit:(id)fp8;
- (void)_toggleButtonHit:(id)fp8;
- (void)_updateDisplay;
- (BOOL)shouldScrollCancelInContentForView:(id)fp8;
- (void)prepareToDisappear;
- (void)warmup;
- (void)viewAtIndexDidDisappear:(int)fp8;
- (void)viewAtIndexDidAppear:(int)fp8;
- (void)setVisible:(BOOL)fp8;
- (int)scanDirection;
- (id)views;
- (void)dealloc;
- (id)init;

@end

