/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPanGestureRecognizer.h"

@interface SBOffscreenSwipeGestureRecognizer : SBPanGestureRecognizer
{
    int m_offscreenEdge;
    float m_edgeMargin;
    float m_falseEdge;
    int m_touchesChecked;
    struct CGPoint m_firstTouch;
    float m_edgeCenter;
    float m_allowableDistanceFromEdgeCenter;
    BOOL m_requiresSecondTouchInRange;
}

- (void)setEdgeCenter:(float)fp8;
- (float)edgeCenter;
- (void)setRequiresSecondTouchInRange:(BOOL)fp8;
- (BOOL)requiresSecondTouchInRange;
- (void)setAllowableDistanceFromEdgeCenter:(float)fp8;
- (float)allowableDistanceFromEdgeCenter;
- (float)falseEdge;
- (float)edgeMargin;
- (void)updateForBeganOrMovedTouches:(struct __SBGestureContext *)fp8;
- (void)_updateAnimationDistanceAndEdgeCenter;
- (BOOL)secondTouchInRange:(struct CGPoint)fp8;
- (BOOL)firstTouchInRange:(struct CGPoint)fp8;
- (void)setFalseEdge:(float)fp8;
- (void)setEdgeMargin:(float)fp8;
- (void)reset;
- (id)initForOffscreenEdge:(int)fp8;

@end

