/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray;

@interface SBOrderedRequesters : _ABAddressBookCopyLocalizedLabel
{
    NSMutableArray *_bands[2];
}

- (id)description;
- (void)prioritizeRequester:(id)fp8;
- (void)removeRequester:(id)fp8;
- (void)addRequester:(id)fp8 toBand:(int)fp12;
- (BOOL)containsRequester:(id)fp8 inBand:(int)fp12;
- (id)requesters;
- (id)frontmostRequester;
- (void)dealloc;
- (id)init;

@end

