/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSDate, NSString, SBPasscodeAlertItem, SBPasscodeComplianceAlertItem;

@interface SBPasscodeController : _ABAddressBookCopyLocalizedLabel
{
    SBPasscodeAlertItem *_passcodeAlertItem;
    int _mode;
    NSString *_previousPasscode;
    NSString *_newPasscode;
    int _unlockScreenType;
    SBPasscodeComplianceAlertItem *_complianceAlertItem;
    NSDate *_forcedComplianceDate;
    id _telephonyNotificationObserver;
}

+ (id)sharedInstance;
- (void)checkPasscodeCompliance;
- (void)_stopListeningToTelephonyNotifications;
- (void)_startListeningToTelephonyNotifications;
- (void)_didEndCall;
- (void)_abort;
- (void)_userWantsToComplyNow:(BOOL)fp8;
- (void)_passwordEntered:(id)fp8;
- (void)forceUserToChangePasscode;
- (void)dealloc;

@end

