/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString;

@interface SBPasscodeAlertItem : _ABAddressBookCopyLocalizedLabel <UITextFieldDelegate>
{
    int _mode;
    int _unlockScreenType;
    NSString *_errorString;
    BOOL _hasEmergencyCall;
}

- (void)didEndCall;
- (void)_setErrorString:(id)fp8;
- (void)dismiss:(int)fp8;
- (BOOL)shouldShowInLockScreen;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)returnKeyPressed:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)dealloc;
- (id)initWithPasscodeMode:(int)fp8 unlockScreenType:(int)fp12;

@end

