/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFluidSlideGestureRecognizer.h"

@interface SBPanGestureRecognizer : SBFluidSlideGestureRecognizer
{
    float _arcCenter;
    float _arcSize;
    BOOL _recognizesHorizontalPanning;
    BOOL _recognizesVerticalPanning;
}

- (void)updateForBeganOrMovedTouches:(struct __SBGestureContext *)fp8;
- (float)computeIncrementalGestureMotion:(struct __SBGestureContext *)fp8;
- (id)initForVerticalPanning;
- (id)initForHorizontalPanning;
- (id)init;

@end

