/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface SBPlatformController : _ABAddressBookCopyLocalizedLabel
{
    NSString *_currentConfigurationName;
    NSMutableDictionary *_currentConfiguration;
    NSMutableDictionary *_currentCapabilities;
    NSMutableDictionary *_regionalOverrideSoftwareBehaviors;
    NSDictionary *_discoveredCapabilities;
    int _currentLockdownState;
    BOOL _saveLocalePostActivation;
}

+ (id)productType;
+ (id)hardwareModel;
+ (id)systemBuildVersion;
+ (id)sharedInstance;
- (void)setOriginalRegionFormatCountryCodeAndResetSoftwareBehaviorsIfNecessary;
- (void)localeChanged;
- (void)_iCloudRestoreDidEnd;
- (void)visibleIdentifiersChanged:(id)fp8;
- (void)lockdownStateChanged;
- (id)regionalOverrideSoftwareBehaviorForKey:(id)fp8;
- (void)setSoftwareBehavior:(id)fp8 forKey:(id)fp12;
- (void)resetDefaultSoftwareBehaviorsAndPost:(BOOL)fp8;
- (void)noteConfigurationChangedWithKeys:(id)fp8;
- (struct __CFBoolean *)currentITunesStoreCapability;
- (void)addTelephonyCapabilitiesAndPost:(BOOL)fp8;
- (void)discoverCurrentConfiguration;
- (BOOL)allowYouTubePlugin;
- (BOOL)allowYouTube;
- (BOOL)isCarrierInstall:(BOOL)fp8 hasInternalBundle:(BOOL)fp12;
- (BOOL)allowSensitiveUI:(BOOL)fp8 hasInternalBundle:(BOOL)fp12;
- (id)_copyDefaultConfigInfo;
- (id)_copyConfigInfoWithName:(id)fp8;
- (void)postCurrentConfiguration;
- (id)currentConfigurationName;
- (void)noteDeveloperDeviceStateMightHaveChanged;
- (void)noteCapabilityOverridesMightHaveChanged;
- (void)noteCapabilityOverrideMightHaveChanged:(id)fp8 setByPreference:(id)fp12;
- (BOOL)capabililtyOverrideEnabledByPreference:(id)fp8;
- (void)noteITunesStoreCapabilityChanged;
- (void)registerForIconVisibilityChanges;
- (BOOL)isCarrierInstall;
- (BOOL)isInternalInstall;
- (id)localizedPlatformName;
- (BOOL)matchesPlatforms:(id)fp8;
- (id)defaultDisplayIdentifiers;
- (void)_addIconListIdentifiers:(id)fp8 toSet:(id)fp12;
- (id)iconState;
- (id)platformName;
- (BOOL)hasRestriction:(id)fp8;
- (id)enabledCapabilities;
- (BOOL)hasCapability:(id)fp8;
- (void)addCapabilities:(id)fp8 resetCapabilites:(id)fp12;
- (void)setValue:(id)fp8 forCapability:(id)fp12;
- (id)hardwareInfoForCapability:(id)fp8;
- (id)defaultInfoForCapability:(id)fp8;
- (id)infoForCapability:(id)fp8;
- (void)dealloc;
- (id)init;

@end

