/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBPolygon : _ABAddressBookCopyLocalizedLabel
{
    int m_pointCount;
    struct CGPoint m_points[5];
    unsigned int m_pathIDs[5];
    float m_weights[5];
    struct CGPoint m_centroid;
    struct CGPoint m_weightedCentroid;
    unsigned int m_baseLeftVertex;
    unsigned int m_bottomRightVertex;
}

+ (BOOL)candidate:(id)fp8 matchesTemplate:(id)fp12 transforms:(int)fp16 acceptFactor:(float)fp20;
- (struct CGPoint)weightedCentroid;
- (struct CGPoint)centroid;
- (int)pointCount;
- (float)meanRadius;
- (float)meanFingertipRowAngle;
- (float)baseOrientation;
- (struct CGPoint)calculateWeightedCentroid;
- (struct CGPoint)calculateCentroid;
- (float)findLongestOutsideEdge;
- (void)sortAlongOutsideEdge;
- (void)flipHorizontally;
- (void)scale:(float)fp8;
- (void)rotate:(float)fp8;
- (unsigned int)thumbIndex;
- (BOOL)isLeftHanded;
- (float)height;
- (float)width;
- (void)setWeightedCentroid:(struct CGPoint)fp8;
- (void)setCentroid:(struct CGPoint)fp8;
- (float)weightAtIndex:(int)fp8;
- (void)endPointUpdate;
- (void)addPoint:(struct CGPoint)fp8 pathIndex:(unsigned int)fp16;
- (void)addPoint:(struct CGPoint)fp8;
- (void)beginPointUpdate;
- (void)clear;
- (void)makeLike:(id)fp8;
- (void)commonInit;

@end

