/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertView.h"

@class NSTimer, TPBottomSingleButtonBar, TPTopLockBar, UIView;

@interface SBPowerDownView : SBAlertView
{
    id <SBPowerDownViewDelegate> _delegate;
    UIView *_dimView;
    TPTopLockBar *_lockView;
    TPBottomSingleButtonBar *_cancelView;
    NSTimer *_autoDismissTimer;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)layoutForInterfaceOrientation:(int)fp8;
- (BOOL)isSupportedInterfaceOrientation:(int)fp8;
- (void)animateDark;
- (void)animateOut;
- (void)animateIn;
- (void)notifyDelegateOfPowerDown;
- (void)finishedAnimatingOut;
- (void)finishedAnimatingIn;
- (void)powerDown:(id)fp8;
- (void)lockBarStoppedTracking:(id)fp8;
- (void)lockBarStartedTracking:(id)fp8;
- (void)lockBarUnlocked:(id)fp8;
- (void)cancel:(id)fp8;
- (void)resetAutoDismissTimer;
- (void)cancelAutoDismissTimer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

