/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBSwitcherPopoverWindowControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPrintStatusDelegate-Protocol.h"
#import "UIStatusBarStyleDelegate-Protocol.h"

@class SBAppSwitcherController, UIPrintStatusViewController, UIStatusBar, UITransitionView, UIView;

@interface SBPrintStatusController : _ABAddressBookCopyLocalizedLabel <UIPrintStatusDelegate, UINavigationControllerDelegate, UIStatusBarStyleDelegate, SBSwitcherPopoverWindowControllerDelegate>
{
    SBAppSwitcherController *_switcherController;
    UIPrintStatusViewController *_printStatusController;
    int _numPrintJobs;
    BOOL _dismissingImmediately;
    BOOL _printViewVisible;
    UIView *_rootView;
    UITransitionView *_transitionView;
    UIStatusBar *_fakeStatusBar;
    BOOL _savePopoverWindowForRotation;
    BOOL _showPopoverWhenRotationComplete;
}

- (int)numPrintJobs;
- (void)switcherPopoverController:(id)fp8 didRotateFromInterfaceOrientation:(int)fp12;
- (void)switcherPopoverController:(id)fp8 willRotateToOrientation:(int)fp12 duration:(double)fp16;
- (void)statusBar:(id)fp8 didAnimateFromHeight:(float)fp12 toHeight:(float)fp16 animation:(int)fp20;
- (void)statusBar:(id)fp8 willAnimateFromHeight:(float)fp12 toHeight:(float)fp16 duration:(double)fp20 animation:(int)fp28;
- (int)statusBar:(id)fp8 styleForRequestedStyle:(int)fp12 overrides:(int)fp16;
- (void)navigationController:(id)fp8 willShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)printStatusViewControllerJobDidCancel:(id)fp8;
- (void)printStatusViewController:(id)fp8 didDismissWithCancel:(BOOL)fp12;
- (double)durationForTransition:(int)fp8;
- (void)transitionViewDidComplete:(id)fp8 fromView:(id)fp12 toView:(id)fp16;
- (void)_dismissPrintStatus;
- (void)_cleanupPopoverViews:(BOOL)fp8;
- (void)_cleanupPrintController;
- (void)_printStateChanged:(id)fp8;
- (void)_updateStateForNumberOfJobs:(int)fp8;
- (void)dismissPrintStatusView;
- (void)activatePrintStatusPopoverForView:(id)fp8;
- (void)activatePrintStatusView;
- (BOOL)printStatusViewIsShowing;
- (void)dealloc;
- (id)initWithSwitcherController:(id)fp8;

@end

