/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@interface SBPrintStatusIcon : SBLeafIcon
{
}

- (BOOL)delaysUnhighlightWhenTapped;
- (id)applicationBundleID;
- (BOOL)shouldEllipsizeLabel;
- (id)leafIdentifier;
- (id)displayName;
- (id)generateIconImage:(int)fp8;

@end

