/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, SBApplication;

@interface SBProxyRemoteView : _ABAddressBookCopyLocalizedLabel
{
    id _delegate;
    SBApplication *_app;
    NSString *_remoteViewIdentifier;
    BOOL _remoteViewOpaque;
}

+ (Class)layerClass;
- (void)setRemoteViewOpaque:(BOOL)fp8;
- (BOOL)remoteViewOpaque;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setRemoteViewIdentifier:(id)fp8;
- (id)remoteViewIdentifier;
- (void)disconnect;
- (void)noteConnectionLost;
- (void)_setIsConnected:(BOOL)fp8;
- (void)connectToContextID:(unsigned int)fp8 forIdentifier:(id)fp12 application:(id)fp16;
- (void)didMoveToSuperview;
- (void)dealloc;
- (id)init;

@end

