/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSObject<OS_dispatch_queue>;

@interface SBPushStore : _ABAddressBookCopyLocalizedLabel
{
    NSObject<OS_dispatch_queue> *_notificationsQueue;
    NSObject<OS_dispatch_queue> *_settingsQueue;
}

+ (void)migratePushStore;
+ (id)sharedInstance;
+ (void)initialize;
- (void)dealloc;
- (BOOL)prepareToSupportLocalNotificationsTypes:(unsigned int)fp8 forBundleID:(id)fp12;
- (void)setEffectivePushSettings:(unsigned int)fp8 forBundleID:(id)fp12;
- (unsigned int)effectivePushSettingsForBundleID:(id)fp8;
- (unsigned int)_effectivePushSettingsForBundleID:(id)fp8;
- (id)allNotificationEnabledBundleIDs;
- (id)allLocalNotificationEnabledBundleIDs;
- (id)lastUpdateDateForBundleID:(id)fp8;
- (id)bundleIDsWithUpdatesSince:(id)fp8;
- (id)savedNotificationDataForBundleID:(id)fp8;
- (void)makeTestNotificationStores;
- (void)removeAllLocalNotificationsForBundleID:(id)fp8;
- (void)removeLocalNotification:(id)fp8 forBundleID:(id)fp12;
- (void)saveLocalNotification:(id)fp8 forBundleID:(id)fp12;
- (void)saveRemoteNotificationWithMessage:(id)fp8 soundName:(id)fp12 actionText:(id)fp16 badge:(id)fp20 userInfo:(id)fp24 launchImage:(id)fp28 forBundleID:(id)fp32;
- (void)_saveNotificationWithMessage:(id)fp8 soundName:(id)fp12 actionText:(id)fp16 badge:(id)fp20 userInfo:(id)fp24 launchImage:(id)fp28 fullDetails:(id)fp32 soundIsRingtone:(BOOL)fp36 isRemoteNotification:(BOOL)fp40 forBundleID:(id)fp44;
- (void)clearNotificationsForBundleID:(id)fp8;
- (void)unregisterAppForNotificationsWithBundleID:(id)fp8;
- (void)_removeNotificationsForBundleID:(id)fp8 andSendNotification:(id)fp12;
- (void)registerAppForNotificationsWithBundleID:(id)fp8;
- (BOOL)_saveNotificationList:(id)fp8 toPath:(id)fp12;
- (id)_allNotificationsFromPath:(id)fp8;
- (id)_allNotificationDataFromPath:(id)fp8;
- (BOOL)_notificationDataExistsAtPath:(id)fp8;
- (id)_notificationStoreFilenameForBundleID:(id)fp8;
- (void)noteInstalledAppsChanged;
- (id)init;

@end

