/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

@class SBApplication, SBAwayController;

@interface SBReturnToLockscreenWorkspaceTransaction : SBWorkspaceTransaction
{
    SBApplication *_fromApp;
    SBAwayController *_awayController;
    BOOL _workspaceAlreadyResumed;
}

- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfWorkspaceDidResume;
- (BOOL)selfAlertDidActivate:(id)fp8 overAlerts:(id)fp12;
- (void)_commit;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 fromApplication:(id)fp16 toAwayController:(id)fp20;

@end

