/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerDelegate-Protocol.h"

@class SBUIAnimationController;

@interface SBRelaunchAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerDelegate>
{
    SBUIAnimationController *_animationController;
    BOOL _relaunchSuspended;
    BOOL _keepWorkspaceSuspended;
    BOOL _waitForReceiverChange;
}

- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 didCommitAnimation:(BOOL)fp12 withDuration:(double)fp16 afterDelay:(double)fp24;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
- (void)_handleAppRelaunch:(id)fp8;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (BOOL)selfApplicationActivated:(id)fp8;
- (BOOL)selfApplicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidStartLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (void)_transactionComplete;
- (void)_commit;
- (void)_endAnimation;
- (id)_setupAnimationForApp:(id)fp8;
- (BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 application:(id)fp16;

@end

