/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBRestoreFailureAlertItem : _ABAddressBookCopyLocalizedLabel
{
    BOOL _runningModal;
}

- (BOOL)allowInSetup;
- (BOOL)forcesModalAlertAppearance;
- (BOOL)shouldShowInLockScreen;
- (BOOL)allowMenuButtonDismissal;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)performUnlockAction;
- (void)restartSystemEvent;
- (void)_rebootNow;
- (double)autoDismissInterval;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)didPresentAlertView:(id)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;

@end

