/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSCalendar, NSDate, NSTimer;

@interface SBRelativeDateTimer : _ABAddressBookCopyLocalizedLabel
{
    NSCalendar *_gregorian;
    NSTimer *_timer;
    NSDate *_date;
    id <SBRelativeDateTimerDelegate> _delegate;
    int _currResolution;
    int _currValue;
}

+ (void)invalidateTimer:(id)fp8;
+ (void)addTimerToMainRunLoop:(id)fp8;
+ (void)initialize;
- (double)_nextFireInterval:(id)fp8 resolution:(int)fp12 comparedToNow:(int)fp16;
- (void)_fireAndUpdateTimerIfNecessary;
- (id)_timeDifferenceFromDate:(id)fp8;
- (void)invalidate;
- (void)fireAndSchedule;
- (double)nextFireInterval;
- (id)date;
- (void)setDate:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)_fireForLocaleEvent:(id)fp8;
- (void)_fireForEvent:(id)fp8;
- (void)dealloc;
- (id)init;

@end

