/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIBezierPath, UIColor;

@interface SBResetProgressView : _ABAddressBookCopyLocalizedLabel
{
    UIColor *_progressColor;
    UIBezierPath *_path;
    float _resetProgress;
}

- (void)drawRect:(struct CGRect)fp8;
- (id)_progressColor;
- (id)_outlinePath;
- (void)setResetProgress:(float)fp8;
- (void)dealloc;

@end

