/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary;

@interface SBRemoteViewsController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_registeredRemoteViewInfos;
    NSMutableDictionary *_unregisteredRemoteViewInfos;
}

+ (id)sharedInstance;
- (void)unregisterRemoteViewsForApplication:(id)fp8;
- (id)proxyRemoteViewForIdentifier:(id)fp8;
- (void)_sequesterProxyRemoteView:(id)fp8;
- (id)_newProxyRemoteViewForIdentifier:(id)fp8;
- (void)unregisterRemoteIdentifier:(id)fp8 application:(id)fp12;
- (void)registerRemoteContextID:(unsigned int)fp8 forIdentifier:(id)fp12 opaque:(BOOL)fp16 size:(struct CGSize)fp20 application:(id)fp28;
- (void)unregisterProxyRemoteView:(id)fp8;
- (void)dealloc;
- (id)init;

@end

