/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBRenderImage : _ABAddressBookCopyLocalizedLabel
{
    struct _CARenderImage *_image;
}

- (void *)CA_copyRenderValue;
- (void)dealloc;
- (id)initWithRenderImage:(struct _CARenderImage *)fp8;

@end

