/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSLock;

@interface SBResetManager : _ABAddressBookCopyLocalizedLabel
{
    BOOL _threadRunning;
    NSLock *_lock;
    int _mode;
    NSLock *_progressLock;
    float _progress;
}

+ (id)sharedInstance;
- (void)_resetFinished;
- (void)_postResetEnded;
- (void)_resetThread;
- (void)_beginReset:(id)fp8;
- (void)beginReset;
- (float)progress;
- (void)setProgress:(float)fp8;
- (void)setMode:(int)fp8;
- (void)dealloc;
- (id)init;

@end

