/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFolder.h"

#import "SBIconIndexNodeObserver-Protocol.h"

@class SBDockIconListModel;

@interface SBRootFolder : SBFolder <SBIconIndexNodeObserver>
{
    SBDockIconListModel *_dock;
}

+ (int)maxListCount;
- (void)node:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)node:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (void)list:(id)fp8 didRemoveContainedNodeIdentifiers:(id)fp12;
- (void)list:(id)fp8 didAddContainedNodeIdentifiers:(id)fp12;
- (void)_notifyIndexChange:(int)fp8 identifiers:(id)fp12 withValidationBlock:(id)fp(null);
- (id)nodeDescriptionWithPrefix:(id)fp8;
- (id)nodesAlongIndexPath:(id)fp8 consumedIndexes:(unsigned int)fp12;
- (id)indexPathsForContainedNodeIdentifier:(id)fp8 prefixPath:(id)fp12;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)fp8;
- (id)nodeIdentifier;
- (void)placeIconsOnFirstPage:(id)fp8;
- (id)representation;
- (BOOL)resetWithRepresentation:(id)fp8 model:(id)fp12 leafIdentifiersAdded:(id)fp16;
- (id)folderType;
- (id)iconsOfClass:(Class)fp8;
- (void)markIconStateClean;
- (BOOL)isIconStateDirty;
- (void)removeEmptyList:(id)fp8;
- (id)listContainingLeafIconWithIdentifier:(id)fp8;
- (id)listContainingIcon:(id)fp8;
- (unsigned int)indexOfIconList:(id)fp8;
- (id)listAtIndex:(unsigned int)fp8;
- (id)dockModel;
- (void)dealloc;
- (id)init;
- (Class)listViewClass;
- (Class)listModelClass;

@end

