/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBHUDView.h"

@interface SBRotationLockHUDView : SBHUDView
{
    BOOL _locked;
    BOOL locked;
}

- (BOOL)isLocked;
- (void)setLocked:(BOOL)fp8;
- (id)init;
- (void)_updateLockedImage;

@end

