/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView, UIWindow;

@interface SBScreenFlash : _ABAddressBookCopyLocalizedLabel
{
    UIWindow *_flashWindow;
    UIView *_flashView;
    BOOL _windowVisible;
}

+ (id)sharedInstance;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)flashColor:(id)fp8;
- (void)flash;
- (void)stopFlash;
- (void)_orderWindowFront:(id)fp8 withColor:(id)fp12;
- (void)_orderWindowOut:(id)fp8;
- (void)_tearDown;
- (void)_createUIWithColor:(id)fp8;
- (void)dealloc;

@end

