/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, UIFont;

@interface SBSearchTableViewCell : _ABAddressBookCopyLocalizedLabel
{
    UIFont *_titleFont;
    UIFont *_subtitleFont;
    UIFont *_auxiliaryTitleFont;
    UIFont *_topHitFont;
    NSString *_title;
    NSString *_subtitle;
    NSString *_summary;
    NSString *_auxiliaryTitle;
    NSString *_auxiliarySubtitle;
    BOOL _badged;
    BOOL _starred;
    BOOL _usesAlternateBackgroundColor;
    BOOL _isTopHit;
    BOOL _isBelowTopHit;
    BOOL _isFirstInTableView;
    BOOL _isLastInTableView;
    BOOL _isFirstInSection;
    float _sectionHeaderWidth;
    float _edgeInset;
}

+ (id)inner2xAlternateLineColor;
+ (id)outer2xAlternateLineColor;
+ (id)inner2xAlternateShadowColor;
+ (id)outer2xAlternateShadowColor;
+ (id)inner2xLineColor;
+ (id)outer2xLineColor;
+ (id)inner2xShadowColor;
+ (id)outer2xShadowColor;
+ (id)topLineShadowColor;
+ (id)alternateLineColor;
+ (id)lineColor;
+ (id)alternateBackgroundColor;
+ (id)backgroundColor;
+ (void)initialize;
- (void)setEdgeInset:(float)fp8;
- (float)edgeInset;
- (void)setSectionHeaderWidth:(float)fp8;
- (float)sectionHeaderWidth;
- (void)setFirstInSection:(BOOL)fp8;
- (BOOL)isFirstInSection;
- (BOOL)isLastInTableView;
- (BOOL)isFirstInTableView;
- (void)setBelowTopHit:(BOOL)fp8;
- (BOOL)isBelowTopHit;
- (void)setTopHit:(BOOL)fp8;
- (BOOL)isTopHit;
- (void)setUsesAlternateBackgroundColor:(BOOL)fp8;
- (BOOL)usesAlternateBackgroundColor;
- (void)setStarred:(BOOL)fp8;
- (BOOL)isStarred;
- (void)setBadged:(BOOL)fp8;
- (BOOL)isBadged;
- (void)setAuxiliarySubtitle:(id)fp8;
- (id)auxiliarySubtitle;
- (void)setAuxiliaryTitle:(id)fp8;
- (id)auxiliaryTitle;
- (void)setSummary:(id)fp8;
- (id)summary;
- (void)setSubtitle:(id)fp8;
- (id)subtitle;
- (id)title;
- (id)_scriptingInfo;
- (void)drawRect:(struct CGRect)fp8;
- (void)_drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (BOOL)_drawsContent;
- (void)setLastInTableView:(BOOL)fp8;
- (void)setFirstInTableView:(BOOL)fp8;
- (void)_updateOpacity;
- (void)setTitle:(id)fp8;
- (void)clearContents;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

