/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SPSearchAgentDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class SBSearchView;

@interface SBSearchController : _ABAddressBookCopyLocalizedLabel <UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate, SPSearchAgentDelegate>
{
    SBSearchView *_searchView;
    BOOL _reloadingTableContent;
    BOOL _resultsUpdated;
    void *_addressBook;
}

- (id)searchView;
- (id)_auxiliaryTitleForABRecordID:(int)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)searchAgentClearedResults:(id)fp8;
- (void)searchAgentUpdatedResults:(id)fp8;
- (void)_updateTableContents;
- (void)_tableViewDidFadeOut:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)scrollViewDidScroll:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayHeaderView:(id)fp12 forSection:(int)fp16;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (BOOL)tableView:(id)fp8 wantsHeaderForSection:(int)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (void)_deselect;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)_populateCell:(id)fp8 withSearchResultAtIndex:(int)fp12 inSection:(id)fp16;
- (int)numberOfSectionsInTableView:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)searchBarSearchButtonClicked:(id)fp8;
- (void)searchBar:(id)fp8 textDidChange:(id)fp12;
- (BOOL)shouldShowKeyboardOnScroll;
- (void)setSearchView:(id)fp8;
- (void)scrollViewIsScrollingHorizontallyInSearchView;
- (void)controllerWasDeactivated;
- (void)controllerWasActivated;
- (void)updateResultsIfNecessary;
- (void)dealloc;
- (id)init;

@end

