/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableArray, SBNoResultsView, UILabel, UISearchBar, UITableView, UIView;

@interface SBSearchView : _ABAddressBookCopyLocalizedLabel
{
    UISearchBar *_searchBar;
    UITableView *_tableView;
    UILabel *_noResultsLabel;
    SBNoResultsView *_noResultsView;
    UIView *_rootView;
    UIView *_contentView;
    BOOL _isKeyboardAnimatingRotation;
    BOOL _hidesEmptyTableFooter;
    BOOL _translatedKbForScatter;
    BOOL _deferredFirstResponder;
    BOOL _observingForKeyboardOnScreen;
    BOOL _observingForKeyboardOffScreen;
    BOOL _removeView;
    NSMutableArray *_keyboardCompletionBlocks;
}

- (void)setRootView:(id)fp8;
- (id)rootView;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (id)tableView;
- (id)searchBar;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)unscatterAnimationDidStop;
- (void)unscatter:(BOOL)fp8 delay:(double)fp12;
- (void)scatter:(BOOL)fp8 delay:(double)fp12;
- (void)cleanupKeyboardForScatterIfNecessary;
- (void)_resetKeyboardTransformForScatter;
- (void)_resetContentViewTransform;
- (void)_setDistantContentViewTransform;
- (void)setShowingNoResultsText:(BOOL)fp8;
- (void)keyboardDidShow:(id)fp8;
- (void)keyboardDidHide:(id)fp8;
- (void)finishBecomingFirstResponderIfNecessary;
- (void)setShowsKeyboard:(BOOL)fp8 animated:(BOOL)fp12 shouldDeferResponderStatus:(BOOL)fp16 completionBlock:(id)fp(null);
- (void)setShowsKeyboard:(BOOL)fp8 animated:(BOOL)fp12 shouldDeferResponderStatus:(BOOL)fp16;
- (void)setShowsKeyboardAnimated:(BOOL)fp8 completionBlock:(id)fp(null);
- (void)setShowsKeyboard:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)isKeyboardVisible;
- (void)__searchFieldDidResignFirstResponder;
- (void)_stopObservingForKeyboardOnScreen;
- (void)_startObservingForKeyboardOnScreen;
- (void)_stopObservingForKeyboardOffScreen;
- (void)_startObservingForKeyboardOffScreen;
- (void)__becomeFirstResponder;
- (BOOL)__isFirstResponder;
- (BOOL)isKeyboardMinimized;
- (id)_keyboard;
- (Class)searchBarClass;
- (Class)tableViewClass;
- (void)_layoutNoResultsView;
- (void)layoutFooterView;
- (float)_footerHeight;
- (void)setHidesEmptyTableFooter:(BOOL)fp8;
- (void)layoutCornerView;
- (void)_resetLastCellInTableView;
- (void)setShowsNoResultsView:(BOOL)fp8;
- (void)scrollViewIsScrollingHorizontally;
- (void)setFrame:(struct CGRect)fp8;
- (void)didMoveToWindow;
- (void)dealloc;
- (void)hideAllSubviewsOfTableView;
- (id)initWithFrame:(struct CGRect)fp8 withContent:(id)fp24 onWallpaper:(id)fp28;
- (void)removeTableView;
- (void)addTableView;
- (id)initWithFrame:(struct CGRect)fp8;

@end

