/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SPDaemonQueryDelegate-Protocol.h"

@class CPLRUDictionary, NSDate, NSObject<OS_dispatch_semaphore>, NSTimer;

@interface SBSearchModel : _ABAddressBookCopyLocalizedLabel <SPDaemonQueryDelegate>
{
    NSTimer *_clearSearchTimer;
    NSDate *_clearSearchDate;
    CPLRUDictionary *_cachedImages;
    NSObject<OS_dispatch_semaphore> *_cacheLock;
}

+ (id)sharedInstance;
- (id)_customImageForPath:(id)fp8;
- (id)imageForDisplayIdentifier:(id)fp8 spotlightKey:(id)fp12;
- (id)imageViewForDomain:(unsigned int)fp8 andDisplayID:(id)fp12;
- (id)_imageForDomain:(unsigned int)fp8 andDisplayID:(id)fp12;
- (void)handleOptionsForNewSections:(id)fp8;
- (id)launchingURLForResult:(id)fp8 withDisplayIdentifier:(id)fp12 andSection:(id)fp16;
- (void)_updateClearSearchTimerFireDate;
- (void)startClearSearchTimer;
- (void)_clearSearchTimerFired;
- (void)resetClearSearchTimer;
- (void)dealloc;
- (id)init;

@end

