/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary, SBApplication, UIView, UIWindow;

@interface SBSheetController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_appToSheetMap;
    UIWindow *_presentationWindow;
    SBApplication *_topHostedApp;
    UIView *_topHostedAppView;
}

+ (id)sharedInstance;
- (BOOL)sheetWantsProgress;
- (id)applicationForTopSheet;
- (void)dismissSheetsForApplication:(id)fp8;
- (void)dismissAllSheets;
- (BOOL)isShowingSheetsForApplication:(id)fp8;
- (BOOL)isShowingSheets;
- (void)sendStatusBarOrientationWillChangeToSheets:(int)fp8 duration:(float)fp12;
- (void)dismissRemoteViewIdentifier:(id)fp8 forApplication:(id)fp12 animated:(BOOL)fp16;
- (BOOL)presentRemoteViewIdentifier:(id)fp8 asSheetForApplication:(id)fp12 requireTopApplication:(BOOL)fp16 animated:(BOOL)fp20;
- (void)dismissSheetView:(id)fp8 animated:(BOOL)fp12;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_tearDownSheet:(id)fp8;
- (void)presentSheetView:(id)fp8 animated:(BOOL)fp12;
- (void)_positionFakeStatusBarView:(id)fp8 forOrientation:(int)fp12;
- (void)dealloc;
- (id)init;

@end

