/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBApplication, SBFakeStatusBarView, SBProxyRemoteView;

@interface SBSheetView : _ABAddressBookCopyLocalizedLabel
{
    SBProxyRemoteView *_remoteProxyView;
    SBApplication *_app;
    SBFakeStatusBarView *_fakeStatusBarView;
    BOOL _wasPresentedAnimated;
}

- (void)dealloc;
- (void)noteSheetDidEnd;
- (BOOL)wasPresentedAnimated;
- (id)fakeStatusBarView;
- (id)application;
- (id)remoteViewIdentifier;
- (id)initWithRemoteViewIdentifier:(id)fp8 application:(id)fp12 shouldFakeStatusBar:(BOOL)fp16 wasPresentedAnimated:(BOOL)fp20;

@end

