/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBSlidingViewHighlight, UIControl, UIView, UIWindow;

@interface SBShowcaseController : _ABAddressBookCopyLocalizedLabel
{
    UIWindow *_hostWindow;
    UIView *_hostView;
    UIWindow *_showcaseWindow;
    UIView *_rootView;
    UIView *_contentView;
    UIControl *_blockingView;
    UIView *_clippingView;
    UIView *_showcaseView;
    UIView *_topShadowView;
    UIView *_bottomShadowView;
    UIView *_hidingView;
    SBSlidingViewHighlight *_separator;
    float _revealAmount;
    int _orientation;
    BOOL _isAnimating;
    int _pendingRevealMode;
    id <SBShowcaseControllerOwner> _owner;
    id <SBShowcaseViewControllerProtocol> _showcaseViewController;
}

+ (float)fullRevealAmount;
- (void)setAnimating:(BOOL)fp8;
- (BOOL)isAnimating;
- (float)revealAmount;
- (id)window;
- (int)orientation;
- (id)hidingView;
- (id)hostView;
- (id)blockingView;
- (id)showcase;
- (void)setOwner:(id)fp8;
- (id)owner;
- (BOOL)transferOwnershipToOwner:(id)fp8;
- (void)noteRevealModeWillChange:(int)fp8;
- (void)dismissWithFadeOfDuration:(double)fp8;
- (void)dismissWithAnimation:(BOOL)fp8;
- (void)updateRevealMode:(int)fp8 withBlock:(id)fp(null);
- (float)_showcaseRevealedAmount;
- (struct CGRect)_hostViewFrame;
- (struct CGRect)_adjustedContentFrameForFrame:(struct CGRect)fp8;
- (struct CGRect)_portraitAdjustedFrameForFrame:(struct CGRect)fp8;
- (struct CGRect)_contentFrame;
- (struct CGAffineTransform)_rootTransform;
- (void)setHidingView:(id)fp8;
- (void)setOrientation:(int)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8;
- (void)didDisappear;
- (void)willDisappear;
- (void)didAppear;
- (void)willAppear;
- (float)_separatorAlphaForRevealAmount:(float)fp8;
- (struct CGRect)_visibleShowcaseBounds;
- (void)_updateShowcase;
- (int)revealMode;
- (void)setRevealMode:(int)fp8;
- (void)_updateShowcaseWindowLevel;
- (float)_showcaseWindowLevel;
- (void)setAlpha:(float)fp8;
- (void)setHidden:(BOOL)fp8;
- (float)revealAmountForMode:(int)fp8;
- (float)bottomBarHeight;
- (struct CGRect)showcaseViewFrame;
- (void)setRevealAmount:(float)fp8;
- (void)setHostView:(id)fp8;
- (void)setShowcase:(id)fp8;
- (void)dealloc;
- (id)init;

@end

