/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBShowcaseViewControllerProtocol <NSObject>
- (void)setRevealMode:(int)fp8;
- (int)revealMode;
- (void)setShowcase:(id)fp8;
- (id)showcase;
- (BOOL)activateIgnoringTouches;
- (float)revealAmountForMode:(int)fp8;
- (float)bottomBarHeight;
- (BOOL)shouldShowLockStatusBarTime;
- (BOOL)expectsFaceContact;
- (void)revealModeWillChange:(int)fp8;
- (void)viewDidRotateFromInterfaceOrientation:(int)fp8;
- (void)viewWillAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)viewWillRotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (id)view;
@end

