/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBShowcaseContext : _ABAddressBookCopyLocalizedLabel
{
    int _appOrientation;
    int _showcaseOrientation;
    struct CGAffineTransform _portraitRelativeViewTransform;
    struct CGAffineTransform _currentReleativeViewTransform;
    BOOL _onSpringBoard;
    BOOL _onApp;
    float _offset;
}

- (void)setOffset:(float)fp8;
- (float)offset;
- (void)setOnApp:(BOOL)fp8;
- (BOOL)onApp;
- (void)setOnSpringBoard:(BOOL)fp8;
- (BOOL)onSpringBoard;
- (void)setCurrentReleativeViewTransform:(struct CGAffineTransform)fp8;
- (struct CGAffineTransform)currentReleativeViewTransform;
- (void)setPortraitRelativeViewTransform:(struct CGAffineTransform)fp8;
- (struct CGAffineTransform)portraitRelativeViewTransform;
- (void)setShowcaseOrientation:(int)fp8;
- (int)showcaseOrientation;
- (void)setAppOrientation:(int)fp8;
- (int)appOrientation;

@end

