/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBShowcaseControllerOwner <NSObject>
- (void)showcase:(id)fp8 didTransferOwnershipToOwner:(id)fp12;
- (void)assumeShowcaseOwnership:(id)fp8;
- (void)showcaseWantsToBeDismissed:(id)fp8 animated:(BOOL)fp12;
- (void)showcase:(id)fp8 updateRevealMode:(int)fp12 withBlock:(id)fp(null);
- (BOOL)presentShowcaseViewController:(id)fp8 revealMode:(int)fp12 completion:(id)fp(null);
@end

