/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBSIMLockAlertItem : _ABAddressBookCopyLocalizedLabel
{
    int _status;
    int _okButtonIndex;
    int _unlockButtonIndex;
}

+ (id)alertTitleForStatus:(int)fp8;
+ (id)alertTitleForStatus:(int)fp8 languageCode:(id)fp12;
- (BOOL)reappearsAfterLock;
- (BOOL)reappearsAfterUnlock;
- (BOOL)pendInSetupIfNotAllowed;
- (BOOL)allowInSetup;
- (BOOL)forcesModalAlertAppearance;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)performUnlockAction;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)unlock;
- (void)didDeactivateForReason:(int)fp8;
- (int)status;
- (id)alertTextForLanguageCode:(id)fp8;
- (id)alertTitleForLanguageCode:(id)fp8;
- (BOOL)canUnlock;
- (void)dealloc;
- (void)_resetButtonIndexes;
- (id)initWithStatus:(int)fp8;

@end

