/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class NSString;

@interface SBSIMLockEntryAlertDisplay : SBSlidingAlertDisplay
{
    NSString *_languageCode;
    NSString *_code;
}

- (void)deviceLockViewCancelButtonPressed:(id)fp8;
- (void)deviceLockViewPasscodeEntered:(id)fp8;
- (void)unlock;
- (void)_unlock;
- (void)setupSuccess;
- (void)alertDisplayWillBecomeVisible;
- (BOOL)shouldShowEmergencyCallButton;
- (int)requiredUnlockStyle;
- (void)setupCurrentLockAttemptState;
- (id)label;
- (id)titleText;
- (void)setupFailureState;
- (id)failureLabel;
- (id)failureTitle;
- (void)setupUnlockAttemptState;
- (BOOL)alphanumericKeyboard;
- (id)_pinAttemptsRemainingLabel;
- (id)localizedStringWithKey:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 languageCode:(id)fp24;

@end

