/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : _ABAddressBookCopyLocalizedLabel
{
    BOOL _isInitialUpdate;
    BOOL _isBrickedDevice;
    int _status;
    SBSIMLockAlertItem *_currentAlert;
    SBSIMLockEntryAlert *_lockEntryAlert;
    NSString *_languageCode;
    BOOL _hasHadSIMWhileNotBricked;
    BOOL _wasActivated;
    BOOL _neededUIM;
}

+ (id)sharedInstance;
- (id)languageCode;
- (int)status;
- (void)registerForAlerts;
- (void)_postponementDidChange;
- (void)_telephonyDidRestart;
- (void)_activationDidChange;
- (void)_initialUpdate;
- (void)_externalSIMStatusChanged:(id)fp8;
- (int)pukLockAttemptsRemaining;
- (int)pinLockAttemptsRemaining;
- (void)_updateSIMStatus:(struct __CFString *)fp8 withOptions:(struct __CFDictionary *)fp12;
- (void)_tearDownAlertAndUpdateStatus;
- (void)_handlePromptForUnlock;
- (void)airplaneModeChanged;
- (void)_tryToUpdateStatus;
- (void)_updateToStatus:(int)fp8;
- (void)attemptUnlock;
- (void)repopAlert;
- (void)_setupAppActivationStateDidChange:(id)fp8;
- (BOOL)_shouldSuppressAlert;
- (void)alertItemDismissed:(id)fp8;
- (void)lockEntryAlertDismissed:(id)fp8;
- (int)_statusFromCT;
- (int)_CTToSBSIMStatus:(struct __CFString *)fp8;
- (BOOL)_hopelesslyPUKLocked;
- (void)dealloc;
- (id)init;

@end

