/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView;

@interface SBSlidingViewHighlight : _ABAddressBookCopyLocalizedLabel
{
    UIImageView *_leftHighlight;
    UIImageView *_rightHighlight;
    struct CGRect _notchRect;
}

+ (id)highlightImage;
+ (float)defaultHeight;
- (void)dealloc;
- (void)setNotchRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8 notchRect:(struct CGRect)fp24;
- (id)initWithFrame:(struct CGRect)fp8;

@end

