/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertView.h"

#import "SBDeviceLockViewOwner-Protocol.h"

@class SBDeviceLockView, SBEmergencyCallView, SBWallpaperView, UIImage, UIStatusBar, UIView;

@interface SBSlidingAlertDisplay : SBAlertView <SBDeviceLockViewOwner>
{
    SBWallpaperView *_backgroundView;
    UIImage *_defaultDesktopImage;
    UIView *_topBar;
    UIView *_bottomBar;
    UIView *_overlayView;
    SBDeviceLockView *_deviceLockView;
    SBEmergencyCallView *_emergencyCallView;
    UIView *_emergencyCallTopBar;
    BOOL _playKeyboardClicks;
    unsigned int _animatingEmergencyCall:1;
    unsigned int _animatingIn:1;
    unsigned int _animatingOut:1;
    unsigned int _animatingDeviceLock:1;
    unsigned int _showingDeviceLock:1;
    unsigned int _showingDeviceUnlockFailure:1;
    unsigned int _isDisplayingWallpaper:1;
    int _currentOrientation;
    UIStatusBar *_fakeStatusBarForSlideToDeviceLock;
    id _lockAnimationCompletionHandler;
    id <SBSlidingAlertDisplayDelegate> _delegate;
}

+ (void)setDisplayPropertiesForActivationOfAlert:(id)fp8;
+ (id)bottomBarForInstance:(id)fp8;
+ (id)topBarForInstance:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)shouldAddClippingViewDuringRotation;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (id)backgroundView;
- (id)topBar;
- (id)bottomBar;
- (void)emergencyCallWasRemoved:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)animateFromEmergencyCallWithDuration:(float)fp8;
- (void)emergencyCallWasDisplayed;
- (void)animateToEmergencyCall;
- (void)_animateView:(id)fp8 direction:(int)fp12;
- (void)alertWindowResizedFromContentFrame:(struct CGRect)fp8 toContentFrame:(struct CGRect)fp24;
- (void)statusBarFrameChanged:(id)fp8;
- (void)adjustForDoubleHighStatusBarIfNecessary;
- (void)_adjustForDoubleHighStatusBar:(BOOL)fp8;
- (void)_updateDeviceLockFrameForDoubleHeightStatusBar:(BOOL)fp8;
- (void)_moveTopBarForDoubleHeightStatusBar:(BOOL)fp8;
- (BOOL)shouldShowEmergencyCallButton;
- (int)requiredUnlockStyle;
- (void)deviceLockViewEmergencyCallButtonPressed:(id)fp8;
- (void)deviceLockViewCancelButtonPressed:(id)fp8;
- (void)deviceLockViewPasscodeEntered:(id)fp8;
- (void)deviceLockViewPasscodeDidChange:(id)fp8;
- (void)deviceLockViewWillAnimateMaximization:(id)fp8;
- (void)deviceLockViewWillAnimateMinimization:(id)fp8;
- (void)deviceUnlockCanceled;
- (void)_entryFinishedWithPassword:(id)fp8;
- (BOOL)isDisplayingErrorStatus;
- (BOOL)shouldUseTransparentStatusBar;
- (void)removeBlockedStatus;
- (void)showBlockedStatus;
- (BOOL)shouldShowBlockedRedStatus;
- (void)deviceUnlockFailed;
- (void)deviceUnlockSucceeded;
- (void)animateToHidingDeviceLockFinished;
- (void)animateToShowingDeviceLockFinished;
- (void)_animateToHidingOrShowingDeviceLockFinished;
- (void)animateToShowingDeviceLock:(BOOL)fp8 duration:(float)fp12;
- (void)setShowingDeviceLock:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setShowingDeviceLock:(BOOL)fp8;
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12 completion:(id)fp(null) outDuration:(void)fp16;
- (void)setShowingDeviceLock:(BOOL)fp8 duration:(float)fp12 completion:(id)fp(null);
- (id)deviceLockView;
- (void)_updateOverlayViewFrame;
- (BOOL)bottomBarIsVisible;
- (BOOL)topBarIsVisible;
- (void)_zoomOutDeviceLockViewWithDelay:(double)fp8;
- (void)_zoomInDeviceLockViewWithDelay:(double)fp8;
- (BOOL)_shouldZoomDeviceLockView;
- (BOOL)isShowingDeviceLock;
- (void)layoutForInterfaceOrientation:(int)fp8;
- (void)alertDisplayWillBecomeVisible;
- (void)animateDisplayIn:(float)fp8 middleDelay:(float)fp12 animateStatusBar:(BOOL)fp16;
- (void)performAnimateDisplayIn;
- (void)beginAnimatingDisplayIn:(BOOL)fp8;
- (void)performAdditionalDismissAnimations;
- (void)dismiss;
- (float)durationForOthersActivation;
- (BOOL)isReadyToBeRemovedFromView;
- (void)setMiddleContentAlpha:(float)fp8;
- (void)_fadeOutCompleted:(id)fp8;
- (void)_fadeOutCompletedWithDisplayDisablingIconUnscatter:(BOOL)fp8;
- (void)animateOut;
- (void)_beginDismissAnimationAffectingWorkspace:(BOOL)fp8;
- (int)currentOrientation;
- (BOOL)isAnimatingOut;
- (BOOL)shouldAnimateIconsOut;
- (BOOL)shouldAnimateIconsIn;
- (void)finishedAnimatingOut;
- (void)finishedAnimatingIn;
- (void)updateDesktopImage:(id)fp8;
- (BOOL)isShowingWallpaper;
- (BOOL)showsDesktopImage;
- (void)getFrameForTopButton:(struct CGRect *)fp8 bottomButton:(struct CGRect *)fp12;
- (struct CGRect)middleFrame;
- (BOOL)isFullscreen;
- (id)lockBar;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)_defaultDesktopImage;
- (void)_showUnlockFailedIndicator;
- (void)_clearUnlockFailedIndicator;
- (void)leftNavigationButtonPressed;
- (void)rightNavigationButtonPressed;
- (struct CGAffineTransform)slideBottomBarToVisible:(BOOL)fp8;
- (struct CGAffineTransform)slideTopBarToVisible:(BOOL)fp8;
- (void)updateTopBarBackground;
- (id)_topBarLCDShadow;
- (id)_topBarLCDImage;
- (BOOL)shouldShowBottomBar;
- (BOOL)shouldEnableWirelessLCD;
- (void)_resetStatusTextView;
- (void)_setTopBarImage:(id)fp8 shadowColor:(id)fp12;

@end

