/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUSSDAlert.h"

@interface SBSMSClass0Alert : SBUSSDAlert
{
}

+ (void)defaultAlertTonePrefChanged;
+ (void)playMessageReceived;
+ (BOOL)shouldPlayMessageReceived;
+ (void)registerForAlerts;
- (void)deactivate;
- (id)_initWithString:(id)fp8;
- (void)_registerForNotifications;
- (void)_unregisterForNotifications;

@end

