/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class AVController, NSHashTable, NSMutableArray, NSMutableDictionary, SBUISound;

@interface SBSoundController : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_soundsBySystemSoundIDs;
    AVController *_ringtoneController;
    id _ringtoneObserver;
    SBUISound *_ringtoneSound;
    NSHashTable *_observers;
    unsigned int _pendingCallbacks;
    NSMutableArray *_pendedCallbacks;
}

+ (id)sharedInstance;
- (void)_enqueueCallback:(id)fp(null);
- (void)_endPendingCallbacksBlock;
- (void)_beginPendingCallbacksBlock;
- (void)_soundDidFinishPlaying:(id)fp8;
- (void)_soundDidStartPlaying:(id)fp8;
- (void)_ringerStateChanged:(id)fp8;
- (BOOL)_playRingtone:(id)fp8;
- (BOOL)_playSystemSound:(id)fp8;
- (void)_killRingtone;
- (void)_cleanupSystemSound:(unsigned long)fp8 andKill:(BOOL)fp12;
- (BOOL)handleVolumeButtonDownEvent;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)stopAllSounds;
- (BOOL)_stopAllSounds;
- (void)stopSound:(id)fp8;
- (BOOL)playSound:(id)fp8 completion:(id)fp(null);
- (BOOL)playSound:(id)fp8;
- (BOOL)isPlaying:(id)fp8;
- (BOOL)isPlayingAnySound;
- (void)dealloc;
- (id)init;

@end

