/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@class NSTimer;

@interface SBSoftwareUpdateForcedInstallAlertItem : SBBaseSoftwareUpdateAlertItem
{
    NSTimer *_timer;
    unsigned int _timeLeftUntilInstall;
    BOOL _delayOnDismissForNonUserAction;
    BOOL _delayAfterNextUnlock;
}

- (void)setDelayAfterNextUnlock:(BOOL)fp8;
- (BOOL)delayAfterNextUnlock;
- (void)setDelayOnDismissForNonUserAction:(BOOL)fp8;
- (BOOL)delayOnDismissForNonUserAction;
- (BOOL)dismissOnLock;
- (void)performUnlockAction;
- (BOOL)shouldShowInLockScreen;
- (id)shortLockLabel;
- (id)lockLabel;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)undimsScreen;
- (void)_timerFired;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)willDeactivateForReason:(int)fp8;
- (void)willPresentAlertView:(id)fp8;
- (void)updateBodyText;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)_installUpdate;
- (void)dealloc;
- (id)initWithDescriptor:(id)fp8;

@end

