/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@interface SBSoftwareUpdateVerificationFailedAlertItem : SBBaseSoftwareUpdateAlertItem
{
}

- (BOOL)dismissOnLock;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)shouldShowInLockScreen;
- (BOOL)undimsScreen;
- (BOOL)reappearsAfterLock;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;

@end

