/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "UIWindowDelegate-Protocol.h"

@class UIView, UIWindow;

@interface SBSwitcherPopoverWindowController : _ABAddressBookCopyLocalizedLabel <UIWindowDelegate>
{
    UIWindow *_popoverWindow;
    UIView *_popoverRootView;
    BOOL _popoverVisible;
    id _delegate;
}

+ (id)sharedInstance;
- (BOOL)popoverVisible;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)didRotateFromOrientation:(int)fp8;
- (void)willAnimateRotationToOrientation:(int)fp8;
- (void)cleanupPopover;
- (void)rotatePopoverWindowToOrientation:(int)fp8;
- (void)prepareAndPresentPopoverForFrame:(struct CGRect)fp8 inView:(id)fp24 delegate:(id)fp28 withPresentationBlock:(id)fp(null);
- (id)window;
- (id)rootView;
- (void)dealloc;

@end

