/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSTimer, SBDeviceLockDisableAssertion;

@interface SBSyncController : _ABAddressBookCopyLocalizedLabel
{
    int _restoreState;
    int _resetState;
    int _restoreTimerState;
    NSTimer *_restoreTimer;
    BOOL _showingResetUI;
    BOOL _appsChangedDuringSync;
    int _restoreStartedNotifyToken;
    int _restoreEndedNotifyToken;
    SBDeviceLockDisableAssertion *_disableDeviceLockAssertion;
}

+ (id)sharedInstance;
- (BOOL)isInUse;
- (void)_appInstallationNotification;
- (void)_setupRestoreTimer;
- (void)_restoreTimerFired:(id)fp8;
- (BOOL)_isBackupAgentRunning;
- (void)_invalidateRestoreTimer;
- (void)_resetEnded:(id)fp8;
- (void)_resetStarted:(id)fp8;
- (void)didEndResetting;
- (void)beginResetting:(BOOL)fp8;
- (void)_delayedBeginReset;
- (void)_delayedQuitApplications;
- (int)resetState;
- (BOOL)isResetting;
- (void)didEndRestoring:(int)fp8;
- (void)finishEndRestoring;
- (void)_rebootNow;
- (void)cancelRestoring;
- (void)finishedTerminatingApplications;
- (void)beginRestoring;
- (void)_killApplications;
- (void)_notifyRestoreCanProceed;
- (int)restoreState;
- (BOOL)isRestoring;
- (void)_wirelessSyncEnded:(id)fp8;
- (void)syncSessionDidEnd;
- (void)frontLockedWhenPossible;
- (void)_setRestoreState:(int)fp8;
- (void)stopObserving;
- (void)startObserving;
- (void)dealloc;

@end

