/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBSystemLocalNotificationAlertSheet : _ABAddressBookCopyLocalizedLabel
{
    BOOL _lockToPortrait;
}

- (BOOL)requiresPortraitOrientation;
- (void)setLockToPortrait:(BOOL)fp8;

@end

