/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, NSTimer, SBApplication;

@interface SBSystemLocalNotificationAlert : _ABAddressBookCopyLocalizedLabel
{
    id <SBSystemLocalNotificationAlertDelegate> _delegate;
    SBApplication *_app;
    NSString *_body;
    NSString *_actionLabel;
    NSString *_customLockLabel;
    NSString *_alertLaunchImage;
    BOOL _showActionButton;
    BOOL _hideTitle;
    BOOL _allowSnooze;
    NSTimer *_toneAutoMuteTimer;
    unsigned int _launchButtonIndex;
    unsigned int _snoozeButtonIndex;
    id _context;
}

+ (void)stopPlayingAlertSoundOrTone;
+ (BOOL)isPlayingTone;
+ (void)playSoundWithName:(id)fp8 type:(int)fp12 inApp:(id)fp16 forAlert:(BOOL)fp20;
+ (id)pathForSoundName:(id)fp8 inApp:(id)fp12;
+ (id)alertMatchingContext:(id)fp8;
+ (id)localizedStringFromKey:(id)fp8 defaultValue:(id)fp12 inBundle:(id)fp16 arguments:(id)fp20;
+ (id)presentWithLocalNotification:(id)fp8 application:(id)fp12;
- (id)application;
- (void)setContext:(id)fp8;
- (id)context;
- (void)setAlertLaunchImage:(id)fp8;
- (id)alertLaunchImage;
- (void)setCustomLockLabel:(id)fp8;
- (id)customLockLabel;
- (void)setAllowSnooze:(BOOL)fp8;
- (BOOL)allowSnooze;
- (void)setHideTitle:(BOOL)fp8;
- (BOOL)hideTitle;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (int)alertPriority;
- (id)alertItemNotificationSender;
- (int)alertItemNotificationType;
- (void)stopToneAutoMuteTimer;
- (void)_toneAutoMuteTimerFired;
- (void)startToneAutoMuteTimer;
- (void)dismiss:(int)fp8;
- (void)snoozeOrDismiss;
- (void)snoozeIfPossible;
- (void)willDeactivateForReason:(int)fp8;
- (void)performUnlockAction;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (BOOL)isCriticalAlert;
- (BOOL)shouldShowInEmergencyCall;
- (float)lockLabelFontSize;
- (id)lockLabel;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (Class)alertSheetClass;
- (void)dealloc;
- (id)initWithApplication:(id)fp8 body:(id)fp12 showActionButton:(BOOL)fp16 actionLabel:(id)fp20;

@end

