/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSString, NSTimer, RadiosPreferences, SBAlertItem;

@interface SBTelephonyManager : _ABAddressBookCopyLocalizedLabel
{
    NSString *_cachedCTRegistrationStatus;
    BOOL _emergencyCallsOnly;
    int _registrationStatus;
    void *_suspendDormancyAssertion;
    BOOL _signalStrengthHasBeenSet;
    long _signalStrength;
    long _signalStrengthBars;
    NSString *_operatorName;
    NSString *_lastKnownNetworkCountryCode;
    unsigned int _suspendDormancyEnabled;
    unsigned int _usingWifi:1;
    unsigned int _usingVPN:1;
    unsigned int _iTunesNeedsToRecheckActivation:1;
    unsigned int _pretendingToSearch:1;
    unsigned int _callForwardingIndicator:2;
    BOOL _isNetworkTethering;
    int _numberOfNetworkTetheredDevices;
    unsigned int _hasShownWaitingAlert:1;
    SBAlertItem *_activationAlertItem;
    int _numActivationFailures;
    int _inEmergencyCallbackMode;
    unsigned int _loggingCallAudio:1;
    NSString *_inCallStatusPreamble;
    NSTimer *_inCallTimer;
    RadiosPreferences *_radioPrefs;
    int _needsUserIdentificationModule;
    NSString *_simStatus;
    int _wantsToHideDataIndicators;
    int _modemDataConnectionType;
    BOOL _modemDataConnectionTypeIsKnown;
    BOOL _fallingBackToCellular;
    struct tcp_connection_fallback_watch_s *_cellularFallbackWatcher;
}

+ (id)sharedTelephonyManagerCreatingIfNecessary:(BOOL)fp8;
+ (id)sharedTelephonyManager;
- (void)_wokeFromSleep:(id)fp8;
- (void)noteWirelessModemChanged;
- (void)setIsNetworkTethering:(BOOL)fp8 withNumberOfDevices:(int)fp12;
- (int)numberOfNetworkTetheredDevices;
- (BOOL)isNetworkTethering;
- (void)noteSIMUnlockAttempt;
- (int)registrationCauseCode;
- (BOOL)needsUserIdentificationModule;
- (id)SIMStatus;
- (void)_setSIMStatus:(id)fp8;
- (BOOL)canOnlyMakeEmergencyCalls;
- (int)registrationStatus;
- (id)operatorName;
- (void)operatorBundleChanged;
- (void)setOperatorName:(id)fp8;
- (void)_reallySetOperatorName:(id)fp8;
- (void)_fetchOperatorNameWithCompletion:(id)fp(null);
- (long)signalStrengthBars;
- (long)signalStrength;
- (void)_setSignalStrength:(long)fp8 andBars:(long)fp12;
- (void)carrierBundleChanged;
- (void)_prepareToAnswerCall;
- (BOOL)_pretendingToSearch;
- (void)_stopFakeService;
- (void)_startFakeServiceIfNecessary;
- (void)_cancelFakeService;
- (void)_updateRegistrationNow;
- (void)_setRegistrationStatus:(int)fp8;
- (void)_updateCanOnlyMakeEmergencyCalls;
- (void)_setCachedCTRegistrationStatus:(struct __CFString *)fp8;
- (struct __CFString *)_cachedCTRegistrationStatus;
- (void)postponementStatusChanged;
- (void)_proximityChanged:(id)fp8;
- (void)_headphoneChanged:(id)fp8;
- (void)_resetCTMMode;
- (id)ttyTitle;
- (BOOL)shouldPromptForTTY;
- (void)configureForTTY:(BOOL)fp8;
- (void)exitEmergencyCallbackMode;
- (void)_setIsInEmergencyCallbackMode:(unsigned char)fp8;
- (BOOL)isInEmergencyCallbackMode;
- (BOOL)isEmergencyCallActive;
- (void)_provisioningUpdateWithStatus:(int)fp8;
- (void)_setCurrentActivationAlertItem:(id)fp8;
- (id)copyTelephonyCapabilities;
- (id)copyMobileEquipmentInfo;
- (BOOL)isUsingVPNConnection;
- (void)setIsUsingVPNConnection:(BOOL)fp8;
- (void)setIsUsingWiFiConnection:(BOOL)fp8;
- (BOOL)isTTYEnabled;
- (BOOL)isUsingSlowDataConnection;
- (BOOL)isInAirplaneMode;
- (void)setIsInAirplaneMode:(BOOL)fp8;
- (BOOL)EDGEIsOn;
- (BOOL)cellularRadioCapabilityIsActive;
- (void)_setWantsToHideDataIndicators:(int)fp8;
- (void)_postDataConnectionTypeChanged;
- (int)dataConnectionType;
- (int)_updateModemDataConnectionTypeWithCTInfo:(id)fp8;
- (void)_resetModemConnectionType;
- (void)setNetworkRegistrationEnabled:(BOOL)fp8;
- (BOOL)isNetworkRegistrationEnabled;
- (BOOL)MALoggingEnabled;
- (void)dumpBasebandState:(id)fp8;
- (void)_setIsLoggingCallAudio:(BOOL)fp8;
- (BOOL)isLoggingCallAudio;
- (void)setIncomingVoiceCallsEnabled:(BOOL)fp8;
- (void)unmute;
- (void)disconnectCallAndActivateHeld;
- (void)disconnectCall;
- (void)disconnectAllCalls;
- (void)swapCalls;
- (BOOL)isCallAmbiguous;
- (void)disconnectIncomingCall;
- (BOOL)inCall;
- (BOOL)shouldHangUpOnLock;
- (BOOL)callWouldUseReceiver:(BOOL)fp8;
- (BOOL)inCallUsingReceiverForcingRoutingToReceiver:(BOOL)fp8;
- (BOOL)inCallUsingSpeakerOrReceiver;
- (BOOL)multipleCallsExist;
- (BOOL)outgoingCallExists;
- (BOOL)incomingCallExists;
- (BOOL)heldCallExists;
- (BOOL)activeCallExists;
- (int)callCount;
- (id)allMissedCallsAfterRowID:(long long)fp8;
- (long long)getRowIDOfLastCallInsert;
- (void)_delayedAudioResume;
- (void)updateDisplaySettings:(id)fp8 forOutgoingCallURL:(id)fp12 outURL:(id *)fp16;
- (id)urlWithScheme:(id)fp8 fromDialingNumber:(id)fp12 abUID:(int)fp16 urlPathAddition:(id)fp20 forceAssist:(BOOL)fp24 suppressAssist:(BOOL)fp28 wasAlreadyAssisted:(BOOL)fp32;
- (id)lastKnownNetworkCountryCode;
- (void)_updateLastKnownNetworkCountryCode;
- (void)updateNetworkLocale;
- (BOOL)updateLocale;
- (void)_updateState;
- (void)updateCalls;
- (void)airplaneModeChanged;
- (void)updateAirplaneMode;
- (void)setFastDormancySuspended:(BOOL)fp8;
- (void)setLimitTransmitPowerPerBandEnabled:(BOOL)fp8;
- (void)updateStatusBarCallDuration;
- (void)_phoneActivationStateChanged:(id)fp8;
- (void)updateStatusBarCallState:(BOOL)fp8;
- (id)_phoneApp;
- (void)updateSpringBoard;
- (int)callForwardingIndicator;
- (void)updateCallForwardingIndicator;
- (void)setCallForwardingIndicator:(int)fp8;
- (double)inCallDuration;
- (void)updateTTYIndicator;
- (void)SBTelephonyDaemonRestartHandler;
- (void)_serverConnectionDidError:(CDAnonymousStruct4)fp8;
- (void)_avSystemControllerDidError:(id)fp8;
- (struct __CTServerConnection *)_serverConnection;
- (void)_performQueryInBackground:(id)fp(null) withMainQueueResultHandler:(void)fp8;
- (void)_postStartupNotification;
- (id)init;

@end

