/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBThermalWarningAlertItem : _ABAddressBookCopyLocalizedLabel
{
    id <SBThermalWarningAlertItemDelegate> _delegate;
    int _actionTaken;
}

- (BOOL)unlocksScreen;
- (BOOL)undimsScreen;
- (void)_playPresentationSound;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)didDeactivateForReason:(int)fp8;
- (void)willActivate;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)_autoCoolDown;
- (void)_tryToSendAction:(int)fp8;
- (BOOL)isWaitingForResponse;
- (id)initWithDelegate:(id)fp8;

@end

