/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSObject<OS_dispatch_source>, NSString;

@interface SBThermalWarningSuppressionAssertion : _ABAddressBookCopyLocalizedLabel
{
    id <SBThermalWarningSuppressionAssertionDelegate> _delegate;
    NSString *_reason;
    unsigned int _clientPort;
    NSObject<OS_dispatch_source> *_source;
}

- (id)reason;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)description;
- (void)dealloc;
- (id)initWithClientPort:(unsigned int)fp8 reason:(id)fp12;

@end

