/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIView;

@interface SBThermalLockoutView : _ABAddressBookCopyLocalizedLabel
{
    UIView *_backgroundView;
}

- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

