/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBThermalWarningAlertItemDelegate-Protocol.h"
#import "SBThermalWarningSuppressionAssertionDelegate-Protocol.h"

@class NSDictionary, NSMutableSet;

@interface SBThermalController : _ABAddressBookCopyLocalizedLabel <SBThermalWarningSuppressionAssertionDelegate, SBThermalWarningAlertItemDelegate>
{
    BOOL _sampling;
    double _samplingStartTime;
    NSDictionary *_samplingStartCPUTimesByApp;
    int _sunlightStateToken;
    int _warningAssertionToken;
    int _warningResponseToken;
    NSMutableSet *_warningSuppressionAssertions;
    BOOL _warningSuppressionPreference;
}

+ (void)logThermalEvent:(id)fp8;
+ (id)sharedInstance;
- (void)thermalWarningAlert:(id)fp8 didTriggerAction:(int)fp12;
- (void)thermalWarningAssertionExpired:(id)fp8;
- (BOOL)captureWarningSuppressionAssertionWithPort:(unsigned int)fp8 reason:(id)fp12;
- (void)_didReceiveWarningAction:(int)fp8;
- (void)_calculateAppsCPUTimesWithCompletion:(id)fp(null);
- (void)_killThermallyActiveApplication;
- (void)_killThermallyActiveApplicationGivenCPUTimes:(id)fp8;
- (void)_beginThermalJetsamCPUSampling;
- (void)respondToCurrentThermalCondition;
- (void)showThermalAlertIfNecessary;
- (void)startListeningForThermalEvents;
- (void)dealloc;
- (id)init;

@end

