/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

@class SBApplication;

@interface SBToAppWorkspaceTransaction : SBWorkspaceTransaction
{
    SBApplication *_toApp;
    BOOL _activateSuspended;
    double _watchdogExtension;
    BOOL _fromAssistant;
    SBApplication *_toApplication;
}

- (id)toApplication;
- (void)_commit;
- (void)_captureApplicationData:(id)fp8;
- (BOOL)_shouldBeWatchdogged:(id *)fp8;
- (double)_watchdogInterval;
- (void)_transactionComplete;
- (void)toggleStatusBarForCleanup;
- (void)performToAppStateCleanup;
- (BOOL)shouldAnimateOrientationChangeOnCompletion;
- (BOOL)shouldDismissShowcase;
- (void)setToApplication:(id)fp8;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
- (BOOL)shouldHideSpringBoardStatusBarOnCleanup;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 toApplication:(id)fp16;

@end

