/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBPolygon;

@interface SBTouchTemplate : _ABAddressBookCopyLocalizedLabel
{
    SBPolygon *m_template;
    SBPolygon *m_candidate;
    unsigned int m_transformType;
    float m_acceptFactor;
}

- (void)setAcceptFactor:(float)fp8;
- (float)acceptFactor;
- (void)setTransformType:(unsigned int)fp8;
- (unsigned int)transformType;
- (BOOL)acceptPolygon:(id)fp8;
- (BOOL)acceptPoints:(struct CGPoint *)fp8 count:(unsigned int)fp12;
- (unsigned int)pointCount;
- (void)dealloc;
- (id)initWithPoints:(struct CGPoint *)fp8 count:(unsigned int)fp12;

@end

