/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableDictionary;

@interface SBTransientSettings : _ABAddressBookCopyLocalizedLabel
{
    NSMutableDictionary *_transientSettings;
    BOOL _dirty;
}

+ (id)sharedInstance;
- (void)_load;
- (id)_path;
- (void)save;
- (void)reload;
- (id)objectForKey:(id)fp8;
- (void)setValue:(id)fp8 forKey:(id)fp12;
- (void)dealloc;
- (id)init;

@end

