/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

#import "SBUIFullscreenAnimationViewDelegate-Protocol.h"

@class SBUISlideAppTransitionView;

@interface SBUISlideAppTransitionController : SBUIAnimationController <SBUIFullscreenAnimationViewDelegate>
{
    SBUISlideAppTransitionView *_transitionView;
    double _animationDelay;
    double _animationDuration;
    double _initiationTime;
}

- (void)appTransitionViewAnimationDidStop:(id)fp8;
- (void)appTransitionView:(id)fp8 animationWillStartWithDuration:(double)fp12 afterDelay:(double)fp20;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;

@end

