/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

@class UIView;

@interface SBUIAnimationZoomDownApp : SBUIAnimationController
{
    UIView *_viewToAnimate;
    BOOL _animateBanner;
    CDAnonymousStruct3 _fakeStatusBarInfo;
}

- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (float)endZoomScale;
- (double)animationDelay;
- (double)animationStartTime;
- (double)animationDuration;
- (void)_prepareAnimation;
- (id)appContext;
- (BOOL)prefersLayerHostSnapshot;
- (CDAnonymousStruct3)fakeStatusBarInfoWithStartEffectivelyHidden:(BOOL)fp8 endStyle:(int)fp12 endOrientation:(int)fp16;
- (void)dealloc;
- (id)initWithDeactivatingApp:(id)fp8;

@end

