/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBUIPluginControllerHost <NSObject>
- (void)uiPlugin:(id)fp8 ignoresKeyboardAvoidance:(BOOL)fp12;
- (void)uiPlugin:(id)fp8 forceUpdateToInterfaceOrientation:(int)fp12 animated:(BOOL)fp16;
- (void)uiPluginUserEventOccurred:(id)fp8;
- (BOOL)uiPlugin:(id)fp8 launchApplicationWithBundleID:(id)fp12 openURL:(id)fp16;
- (BOOL)uiPlugin:(id)fp8 openURL:(id)fp12;
- (BOOL)uiPluginAttemptDeviceUnlock:(id)fp8 withPassword:(id)fp12 lockViewOwner:(id)fp16;
- (void)uiPlugin:(id)fp8 setExpectsFaceContact:(BOOL)fp12;
- (BOOL)uiPluginExpectsFaceContact:(id)fp8;
- (void)uiPlugin:(id)fp8 isNowRunning:(BOOL)fp12;
- (void)uiPluginWantsDismissal:(id)fp8 withAnimation:(BOOL)fp12;
- (void)uiPluginWantsSizeUpdate:(id)fp8 revealMode:(int)fp12 withBlock:(id)fp(null);
- (BOOL)uiPluginWantsActivation:(id)fp8 forEvent:(int)fp12 revealMode:(int)fp16 completion:(id)fp(null);
@end

