/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBUIAnimationControllerDelegate <NSObject>
- (void)animationControllerDidFinishAnimation:(id)fp8;
- (void)animationController:(id)fp8 didCommitAnimation:(BOOL)fp12 withDuration:(double)fp16 afterDelay:(double)fp24;
- (void)animationController:(id)fp8 willBeginAnimation:(BOOL)fp12;
@end

