/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BKSApplicationActivationAssertion, SBActivationContext, SBApplication, UIView, UIWindow;

@interface SBUIAnimationController : _ABAddressBookCopyLocalizedLabel
{
    UIWindow *_transitionWindow;
    UIView *_transitionContainer;
    SBApplication *_activatingApp;
    SBApplication *_deactivatingApp;
    SBActivationContext *_activatingContext;
    SBActivationContext *_deactivatingContext;
    BKSApplicationActivationAssertion *_activationAssertion;
    id <SBUIAnimationControllerDelegate> _delegate;
    id _commitBlock;
    int _animationState;
    BOOL _cancelOnNextSuspendIfNecessary;
    BOOL _didDisableUserInteraction;
    BOOL _didNotifyDelegateOfCompletion;
}

+ (id)_transitionWindow;
+ (id)animationWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;
+ (id)animation;
- (void)setCancelOnNextSuspendIfNecessary:(BOOL)fp8;
- (BOOL)cancelOnNextSuspendIfNecessary;
- (void)setDeactivatingContext:(id)fp8;
- (id)deactivatingContext;
- (void)setActivatingContext:(id)fp8;
- (id)activatingContext;
- (void)setActivationAssertion:(id)fp8;
- (id)activationAssertion;
- (void)setCommitBlock:(id)fp(null);
- (id)commitBlock;
- (void)setDeactivatingApp:(id)fp8;
- (id)deactivatingApp;
- (void)setActivatingApp:(id)fp8;
- (id)activatingApp;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)containerView;
- (void)__cleanupAnimation;
- (void)_noteAnimationDidFinish:(BOOL)fp8;
- (void)_notifyDelegateOfCompletion;
- (void)_noteAnimationDidCommit:(BOOL)fp8 withDuration:(double)fp12 afterDelay:(double)fp20;
- (void)_cleanupAnimation;
- (void)_cancelAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)fp8;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (id)_animationIdentifier;
- (BOOL)_willAnimate;
- (void)endAnimation;
- (BOOL)waitingToStart;
- (void)beginAnimation;
- (void)_applicationActivationStateDidChange;
- (void)_applicationDependencyStateChanged;
- (void)_evaluateProgressConditions;
- (void)__cancelAnimation;
- (void)__startAnimation;
- (void)_releaseActivationAssertion;
- (void)_setAnimationState:(int)fp8;
- (BOOL)_isNullAnimation;
- (BOOL)animating;
- (int)_animationState;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8 deactivatingApp:(id)fp12;
- (id)init;

@end

