/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol SBUIFullscreenAnimationViewDelegate
- (void)appTransitionViewAnimationDidStop:(id)fp8;
- (void)appTransitionView:(id)fp8 animationWillStartWithDuration:(double)fp12 afterDelay:(double)fp20;
@end

