/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertView.h"

@class UIView;

@interface SBUIFullscreenAlertViewAdapter : SBAlertView
{
    BOOL _revealedContentBeneathForDismiss;
    UIView *_alertView;
}

- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)alertWindowResizedFromContentFrame:(struct CGRect)fp8 toContentFrame:(struct CGRect)fp24;
- (void)setShouldAnimateIn:(BOOL)fp8;
- (void)dismiss;
- (void)updateSpringBoardInPreparationForTransparentDismiss;
- (void)viewAnimatedOut;
- (BOOL)shouldAnimateIconsIn;
- (void)alertDisplayWillBecomeVisible;
- (BOOL)displaysAboveStatusBar;
- (BOOL)isReadyToBeRemovedFromView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 andContentView:(id)fp24;
- (id)_alertAdapter;

@end

