/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationController.h"

@class UIView;

@interface SBUIAnimationZoomUpApp : SBUIAnimationController
{
    UIView *_viewToAnimate;
    UIView *_contextHostView;
    BOOL _requiresHostView;
    BOOL _activateBeforeHosting;
    BOOL _animateBanner;
    BOOL _doFadeInsteadOfZoom;
    CDAnonymousStruct3 _fakeStatusBarInfo;
    BOOL _fadeOrScatterSpringBoardIfNecessary;
}

- (void)setFadeOrScatterSpringBoardIfNecessary:(BOOL)fp8;
- (BOOL)fadeOrScatterSpringBoardIfNecessary;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (CDAnonymousStruct3)fakeStatusBarInfoWithStartStyle:(int)fp8 startOrientation:(int)fp12;
- (void)dealloc;
- (id)initWithActivatingApp:(id)fp8;

@end

