/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBUIActiveOrientationObserver <NSObject>
- (void)activeInterfaceOrientationDidChangeToOrientation:(int)fp8 willAnimateWithDuration:(double)fp12 fromOrientation:(int)fp20;
- (void)activeInterfaceOrientationWillChangeToOrientation:(int)fp8;
@end

