/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBUIRootView : _ABAddressBookCopyLocalizedLabel
{
    BOOL _animatingAlpha;
}

- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)setAlpha:(float)fp8;
- (void)_actuallySetAlpha:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

