/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBUIUserAgent <NSObject>
- (void)setMinimumBacklightLevel:(float)fp8 animated:(BOOL)fp12;
- (void)notifyOnNextUserEvent;
- (BOOL)isSBUILoggingEnabled;
- (void)removeActiveInterfaceOrientationObserver:(id)fp8;
- (void)addActiveInterfaceOrientationObserver:(id)fp8;
- (void)activateModalBulletinAlert:(id)fp8;
- (id)modalBulletinAlertHandlerRegistry;
- (BOOL)launchDisplayWithURL:(id)fp8 forCall:(BOOL)fp12 sender:(id)fp16;
- (void)setFlipBackAttributeForSEODisplayWithIdentifier:(id)fp8;
- (void)prepareToAnswerCall;
- (void)stopRinging;
- (void)playRingtoneAtPath:(id)fp8 vibrationPattern:(id)fp12;
- (void)playRingtoneAtPath:(id)fp8;
- (void)setBadgeNumberOrString:(id)fp8 forApplicationWithID:(id)fp12;
- (void)setIdleText:(id)fp8;
- (void)lockAndDimDeviceDisconnectingCallIfNecessary:(BOOL)fp8;
- (void)lockAndDimDevice;
- (BOOL)isIdleTimerDisabledForReason:(id)fp8;
- (void)setIdleTimerDisabled:(BOOL)fp8 forReason:(id)fp12;
- (void)undimScreen;
- (void)dimScreen:(BOOL)fp8;
- (void)updateLockScreenInterfaceIfNecessary;
- (struct CGRect)defaultContentRegionForAwayViewPlugin:(id)fp8 withOrientation:(int)fp12;
- (BOOL)launchFromAwayViewPluginWithURL:(id)fp8 bundleID:(id)fp12 allowUnlock:(BOOL)fp16 animate:(BOOL)fp20;
- (BOOL)canLaunchFromAwayViewPluginWithURL:(id)fp8 bundleID:(id)fp12;
- (BOOL)launchFromSource:(int)fp8 withURL:(id)fp12 bundleID:(id)fp16 allowUnlock:(BOOL)fp20;
- (BOOL)launchFromPushOrLocalBulletin:(id)fp8 origin:(int)fp12;
- (BOOL)launchFromBulletinWithURL:(id)fp8 bundleID:(id)fp12 allowUnlock:(BOOL)fp16 animate:(BOOL)fp20 launchOrigin:(int)fp24;
- (BOOL)canLaunchFromBulletinWithURL:(id)fp8 bundleID:(id)fp12;
- (BOOL)launchApplicationFromSource:(int)fp8 withURL:(id)fp12 options:(id)fp16;
- (BOOL)launchApplicationFromSource:(int)fp8 withDisplayID:(id)fp12 options:(id)fp16;
- (BOOL)canLaunchFromSource:(int)fp8 withURL:(id)fp12 bundleID:(id)fp16;
- (void)openURL:(id)fp8 animateIn:(BOOL)fp12 scale:(float)fp16 start:(double)fp20 duration:(float)fp28 animateOut:(BOOL)fp32;
- (BOOL)openURL:(id)fp8 allowUnlock:(BOOL)fp12 animated:(BOOL)fp16;
- (BOOL)canUserLaunchIcon;
- (BOOL)alertIsActive;
- (BOOL)springBoardIsActive;
- (id)createWallpaperView:(int)fp8;
- (BOOL)homeScreenIsDisplayingWallpaper;
- (int)networkUsageTypeForAppWithDisplayID:(id)fp8;
- (BOOL)lockScreenIsShowing;
- (BOOL)deviceIsTethered;
- (BOOL)deviceIsBlocked;
- (BOOL)deviceIsPasscodeLockedRemotely;
- (BOOL)deviceIsPasscodeLocked;
- (BOOL)deviceIsLocked;
- (BOOL)applicationInstalledForDisplayID:(id)fp8;
- (id)topSuspendedEventsOnlyDisplayID;
- (id)foregroundDisplayID;
- (id)foregroundApplicationDisplayID;
- (int)activeInterfaceOrientation;
- (void)updateInterfaceOrientationIfNecessary;
@end

