/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBUIFullscreenAnimationView : _ABAddressBookCopyLocalizedLabel
{
    id <SBUIFullscreenAnimationViewDelegate> _delegate;
    BOOL _animating;
}

- (BOOL)animating;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)_notifyDelegateThatAnimationIsDone;
- (void)_notifyDelegateAnimationBeganWithDuration:(double)fp8 delay:(double)fp16;
- (void)_animationEnded;
- (void)_animationBegan;
- (void)endTransition;
- (void)beginTransition;
- (void)setToView:(id)fp8;
- (void)setFromView:(id)fp8;

@end

