/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBPluginManager.h"

@class NSMutableDictionary, SBUIPluginHost;

@interface SBUIPluginManager : SBPluginManager
{
    NSMutableDictionary *_uiPlugins;
    SBUIPluginHost *_pendingActivation;
    SBUIPluginHost *_hostPendingActivation;
}

+ (id)sharedInstance;
- (void)setHostPendingActivation:(id)fp8;
- (id)hostPendingActivation;
- (BOOL)overrideScreenDimInterval:(double *)fp8;
- (BOOL)suppressingNotifications;
- (BOOL)overrideInterfaceOrientation:(int *)fp8;
- (BOOL)handleActivationEvent:(int)fp8;
- (void)cancelPendingActivationEvent:(int)fp8;
- (void)prepareForActivationEvent:(int)fp8 afterInterval:(double)fp12;
- (BOOL)wantsActivationEvent:(int)fp8 interval:(double *)fp12;
- (BOOL)handleMenuButtonTap;
- (BOOL)handleMenuButtonDownEvent;
- (id)loadedUIPluginHosts;
- (id)_loadedUIPluginHostsVisible:(BOOL)fp8;
- (id)loadedUIPlugins;
- (BOOL)unloadUIPlugin:(id)fp8 forHost:(id)fp12;
- (id)loadUIPluginNamed:(id)fp8 withHost:(id)fp12;

@end

