/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlert.h"

@class SBAlertView, SBUIFullscreenAlertController;

@interface SBUIFullscreenAlertAdapter : SBAlert
{
    SBUIFullscreenAlertController *_alertController;
    SBAlertView *_alertDisplay;
    BOOL _animatingDeactivation;
}

- (id)description;
- (void)launchSucceeded:(BOOL)fp8;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)fp8;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)handleMenuButtonTap;
- (BOOL)dismissPresentedModalAlertIfNecessary;
- (void)presentAlertModally:(id)fp8;
- (void)alertWindow:(id)fp8 didRotateFromInterfaceOrientation:(int)fp12;
- (void)alertWindow:(id)fp8 willAnimateRotationToInterfaceOrientation:(int)fp12 duration:(double)fp16;
- (void)alertWindow:(id)fp8 willRotateToInterfaceOrientation:(int)fp12 duration:(double)fp16;
- (void)alertWindow:(id)fp8 resizedFromContentFrame:(struct CGRect)fp12 toContentFrame:(struct CGRect)fp28;
- (id)alertController;
- (void)_updateForTransparentDismiss:(id)fp8;
- (void)_pluginViewAnimatedOut:(id)fp8;
- (void)animateViewOut;
- (void)prepareViewToAnimateOut;
- (BOOL)currentlyAnimatingDeactivation;
- (void)setViewShouldAnimateIn:(BOOL)fp8;
- (BOOL)viewDisplaysAboveStatusBar;
- (BOOL)viewIsReadyToBeRemoved;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (void)dealloc;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (BOOL)hasTranslucentBackground;
- (BOOL)allowsEventOnlySuspension;
- (id)initWithAlertController:(id)fp8;

@end

