/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBUIAnimationZoomUpApp.h"

@interface SBUIAnimationZoomUpAppFromPhone : SBUIAnimationZoomUpApp
{
}

- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (CDAnonymousStruct3)fakeStatusBarInfoWithStartStyle:(int)fp8 startOrientation:(int)fp12;
- (void)dealloc;

@end

