/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class AVController, BKSProcessAssertion, NSDictionary, NSObject<OS_dispatch_source>, NSString, NSTimer, UIImage;

@interface SBUserNotificationAlert : _ABAddressBookCopyLocalizedLabel
{
    unsigned int _replyPort;
    NSObject<OS_dispatch_source> *_portWatcher;
    NSObject<OS_dispatch_source> *_expirationTimer;
    BOOL _cleanedUp;
    int _token;
    int _timeout;
    unsigned long _requestFlags;
    NSString *_alertHeader;
    id _alertMessage;
    NSString *_alertMessageDelimiter;
    NSString *_defaultButtonTitle;
    NSString *_alternateButtonTitle;
    NSString *_otherButtonTitle;
    NSString *_soundPath;
    NSDictionary *_avControllerAttributes;
    NSDictionary *_avItemAttributes;
    double _soundRepeatDuration;
    NSTimer *_soundStopTimer;
    id _keyboardTypes;
    id _autocapitalizationTypes;
    id _autocorrectionTypes;
    id _textFieldButtonDisplayDefaultButtonURLs;
    id _textFieldButtonImagePaths;
    id _textFieldTitles;
    id _textFieldValues;
    id _textFieldButtonDisplayTitles;
    id _textFieldButtonDisplayDefaultButtonTitles;
    int _currentTextFieldButtonDisplayIndex;
    double _creationTime;
    int _defaultButtonTag;
    int _unlockActionButtonTag;
    unsigned int _replyFlags;
    int _defaultButtonIndex;
    int _alternateButtonIndex;
    int _otherButtonIndex;
    NSString *_defaultResponseLaunchBundleID;
    unsigned int _cancel:1;
    unsigned int _isActivated:1;
    unsigned int _aboveLock:1;
    unsigned int _hideButtonsInAwayView:1;
    unsigned int _dismissOnLock:1;
    unsigned int _dontDismissOnUnlock:1;
    unsigned int _behavesSuperModally:1;
    unsigned int _allowMenuButtonDismissal:1;
    unsigned int _oneButtonPerLine:1;
    unsigned int _groupsTextFields:1;
    unsigned int _usesUndoStyle:1;
    unsigned int _configuredLocked:1;
    unsigned int _configuredNeedsPasscode:1;
    unsigned int _defaultResponseAppLaunchWaitingForPasscode:1;
    UIImage *_alertImage;
    AVController *_avController;
    BKSProcessAssertion *_processAssertion;
}

- (void)setDefaultResponseLaunchBundleID:(id)fp8;
- (id)defaultResponseLaunchBundleID;
- (void)setAlertImage:(id)fp8;
- (id)alertImage;
- (void)setOtherButtonTitle:(id)fp8;
- (id)otherButtonTitle;
- (void)setAlternateButtonTitle:(id)fp8;
- (id)alternateButtonTitle;
- (void)setDefaultButtonTitle:(id)fp8;
- (id)defaultButtonTitle;
- (void)setAlertMessageDelimiter:(id)fp8;
- (id)alertMessageDelimiter;
- (void)setAlertMessage:(id)fp8;
- (id)alertMessage;
- (void)setAlertHeader:(id)fp8;
- (id)alertHeader;
- (void)setAvItemAttributes:(id)fp8;
- (id)avItemAttributes;
- (void)setAvControllerAttributes:(id)fp8;
- (id)avControllerAttributes;
- (void)setSoundPath:(id)fp8;
- (id)soundPath;
- (void)setTextFieldButtonDisplayDefaultButtonTitles:(id)fp8;
- (id)textFieldButtonDisplayDefaultButtonTitles;
- (void)setTextFieldButtonDisplayTitles:(id)fp8;
- (id)textFieldButtonDisplayTitles;
- (void)setTextFieldValues:(id)fp8;
- (id)textFieldValues;
- (void)setTextFieldTitles:(id)fp8;
- (id)textFieldTitles;
- (void)setTextFieldButtonDisplayDefaultButtonURLs:(id)fp8;
- (id)textFieldButtonDisplayDefaultButtonURLs;
- (void)setTextFieldButtonImagePaths:(id)fp8;
- (id)textFieldButtonImagePaths;
- (void)setAutocorrectionTypes:(id)fp8;
- (id)autocorrectionTypes;
- (void)setAutocapitalizationTypes:(id)fp8;
- (id)autocapitalizationTypes;
- (void)setKeyboardTypes:(id)fp8;
- (id)keyboardTypes;
- (void)didFailToActivate;
- (void)didDeactivateForReason:(int)fp8;
- (void)willDeactivateForReason:(int)fp8;
- (void)noteVolumeOrLockPressed;
- (BOOL)reappearsAfterUnlock;
- (BOOL)reappearsAfterLock;
- (BOOL)behavesSuperModally;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)performUnlockAction;
- (BOOL)_needsDismissalWithClickedButtonIndex:(int)fp8;
- (void)_sendResponse:(int)fp8;
- (void)_textFieldButtonPressed:(id)fp8;
- (void)_setSheetDefaultButtonTitle:(id)fp8;
- (void)cancel;
- (void)_cleanup;
- (void)_setActivated:(BOOL)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)stopSound;
- (void)willActivate;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (int)token;
- (Class)alertSheetClass;
- (void)dealloc;
- (void)updateWithMessage:(id)fp8 requestFlags:(int)fp12;
- (id)initWithMessage:(id)fp8 replyPort:(unsigned int)fp12 requestFlags:(int)fp16 auditToken:(CDAnonymousStruct5)fp20;
- (id)_safeLocalizedValue:(id)fp8 withBundle:(id)fp12;

@end

