/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBUserInstalledApplicationIcon : SBApplicationIcon
{
    BOOL _shouldHaveSash;
}

- (id)badgeTextForLocation:(int)fp8;
- (int)accessoryTypeForLocation:(int)fp8;
- (void)_checkHasBeenLaunchedState;
- (BOOL)_shouldShowSashForNewlyInstalledApp;
- (id)_newlyInstalledSashLabel;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;
- (id)uninstallAlertTitle;
- (id)ratingsAlertRateButtonTitle;
- (id)ratingsAlertSkipTitle;
- (id)ratingsAlertBody;
- (id)ratingsAlertTitle;
- (BOOL)hasBeenSyncedBackToITunes;
- (BOOL)allowsUninstall;
- (id)initWithApplication:(id)fp8;

@end

