/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImage;

@interface SBUserNotificationAlertSheet : _ABAddressBookCopyLocalizedLabel
{
    UIImage *_alertImage;
}

- (void)setAlertImage:(id)fp8;
- (id)alertImage;
- (id)_maskedAlertImage;
- (void)dealloc;
- (void)layout;
- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;

@end

