/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

#import "VSRecognitionSessionDelegate-Protocol.h"
#import "VSSpeechSynthesizerDelegate-Protocol.h"

@class AVController, NSDictionary, NSInvocation, NSMutableArray, NSMutableIndexSet, NSMutableSet, NSTimer, UITextField, UIView, VSRecognitionSession;

@interface SBVoiceControlAlertDisplay : SBSlidingAlertDisplay <VSRecognitionSessionDelegate, VSSpeechSynthesizerDelegate>
{
    VSRecognitionSession *_session;
    BOOL _wasRecognizing;
    BOOL _didConfigureRouting;
    NSInvocation *_postSoundInvocation;
    UIView *_leftFadeView;
    UIView *_rightFadeView;
    UIView *_labelsView;
    int _clipCount;
    int _currentClipNo;
    BOOL _voiceTranscription;
    UITextField *_textField;
    NSMutableArray *_transcripts;
    NSMutableArray *_voiceClips;
    AVController *_avController;
    NSMutableArray *_waves;
    NSMutableSet *_labels;
    int _keywordCount;
    int _lastKeywordIndex;
    NSTimer *_levelTimer;
    NSMutableIndexSet *_occupiedLabelSlots;
    NSDictionary *_locStrings;
    BOOL _labelsOn;
    BOOL _animatingToCall;
    BOOL _didDismiss;
    BOOL _awaitingButtonRelease;
    BOOL _isBecomingVisible;
    BOOL _labelsHaveDisplayed;
}

+ (id)bottomBarForInstance:(id)fp8;
+ (id)bottomLockBarForDisplay:(id)fp8;
- (void)_keywordsChanged:(id)fp8;
- (void)_stopMovingLabels;
- (void)_fadeOutCurrentLabels;
- (void)_startMovingLabels;
- (void)_labelFinishedAnimating:(id)fp8 finished:(id)fp12 label:(id)fp16;
- (void)_startKeywordIfNecessary;
- (void)_startLabelForKeywordAtIndex:(int)fp8 now:(BOOL)fp12 delayStart:(BOOL)fp16;
- (int)_keywordCount;
- (void)_setWaveAlpha:(float)fp8 withDuration:(double)fp12;
- (void)_stopUpdatingLevels;
- (void)_startUpdatingLevels;
- (void)_updateLevels;
- (void)recognitionSession:(id)fp8 didFinishSpeakingFeedbackStringWithError:(id)fp12;
- (void)_speakText:(id)fp8;
- (void)_speakFeedbackText;
- (void)_performConfirmationAction;
- (void)_continueWithRecognitionAction;
- (id)recognitionSession:(id)fp8 openURL:(id)fp12;
- (id)_openVideoURL:(id)fp8;
- (id)_openTelURL:(id)fp8;
- (void)_animateToAwayInCallController;
- (void)_finishedFadingToAwayInCallController;
- (void)recognitionSession:(id)fp8 didCompleteActionWithError:(id)fp12;
- (void)_exitVoiceTranscriptView;
- (void)_playAudioAtPath:(id)fp8;
- (void)_getAudioClipsFromDirectory;
- (void)_startTrancribeAudio;
- (void)_userEnteredTextForVoiceClip:(id)fp8;
- (void)_mediaPlayerDied;
- (void)_promptUserForVoiceTranscription;
- (void)_performNoMatchFound;
- (void)recognitionSessionDidBeginAction:(id)fp8;
- (void)_continueRecognitionAction;
- (BOOL)recognitionSessionWillBeginAction:(id)fp8;
- (void)_resetSession;
- (void)_startSession;
- (void)_playSound:(unsigned long)fp8 synchronously:(BOOL)fp12;
- (BOOL)_attemptPlaySound:(unsigned long)fp8 synchronously:(BOOL)fp12;
- (void)_performSoundCompletionAction;
- (void)_configureRoutingIfNecessary;
- (void)_pickedRouteChanged:(id)fp8;
- (id)_desiredRouteDictionary;
- (void)handleHeadsetButtonUpFromActivation:(BOOL)fp8;
- (void)handleButtonUpCancel;
- (void)_dismissSlightlyLater;
- (void)_dismissIfWeHavent;
- (void)_notifyDeviceTermination;
- (void)_invalidateRouting;
- (void)setMiddleContentAlpha:(float)fp8;
- (void)lockBarUnlocked:(id)fp8;
- (void)alertWillBeDismissed;
- (void)alertDisplayWillBecomeVisible;
- (void)setStatusText:(id)fp8;
- (void)setTitleText:(id)fp8;
- (id)_localizedStringForKey:(id)fp8;
- (BOOL)alphanumericKeyboard;
- (void)dealloc;
- (void)updateDesktopImage:(id)fp8;
- (BOOL)_wasTriggeredByMenu;
- (id)initWithFrame:(struct CGRect)fp8 session:(id)fp24;

@end

