/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class UIImageView;

@interface SBWallpaperView : _ABAddressBookCopyLocalizedLabel
{
    int _orientation;
    int _variant;
    UIImageView *_topGradient;
    UIImageView *_bottomGradient;
    BOOL _usesFilter;
    float _gradientAlpha;
    struct CGRect _wallpaperContentsRect;
}

- (BOOL)usesFilter;
- (float)gradientAlpha;
- (int)variant;
- (int)orientation;
- (void)resetCurrentImageToWallpaper;
- (void)replaceWallpaperWithImage:(id)fp8;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (void)setGradientAlpha:(float)fp8;
- (void)setAlpha:(float)fp8;
- (float)alpha;
- (void)setFilterAlpha:(float)fp8;
- (float)filterAlpha;
- (void)setUsesFilter:(BOOL)fp8;
- (void)setOrientation:(int)fp8 duration:(double)fp12;
- (void)setOrientation:(int)fp8;
- (void)_setOrientation:(int)fp8 duration:(double)fp12 force:(BOOL)fp20;
- (void)_setGradientImagesWithOrientation:(int)fp8;
- (BOOL)_shouldShowGradientOverWallpaper;
- (void)_wallpaperChanged;
- (void)_resetImage;
- (void)setImage:(id)fp8;
- (void)dealloc;
- (id)initWithOrientation:(int)fp8 variant:(int)fp12;

@end

