/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBWaveView : _ABAddressBookCopyLocalizedLabel
{
    float _phaseWidth;
    float _phaseShift;
    float _minAmplitude;
    float _maxAmplitude;
    float _amplitude;
    float _levelDamping;
    double _phaseDuration;
    double _amplitudeChangeTime;
    double _amplitudeChangeDuration;
    float _lastAmplitude;
    float _level;
    BOOL _animating;
}

- (void)_finishedAnimating;
- (void)stopAnimating;
- (void)beginAnimating;
- (float)_amplitudeForLevel:(float)fp8;
- (void)setLevelDamping:(float)fp8;
- (void)setLevel:(float)fp8 animated:(BOOL)fp12;
- (void)setPhaseAnimationDuration:(double)fp8;
- (void)setMaxAmplitude:(float)fp8;
- (void)setMinAmplitude:(float)fp8;
- (void)_setAmplitude:(float)fp8 animated:(BOOL)fp12;
- (float)_currentAmplitude;
- (float)_phaseShift;
- (void)setPhaseShift:(float)fp8;
- (void)setPhaseWidth:(float)fp8;
- (void)setColor:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;

@end

