/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class SBWallpaperView;

@interface SBWallpaperNotchView : _ABAddressBookCopyLocalizedLabel
{
    SBWallpaperView *_wallpaperView;
    CDAnonymousStruct6 _notchInfo;
}

- (void)drawRect:(struct CGRect)fp8;
- (void)setNotchInfo:(CDAnonymousStruct6)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 wallpaperView:(id)fp24 notchInfo:(CDAnonymousStruct6)fp28;

@end

