/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BBWeeAppController-Protocol.h"
#import "BBWeeAppControllerHost-Protocol.h"

@class NSString, UIViewController<BBWeeAppPresentationController>;

@interface SBWeeApp : _ABAddressBookCopyLocalizedLabel <BBWeeAppController, BBWeeAppControllerHost>
{
    id <BBWeeAppController> _weeAppController;
    NSString *_sectionID;
    id <SBWeeAppDelegate> _delegate;
    int _presentationMode;
    UIViewController<BBWeeAppPresentationController> *_presentationController;
    BOOL _sentWillAppear;
    struct {
        unsigned int viewHeight:1;
        unsigned int viewWillAppear:1;
        unsigned int viewDidAppear:1;
        unsigned int viewWillDisappear:1;
        unsigned int viewDidDisappear:1;
        unsigned int willRotate:1;
        unsigned int willAnimateRotation:1;
        unsigned int didRotate:1;
        unsigned int loadPlaceholderView:1;
        unsigned int loadFullView:1;
        unsigned int unloadView:1;
        unsigned int launchURL:1;
        unsigned int launchURLForTapLocation:1;
        unsigned int clearSnapshotImage:1;
        unsigned int host:1;
    } _weeAppFlags;
}

- (void)setPresentationMode:(int)fp8;
- (int)presentationMode;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)sectionID;
- (BOOL)weeApp:(id)fp8 updatePresentationMode:(int)fp12 duration:(float)fp16 delay:(float)fp20;
- (int)weeAppPresentationMode:(id)fp8;
- (BOOL)weeAppWantsNotificationCenterDismissal:(id)fp8;
- (void)weeAppWantsSizeUpdate:(id)fp8;
- (id)presentationControllerForMode:(int)fp8;
- (void)unloadPresentationController;
- (id)currentPresentationController;
- (float)presentationHeight;
- (void)setPresentationView:(id)fp8;
- (void)clearShapshotImage;
- (id)launchURLForTapLocation:(struct CGPoint)fp8;
- (BOOL)wantsTaps;
- (void)unloadView;
- (void)loadFullView;
- (void)loadPlaceholderView;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (float)viewHeight;
- (id)view;
- (id)description;
- (void)dealloc;
- (id)initWithWeeAppController:(id)fp8 sectionID:(id)fp12;

@end

