/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAppToAppWorkspaceTransaction.h"

@interface SBWebAppToWebAppWorkspaceTransaction : SBAppToAppWorkspaceTransaction
{
}

- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (int)_setupMilestonesFrom:(id)fp8 to:(id)fp12;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12 from:(id)fp16 to:(id)fp20;

@end

