/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBulletinLinenBackedCell.h"

@class SBWeeApp, UITapGestureRecognizer, UIView;

@interface SBWeeAppCell : SBBulletinLinenBackedCell
{
    SBWeeApp *_weeApp;
    UIView *_weeAppView;
    BOOL _useTopPadding;
    UITapGestureRecognizer *_tapRecognizer;
}

+ (float)rowHeightForViewHeight:(float)fp8 withTopPadding:(BOOL)fp12;
- (id)weeApp;
- (void)_tapped:(id)fp8;
- (void)prepareForReuse;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)fp8;
- (void)noteDidDisappear;
- (void)noteWillAppear;
- (void)layoutSubviews;
- (void)setUsesTopPadding:(BOOL)fp8;
- (void)setWeeApp:(id)fp8;
- (void)dealloc;
- (id)initWithLinenView:(id)fp8 reuseIdentifier:(id)fp12;

@end

