/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBBulletinFadeOverlayOwner-Protocol.h"

@class SBWeeApp, UIViewController<BBWeeAppPresentationController>;

@interface SBWeeAppPresentationView : _ABAddressBookCopyLocalizedLabel <SBBulletinFadeOverlayOwner>
{
    BOOL _isDismissing;
    UIViewController<BBWeeAppPresentationController> *_viewController;
    SBWeeApp *_weeApp;
}

- (void)setViewController:(id)fp8;
- (id)viewController;
- (void)setWeeApp:(id)fp8;
- (id)weeApp;
- (void)setLinenGradientAlpha:(float)fp8;
- (void)setRasterizesFadeOverlay:(BOOL)fp8;
- (void)dismissWithCompletion:(id)fp(null);
- (void)willMoveToWindow:(id)fp8;
- (void)dealloc;
- (id)initWithWeeApp:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

