/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@class UIWebClip;

@interface SBWebApplicationIcon : SBApplicationIcon
{
    UIWebClip *_webClip;
}

- (void)setWebClip:(id)fp8;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)webClip;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitle;
- (BOOL)allowsUninstall;
- (BOOL)shouldEllipsizeLabel;
- (BOOL)canGenerateImageInBackgroundForFormat:(int)fp8;
- (id)generateIconImage:(int)fp8;
- (void)dealloc;
- (id)initWithApplication:(id)fp8;

@end

