/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBFolderNotchView.h"

@interface SBWoodNotchView : SBFolderNotchView
{
}

+ (id)_squareImageForNotchInfo:(CDAnonymousStruct6)fp8 orientation:(int)fp28;
+ (id)_keyComponentForNotchInfoRect:(struct CGRect)fp8;

@end

