/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "BKSWorkspaceDelegate-Protocol.h"
#import "SBAlertManagerDelegate-Protocol.h"
#import "SBWorkspaceTransactionDelegate-Protocol.h"

@class BKSWorkspace, NSMutableArray, NSObject<OS_dispatch_source>, NSTimer, SBAlertManager, SBWorkspaceEventQueueLockAssertion, SBWorkspaceTransaction;

@interface SBWorkspace : _ABAddressBookCopyLocalizedLabel <BKSWorkspaceDelegate, SBAlertManagerDelegate, SBWorkspaceTransactionDelegate>
{
    BKSWorkspace *_bksWorkspace;
    SBAlertManager *_alertManager;
    SBWorkspaceTransaction *_currentTransaction;
    SBWorkspaceEventQueueLockAssertion *_eventQueueLock;
    NSObject<OS_dispatch_source> *_transactionWatchdog;
    NSTimer *_relaunchTimer;
    NSMutableArray *_applicationsToRelaunch;
}

- (id)alertManager;
- (id)bksWorkspace;
- (id)currentTransaction;
- (void)transactionDidFinish:(id)fp8 success:(BOOL)fp12;
- (void)alertManager:(id)fp8 didDeactivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 willDeactivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 didActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)alertManager:(id)fp8 willActivateAlert:(id)fp12 overAlerts:(id)fp16;
- (void)workspace:(id)fp8 applicationDebugStateChanged:(id)fp12 newState:(BOOL)fp16;
- (void)workspace:(id)fp8 handleStatusBarReturnActionFromApplication:(id)fp12 statusBarStyle:(id)fp16;
- (void)workspace:(id)fp8 handleOpenURL:(id)fp12 fromApplication:(id)fp16;
- (void)workspace:(id)fp8 applicationSuspensionSettingsUpdated:(id)fp12 withSettings:(id)fp16;
- (void)workspace:(id)fp8 applicationSuspended:(id)fp12 withSettings:(id)fp16;
- (void)workspace:(id)fp8 applicationExited:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationDidFailToLaunch:(id)fp12;
- (void)workspace:(id)fp8 applicationActivated:(id)fp12;
- (void)workspace:(id)fp8 applicationDidFinishLaunching:(id)fp12 withInfo:(id)fp16;
- (void)workspace:(id)fp8 applicationDidStartLaunching:(id)fp12;
- (void)workspaceDidResume:(id)fp8;
- (void)workspaceWillResume:(id)fp8;
- (void)workspaceDidSuspend:(id)fp8;
- (void)workspaceWillSuspend:(id)fp8;
- (void)workspace:(id)fp8 applicationDidBecomeReceiver:(id)fp12 fromApplication:(id)fp16;
- (id)workspace:(id)fp8 applicationWillBecomeReceiver:(id)fp12 fromApplication:(id)fp16;
- (void)updateInterruptedByCallSettingsFrom:(id)fp8 to:(id)fp12;
- (BOOL)_applicationExited:(id)fp8 withInfo:(id)fp12;
- (BOOL)_handleSetupExited:(id)fp8;
- (void)_invalidateRelaunchTimer;
- (void)_memoryPressureRelieved:(id)fp8;
- (void)_memoryPressureWarn:(id)fp8;
- (void)_launchNextPendedAutoLaunchApp;
- (void)_scheduleRelaunchTimerIfNecessary;
- (void)_handleBuddyLaunchFinished;
- (id)_applicationForBundleIdentifier:(id)fp8 frontmost:(BOOL)fp12;
- (void)_noteCurrentTransactionFailed:(const char *)fp8;
- (void)setCurrentTransaction:(id)fp8;
- (id)debugDescription;
- (void)dealloc;
- (id)init;

@end

