/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSArray, NSString;

@interface SBWorkspaceEvent : _ABAddressBookCopyLocalizedLabel
{
    NSString *_label;
    id _handler;
    NSArray *_callStackSymbols;
}

+ (id)eventWithLabel:(id)fp8 handler:(id)fp(null);
- (void)setCallStackSymbols:(id)fp8;
- (id)callStackSymbols;
- (void)setHandler:(id)fp(null);
- (id)handler;
- (void)setLabel:(id)fp8;
- (id)label;
- (BOOL)isEqualToEvent:(id)fp8;
- (void)execute;
- (id)debugDescription;
- (id)description;
- (void)dealloc;
- (id)init;

@end

