/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class BKSWorkspace, NSDate, NSMutableArray, SBAlertManager;

@interface SBWorkspaceTransaction : _ABAddressBookCopyLocalizedLabel
{
    id <SBWorkspaceTransactionDelegate> _delegate;
    int _milestones;
    BKSWorkspace *_workspace;
    SBAlertManager *_alertManager;
    BOOL _didCommit;
    BOOL _completed;
    BOOL _interrupted;
    NSDate *_startTime;
    NSMutableArray *_keepAliveReasons;
}

- (id)alertManager;
- (id)workspace;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)selfAlertDidDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfAlertWillDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfAlertDidActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfAlertWillActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)selfApplicationExited:(id)fp8;
- (BOOL)selfApplicationLaunchDidFail:(id)fp8;
- (BOOL)selfApplicationActivated:(id)fp8;
- (BOOL)selfApplicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidStartLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)selfApplicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfApplicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)selfWorkspaceDidResume;
- (BOOL)selfWorkspaceWillResume;
- (BOOL)selfWorkspaceDidSuspend;
- (BOOL)selfWorkspaceWillSuspend;
- (id)_stringForInterruptReason:(int)fp8;
- (id)_stringForMilestones:(int)fp8;
- (void)_enumerateMilestones:(int)fp8 usingBlock:(id)fp(null);
- (id)_stringForMilestone:(int)fp8;
- (BOOL)_shouldBeWatchdogged:(id *)fp8;
- (double)_watchdogInterval;
- (BOOL)_enableWatchdog;
- (BOOL)alertDidDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)alertWillDeactivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)alertDidActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)alertWillActivate:(id)fp8 overAlerts:(id)fp12;
- (BOOL)applicationExited:(id)fp8;
- (BOOL)applicationLaunchDidFail:(id)fp8;
- (BOOL)applicationActivated:(id)fp8;
- (BOOL)applicationDidFinishLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)applicationDidStartLaunching:(id)fp8 withInfo:(id)fp12;
- (BOOL)applicationDidBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)applicationWillBecomeReceiver:(id)fp8 fromApplication:(id)fp12;
- (BOOL)workspaceDidResume;
- (BOOL)workspaceWillResume;
- (BOOL)workspaceDidSuspend;
- (BOOL)workspaceWillSuspend;
- (void)_transactionComplete;
- (void)_interruptWithReason:(int)fp8;
- (BOOL)_canBeInterrupted;
- (void)_commit;
- (void)_keepalive_async:(id)fp(null);
- (void)_endKeepAliveForReason:(id)fp8;
- (void)_keepAliveForReason:(id)fp8;
- (BOOL)_hasKeepAliveReason:(id)fp8;
- (BOOL)_checkAndRemoveMilestone:(int)fp8;
- (void)_notifyDelegateOfCompletion:(BOOL)fp8;
- (void)removeMilestonesAndCheckForCompletion:(int)fp8;
- (void)_checkAndReportIfMilestonesMet;
- (BOOL)milestonesMet;
- (BOOL)waitingForMilestone:(int)fp8;
- (void)removeMilestones:(int)fp8;
- (void)addMilestones:(int)fp8;
- (void)interruptWithReason:(int)fp8;
- (void)interrupt;
- (BOOL)canBeInterrupted;
- (BOOL)completed;
- (void)commit;
- (id)description;
- (void)dealloc;
- (id)initWithWorkspace:(id)fp8 alertManager:(id)fp12;

@end

