/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@interface SBZoomView : _ABAddressBookCopyLocalizedLabel
{
}

+ (id)_chromeStatusBarImageForInterfaceOrientation:(int)fp8;
+ (struct CGSize)_rotateAndNormalizeSize:(struct CGSize)fp8 withTransform:(struct CGAffineTransform)fp16;
+ (int)_degreesForRotationFromOriginalImageOrientation:(int)fp8 toInterfaceOrientation:(int)fp12;
+ (int)_degreesForRotationFromInterfaceOrientation:(int)fp8 toInterfaceOrientation:(int)fp12;
- (void)setRoundedCorners:(int)fp8 withCornersFrame:(struct CGRect)fp12;
- (id)_initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

