/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol UIStatusBarStyleDelegate <NSObject>
- (void)statusBar:(id)fp8 didAnimateFromHeight:(float)fp12 toHeight:(float)fp16 animation:(int)fp20;
- (void)statusBar:(id)fp8 willAnimateFromHeight:(float)fp12 toHeight:(float)fp16 duration:(double)fp20 animation:(int)fp28;
- (int)statusBar:(id)fp8 styleForRequestedStyle:(int)fp12 overrides:(int)fp16;
@end

