/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

@class NSMutableSet, NSString;

@interface VolumeControl : _ABAddressBookCopyLocalizedLabel
{
    BOOL _debounce;
    int _numberOfVolumeDecreasesSinceDownButtonDown;
    int _mode;
    NSMutableSet *_alwaysHiddenCategories;
    NSString *_lastDisplayedCategory;
    NSString *_lastEventCategory;
    BOOL _hudHandledLastVolumeChange;
    BOOL _euDevice;
    float _euVolumeLimit;
    BOOL _euVolumeLimitEnforced;
    BOOL _lastVolumeChangedWasBlocked;
    BOOL _volumeDownButtonIsDown;
    BOOL _volumeUpButtonIsDown;
}

+ (id)sharedVolumeControl;
- (float)getMediaVolume;
- (void)setMediaVolume:(float)fp8;
- (void)sendEUVolumeLimitAcknowledgementIfNecessary;
- (void)_EUVolumeEnforcementChanged:(id)fp8;
- (void)_EUVolumeLimitChanged:(id)fp8;
- (BOOL)_isVolumeHUDVisibleOrFading;
- (BOOL)_isVolumeHUDVisible;
- (void)hideVolumeHUDIfVisible;
- (id)volumeHUDForCurrentCategory;
- (void)_presentVolumeHUDWithMode:(int)fp8 volume:(float)fp12;
- (id)_volumeHUDViewWithMode:(int)fp8 volume:(float)fp12;
- (BOOL)_headphonesPresent;
- (void)_effectiveVolumeChanged:(id)fp8;
- (int)_volumeModeForCategory:(id)fp8;
- (void)_serverConnectionDied:(id)fp8;
- (void)_unregisterForAVSystemControllerNotifications;
- (void)_registerForAVSystemControllerNotifications;
- (void)cancelVolumeEvent;
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;
- (void)_turnOnScreenIfNecessaryForEULimit;
- (id)lastDisplayedCategory;
- (void)decreaseVolume;
- (void)increaseVolume;
- (float)_calcButtonRepeatDelay;
- (void)_changeVolumeBy:(float)fp8;
- (BOOL)_isMusicPlayingSomewhere;
- (void)_userAcknowledgedEUEnforcement;
- (float)volume;
- (void)toggleMute;
- (BOOL)_HUDIsDisplayableForCategory:(id)fp8;
- (void)removeAlwaysHiddenCategory:(id)fp8;
- (void)addAlwaysHiddenCategory:(id)fp8;
- (void)dealloc;
- (void)_initializeEUVolumeLimits;
- (id)init;
- (float)volumeStepDown;
- (float)volumeStepUp;

@end

